# Entity disambiguation

Crear nodos unicos de entidades escritas de formas diferentes: (film director/direcor of films, nombres propios escritos con abreviaciones...)

-   Con libreria textdistance se pueden calcular metricas.
-   Con rank-bm25 es como funciona fulltext.queryNode en Neo4j, que funciona bastante bien. Tiene libreria para python

# Imports

In [1]:
import sys
import json
# import spacy
from neo4j import GraphDatabase
import pandas as pd
import numpy as np

In [2]:
from neo4j import GraphDatabase

In [3]:
import bm25s
import textdistance
import regex as re
import spacy

c:\Users\andre\anaconda3\envs\kag_env1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
sys.path.append("../src")

In [5]:
from load_data.funciones_carga_datos import load_filter_dataset_HuggingFace
from conexion_Neo4j.conexion_Neo4j import ConexionNeo4j

In [6]:
# database_Neo = "2wiki.prueba.rebel.3"
# conn_Neo4j = ConexionNeo4j(database_Neo)

In [7]:
driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=("neo4j", "password"),
    database = "2wiki.prueba.rebel.3",
)

In [8]:
def v(df_o_filtro):
    global _v
    _v = df_o_filtro
    return _v

# Rank-BM25

In [6]:
from rank_bm25 import BM25Okapi

## Prueba ejemplo

In [141]:
corpus = [
    "Hello there good man!",
    "It is quite windy in London",
    "How is the weather today?",
    "k. v. mahadevan"
]

tokenized_corpus = [doc.replace(".", " ").replace("  ", " ").split(" ") for doc in corpus]

In [142]:
tokenized_corpus

[['Hello', 'there', 'good', 'man!'],
 ['It', 'is', 'quite', 'windy', 'in', 'London'],
 ['How', 'is', 'the', 'weather', 'today?'],
 ['k', 'v', 'mahadevan']]

In [143]:
bm25 = BM25Okapi(tokenized_corpus)

In [144]:
query = "krishnankoil venkadachalam mahadevan"
tokenized_query = query.replace(".", " ").replace("  ", " ").split(" ")

doc_scores = bm25.get_scores(tokenized_query)
doc_scores

array([0.        , 0.        , 0.        , 0.99682101])

In [152]:
query = "there weather v"
tokenized_query = query.replace(".", " ").replace("  ", " ").split(" ")

doc_scores = bm25.get_scores(tokenized_query)
doc_scores

array([0.89189248, 0.        , 0.80695034, 0.99682101])

In [155]:
maximos = np.argsort(doc_scores)

In [156]:
maximos

array([1, 2, 0, 3])

In [161]:
maximos[-3:]

array([2, 0, 3])

In [162]:
doc_scores[maximos[-3:]]

array([0.80695034, 0.89189248, 0.99682101])

In [167]:
maximos_py = [i.item() for i in maximos[-3:]]
maximos_py

[2, 0, 3]

In [168]:
doc_scores[maximos_py]

array([0.80695034, 0.89189248, 0.99682101])

In [169]:
best_matches = [corpus[i] for i in maximos_py]

In [170]:
best_matches

['How is the weather today?', 'Hello there good man!', 'k. v. mahadevan']

EN FUNCION

In [7]:
def calc_rank_bm25(bm25_index, query, n_max, entidades):
    tokenized_query = query.replace(".", " ").replace("  ", " ").split(" ")
    scores = bm25_index.get_scores(tokenized_query)
    max_indices = np.argsort(scores)[-n_max:]
    max_indices_py = [i.item() for i in max_indices]
    max_scores = scores[max_indices_py]
    max_scores_py = [i.item() for i in max_scores]
    best_matches = [entidades[i] for i in max_indices_py]
    return max_scores_py, best_matches

In [8]:
corpus = [
    "Hello there good man!",
    "It is quite windy in London",
    "How is the weather today?",
    "k. v. mahadevan"
]

tokenized_corpus = [doc.replace(".", " ").replace("  ", " ").split(" ") for doc in corpus]

In [9]:
bm25 = BM25Okapi(tokenized_corpus)

In [10]:
query = "there weather v"

In [11]:
max_scores, best_matches = calc_rank_bm25(bm25, query, 3, corpus)

In [12]:
max_scores

[0.8069503432259082, 0.8918924846181091, 0.9968210122202397]

In [13]:
best_matches

['How is the weather today?', 'Hello there good man!', 'k. v. mahadevan']

BUCLE PARA VARIAS QUERIES . GUARDADO EN df

In [18]:
def calc_rank_bm25(bm25_index, query, n_max, entidades):
    tokenized_query = query.replace(".", " ").replace("  ", " ").split(" ")
    scores = bm25_index.get_scores(tokenized_query)
    max_indices = np.argsort(scores)[-n_max:]
    max_indices_py = [i.item() for i in max_indices]
    max_scores = scores[max_indices_py]
    max_scores_py = [i.item() for i in max_scores]
    best_matches = [entidades[i] for i in max_indices_py]
    return max_scores_py, best_matches

In [ ]:
def rank_bm25_disambiguation(queries, index_bm25, corpus):
    n_max = 3
    filas = []
    for query in queries:
        # print(f"Entidad: {query}")
        max_scores, best_matches = calc_rank_bm25(index_bm25, query, n_max, corpus)
        fila = max_scores + best_matches
        filas.append(fila)
        # print(f"Finaliza: {query}")
    df_bm25 = pd.DataFrame(filas, columns=['score_3_bm25', 'score_2_bm25', 'score_1_bm25', 'similar_3_bm25', 'similar_2_bm25', 'similar_1_bm25'])
    df_bm25['Entidad'] = queries
    cols_reorder = ["Entidad", "similar_1_bm25", "score_1_bm25", "similar_2_bm25", "score_2_bm25", "similar_3_bm25", "score_3_bm25"]
    df_bm25 = df_bm25[cols_reorder]
    return df_bm25

In [20]:
corpus = [
    "Hello there good man!",
    "It is quite windy in London",
    "How is the weather today?",
    "k. v. mahadevan"
]

tokenized_corpus = [doc.replace(".", " ").replace("  ", " ").split(" ") for doc in corpus]

In [21]:
bm25 = BM25Okapi(tokenized_corpus)

In [22]:
queries = ["krishnankoil venkadachalam mahadevan"]

In [26]:
queries = ["krishnankoil venkadachalam mahadevan", "krishnan venkadalam mahavan"]
df_bm25 = rank_bm25_disambiguation(queries, bm25, corpus)

Entidad: krishnankoil venkadachalam mahadevan
Finaliza: krishnankoil venkadachalam mahadevan
Entidad: krishnan venkadalam mahavan
Finaliza: krishnan venkadalam mahavan

In [27]:
df_bm25

,Entidad,similar_1_bm25,score_1_bm25,similar_2_bm25,score_2_bm25,similar_3_bm25,score_3_bm25
0,krishnankoil venkadachalam mahadevan,k. v. mahadevan,0.996821,How is the weather today?,0.0,It is quite windy in London,0.0
1,krishnan venkadalam mahavan,k. v. mahadevan,0.000000,How is the weather today?,0.0,It is quite windy in London,0.0

## CON VARIAS QUERIS - NO FUNCIONA

In [145]:
queries = ["krishnankoil venkadachalam mahadevan", "otra query de prueba"]

In [146]:
queries_tokenized = [qu.replace(".", " ").replace("  ", " ").split(" ") for qu in queries]

In [148]:
doc_scores_queries = bm25.get_scores(queries_tokenized)
doc_scores_queries

TypeError: unhashable type: 'list'

## Con las entidades de Neo4j

In [28]:
entidades = conn_Neo4j.extraer_all_entidades_neo4j()

In [29]:
len(entidades)

4858

In [30]:
def tokenize(text):
    return text.lower().replace(".", "").replace(",", "").replace("'", "").replace("  ", " ").split()

In [31]:
tokenized_corpus = [tokenize(ent) for ent in entidades]

In [32]:
bm25 = BM25Okapi(tokenized_corpus)

In [33]:
query = "krishnankoil venkadachalam mahadevan"
tokenized_query = tokenize(query)

doc_scores = bm25.get_scores(tokenized_query)
doc_scores

array([0., 0., 0., ..., 0., 0., 0.], shape=(4858,))

In [ ]:
df_bm25 = rank_bm25_disambiguation(entidades, bm25, entidades)

In [38]:
df_bm25[df_bm25['Entidad'] != df_bm25['similar_1_bm25']].head(30)

,Entidad,similar_1_bm25,score_1_bm25,similar_2_bm25,score_2_bm25,similar_3_bm25,score_3_bm25
111,mr moto,mr. moto,12.786003,mr moto,12.786003,mysterious mr. moto,10.633322
127,men's tournament,tournament,10.272367,men's tournament,8.192761,"henry lawes luttrell, 2nd earl of carhampton",0.000000
160,spencer's mountain,mountain pass,6.867283,spencer's mountain,6.867283,dark mountain,6.867283
231,catherine & co.,catherine & co,18.869633,catherine & co.,18.869633,catherine,9.201857
307,mohammed bin rashid al maktoum,rashid bin mohammed bin rashid al maktoum,19.030076,mohammed bin rashid al maktoum,18.967419,mohammed bin rashid al,17.413084
395,danger point,point danger,15.167443,danger point,15.167443,moss point,7.338972
421,the falcon's adventure,adventure,9.201857,the falcon's adventure,8.802656,adventure film,7.338972
433,the sword stained with royal blood,sword stained with royal blood,22.745620,the sword stained with royal blood,21.994690,sword of blood and valour,9.019228
473,abm fazle karim chowdhury,a.b.m. fazle karim chowdhury,20.061549,abm fazle karim chowdhury,20.061549,fazle karim chowdhury,16.625748
500,rumbold's cathedral,cathedral,8.610438,birmingham cathedral,6.867283,rumbold's cathedral,6.867283
636,that'70s show,television show,7.556323,that'70s show,7.556323,the tonight show,6.284123
713,st. mary's high school,st. mary high school,11.587204,st. teresa high school,11.587204,st. mary's high school,11.587204
722,the norman rockwell code,norman rockwell code,19.200898,the norman rockwell code,18.744347,the da vinci code,7.688893
949,raven's home,ptv home,7.828471,raven's home,7.828471,australia's funniest home video show,4.870451
965,peter o'connell,peter lorre,6.539542,peter hyams,6.539542,peter alexander,6.539542
1027,"penfield, new york","new york, new york",13.447780,new york,12.356481,new york city,10.276115
1112,"mckinleyville, california",california,7.708331,"oxnard, california",6.147805,"camarillo, california",6.147805
1554,"chicago, illinois",illinois,8.610438,"schaumburg, illinois",6.867283,"decatur, illinois",6.867283
1604,new york,"new york, new york",13.447780,new york,12.356481,new york city,10.276115
1664,"esquimalt, british columbia",british columbia,14.714317,"esquimalt, british columbia",12.236981,british,9.474379
1676,mohamed husseini,mohamed husseini mohamed,15.212463,mohamed husseini,15.060044,mohamed habash,6.867283
1806,the good old days,good old days,18.159589,the good old days,17.853092,football of the good old days,13.858921
1814,st philip's cathedral,st. rumbold's cathedral,10.940480,st philip's cathedral,10.940480,cathedral,8.610438
1839,"santa clara county, california","santa clara, california",15.097674,"santa clara county, california",12.922083,santa clara,12.006343
1915,where's the love,the love route,7.993166,all the love,7.993166,kill the love,7.993166
1929,a.b.m. fazle karim chowdhury,a. m. b. fazle karim chowdhury,21.830506,a. b. fazle karim chowdhury,20.126771,a. m. fazle karim chowdhury,20.014177
1939,"cairo, illinois",illinois,8.610438,"schaumburg, illinois",6.867283,"decatur, illinois",6.867283
2034,superior court of santa clara county,santa clara superior court,19.690666,superior court of santa clara county,19.642549,superior court,15.656942
2038,the model technical higher secondary school,model technical higher secondary school,20.434373,the model technical higher secondary school,19.941984,technical higher secondary school,18.000414
2042,banović strahinja,strahinja banović,16.385521,banović strahinja,16.385521,japanese,0.000000

In [36]:
df_bm25.sort_values("score_2_bm25", ascending=False).head(50)

,Entidad,similar_1_bm25,score_1_bm25,similar_2_bm25,score_2_bm25,similar_3_bm25,score_3_bm25
1108,why did i get married? why did i get married too?,why did i get married? why did i get married too?,43.648970,why did i get married?,40.603622,why did i get married too?,40.387245
1198,rafe kovich and alison barrington kovich,rafe kovich and alison barrington kovich,30.472926,rafe kovich and alison barrington,28.051664,alison skipper,7.828471
37,santa maría de santa cruz de la serós,santa maría de santa cruz de la serós,30.041823,santa cruz de la serós,27.722049,santa maría de oseira,20.944158
601,saeed bin maktoum bin rashid al maktoum,saeed bin maktoum bin rashid al maktoum,29.062498,rashid bin saeed al maktoum,26.945572,maktoum bin rashid al maktoum,26.390121
2181,rashid bin mohammed bin rashid al maktoum,rashid bin mohammed bin rashid al maktoum,28.914491,mohammed bin rashid al maktoum,26.485359,mohammed bin rashid al,26.014368
1400,it goes like it goes,it goes like it goes,31.861867,it goes like this,25.043057,so it goes,23.155997
285,majid bin mohammed bin rashid al maktoum,majid bin mohammed bin rashid al maktoum,25.735508,rashid bin mohammed bin rashid al maktoum,23.707535,mohammed bin rashid al maktoum,22.525025
475,hind bint maktoum bin juma al maktoum,hind bint maktoum bin juma al maktoum,26.674966,maktoum bin juma al maktoum,23.573317,hind bint maktoum,22.443076
731,the taking of pelham one two three the convers...,the taking of pelham one two three the convers...,25.096983,the taking of pelham one two three,23.554447,three days of the condor,10.139239
3725,david morris and jacqui morris,david morris and jacqui morris,26.773751,jacqui morris,23.305406,david morris,21.652188
439,why did i get married too?,why did i get married too?,24.619899,why did i get married? why did i get married too?,23.211518,why did i get married,22.623716
1206,al-hasan ibn ali ibn abi talib,al-hasan ibn ali ibn abi talib,29.147896,al-hasan ibn ali,22.975694,hasan ibn ali,16.162286
2067,rafe kovich and alison barrington,rafe kovich and alison barrington kovich,23.166414,rafe kovich and alison barrington,22.954571,alison skipper,7.828471
1280,ottawa high school and junior high school,ottawa high school and junior high school,25.977738,ottawa high school,22.720694,high school,19.981451
91,iglesia de santa maría de los reyes,iglesia de santa maría de los reyes,26.799099,iglesia de santa maría,22.446186,iglesia de santa maría de palacio,21.275034
1667,iglesia de santa maría de palacio,iglesia de santa maría de palacio,25.801955,iglesia de santa maría,22.446186,iglesia de santa maría de los reyes,19.314855
433,the sword stained with royal blood,sword stained with royal blood,22.745620,the sword stained with royal blood,21.994690,sword of blood and valour,9.019228
2224,shahzada mirza sultan muhammad farkhunda shah,shahzada mirza sultan muhammad farkhunda shah,24.365203,mirza sultan muhammad farkhunda shah,21.992931,farkhunda shah,14.831405
2435,sheikh zayed bin sultan al nahyan,sheikh zayed bin sultan al nahyan,23.456383,zayed bin sultan al nahyan,21.957430,sheikh ahmed bin rashid al maktoum,10.227285
441,mohamed husseini mohamed,mohamed husseini mohamed,23.611518,mohamed husseini,21.927327,mohamed habash,13.734566
516,jaber ii al- mubarak al- sabah,jaber ii al- mubarak al- sabah,26.772498,mubarak al- sabah,21.918948,salim al- mubarak al- sabah,20.671541
1768,salim al- mubarak al- sabah,salim al- mubarak al- sabah,26.112644,mubarak al- sabah,21.918948,jaber ii al- mubarak al- sabah,18.611720
2923,abd al- muttalib shaybah ibn hashim,abd al- muttalib shaybah ibn hashim,24.637605,abd al- muttalib shaybah,21.482323,shaybah ibn hashim,18.493051
2313,when father was away on businessunderground,when father was away on businessunderground,26.151926,when father was away on business,21.319477,ride on,6.449099
99,when father was away on business,when father was away on business,26.151926,when father was away on businessunderground,21.319477,ride on,6.449099
1856,st. vincent – st. mary high school,st. vincent – st. mary high school,26.617880,st. mary high school,21.286896,st. mary's high school,16.063032
3795,conservative national caucus chair for her maj...,conservative national caucus chair for her maj...,29.558699,conservative national caucus chair,21.158446,conservative national caucus,17.907321
4825,maktoum bin juma al maktoum,maktoum bin juma al maktoum,23.573317,juma bin maktoum,21.058509,hind bint maktoum bin juma al maktoum,19.250641
1513,european bridge team championship in croatia i...,european bridge team championship in croatia i...,27.928095,european bridge team championship,20.899781,european bridge league,12.387489
178,women's 4 × 400 metres relay event,women's 4 × 400 metres relay event,22.748278,women's 4 × 400 metres relay,20.766029,400 metres event,19.381655
2501,mr moto takes a chance,mr. moto takes a chance,20.649529,mr moto takes a chance,20.649529,mr moto takes a vacation,15.779078
2505,mr. moto takes a chance,mr. moto takes a chance,20.649529,mr moto takes a chance,20.649529,mr moto takes a vacation,15.779078
1196,rukn al- din mubarak khwaja,rukn al- din mubarak khwaja,23.393058,rukn al- din mubarak,20.538851,mubarak al- sabah,10.672958
1048,maktoum bin rashid al maktoum,maktoum bin rashid al maktoum,22.832515,saeed bin maktoum bin rashid al maktoum,20.494600,maktoum bin juma al maktoum,18.872181
4598,president of the sahrawi arab democratic republic,president of the sahrawi arab democratic republic,20.993675,sahrawi arab democratic republic,20.486565,democratic republic of the congo,12.685819
454,why did i get married?,why did i get married?,22.850357,why did i get married? why did i get married too?,20.437452,why did i get married,17.753265
1854,why did i get married,why did i get married,22.623716,why did i get married? why did i get married too?,20.308364,why did i get married too?,20.092978
820,sword stained with royal blood,sword stained with royal blood,22.745620,the sword stained with royal blood,20.201246,sword of blood and valour,9.019228
2327,a.m.b. fazle karim chowdhury,a. m. b. fazle karim chowdhury,21.830506,a. b. fazle karim chowdhury,20.126771,a. m. fazle karim chowdhury,20.014177
896,a. m. b. fazle karim chowdhury,a. m. b. fazle karim chowdhury,21.830506,a. b. fazle karim chowdhury,20.126771,a. m. fazle karim chowdhury,20.014177
1929,a.b.m. fazle karim chowdhury,a. m. b. fazle karim chowdhury,21.830506,a. b. fazle karim chowdhury,20.126771,a. m. fazle karim chowdhury,20.014177
473,abm fazle karim chowdhury,a.b.m. fazle karim chowdhury,20.061549,abm fazle karim chowdhury,20.061549,fazle karim chowdhury,16.625748
509,"walter john montagu douglas scott, 8th duke of...","walter john montagu douglas scott, 8th duke of...",21.146671,"john montagu douglas scott, 8th duke of buccleuch",19.978913,"douglas scott, 8th duke of buccleuch",17.353601
2038,the model technical higher secondary school,model technical higher secondary school,20.434373,the model technical higher secondary school,19.941984,technical higher secondary school,18.000414
2560,all nippon airways boeing 787(flight nh692),all nippon airways boeing 787(flight nh692),26.338098,boeing 787(flight nh692),19.910941,all nippon airways,19.730183
2481,tiberius julius rhescuporis iii philocaesar ph...,tiberius julius rhescuporis iii philocaesar ph...,26.890950,tiberius julius rhescuporis iii,19.840478,tiberius julius rhescuporis iv,15.250023
630,eleni zaude gabre- madhin,eleni zaude gabre- madhin,23.201339,eleni zaude gabre-,19.834312,eleni zaude gabre,13.020903
4328,chief constable of cumberland and westmorland ...,chief constable of cumberland and westmorland ...,23.449746,cumberland and westmorland constabulary,19.746589,chief constable,16.385521
2034,superior court of santa clara county,santa clara superior court,19.690666,superior court of santa clara county,19.642549,superior court,15.656942
926,a thief has arrived,a thief has arrived,20.355689,thief has arrived,19.607984,the piano tuner has arrived,9.571586

# BM25s

Lo mismo que rank-bm25 pero mucho mas rapido y con funcionalidades extra. Trae tokenizador, se puede guardar el index...

In [6]:
import bm25s

In [7]:
entidades = conn_Neo4j.extraer_all_entidades_neo4j()
len(entidades)

4858

In [8]:
entidades_tokens = bm25s.tokenize(entidades, stopwords="en")

In [9]:
retriever = bm25s.BM25()
retriever.index(entidades_tokens)

In [10]:
query = "krishnankoil venkadachalam mahadevan"
query_tokens = bm25s.tokenize(query)

In [11]:
# Get top-k results as a tuple of (doc ids, scores). Both are arrays of shape (n_queries, k).
# To return docs instead of IDs, set the `corpus=corpus` parameter.
results, scores = retriever.retrieve(query_tokens, k=4)

In [12]:
scores

array([[7.797125 , 6.3085027, 4.0111074, 0.       ]], dtype=float32)

In [13]:
results

array([[ 622, 2106, 3579,   31]])

In [14]:
print(entidades[622])
print(entidades[2106])
print(entidades[3579])
print(entidades[31])

krishnankoil venkadachalam mahadevan
krishnankoil venkadachalam
k. v. mahadevan
henry lawes luttrell, 2nd earl of carhampton

In [15]:
for i in range(results.shape[1]):
    doc, score = results[0, i], scores[0, i]
    print(f"Rank {i+1} (score: {score:.2f}): {doc}")

Rank 1 (score: 7.80): 622
Rank 2 (score: 6.31): 2106
Rank 3 (score: 4.01): 3579
Rank 4 (score: 0.00): 31

## Con todas las entidades

In [16]:
entidades_token = bm25s.tokenize(entidades, stopwords="en")

In [18]:
# results, scores = retriever.retrieve(entidades_token, k=4)
results, scores = retriever.retrieve(entidades_token, k=3)

In [19]:
results

array([[   0, 2169, 3346],
       [   1, 2071,  551],
       [   2,  581,  341],
       ...,
       [4855, 1872,   31],
       [4856, 4849, 4848],
       [4857, 4849, 4848]], shape=(4858, 3))

In [20]:
scores

array([[7.647942 , 4.0111074, 3.3039467],
       [5.9800696, 3.1542513, 2.8258183],
       [6.9683337, 6.061139 , 5.115469 ],
       ...,
       [4.0111074, 3.1542513, 0.       ],
       [4.2816963, 0.       , 0.       ],
       [4.2816963, 0.       , 0.       ]], shape=(4858, 3), dtype=float32)

### Guardado resultados en un df de pandas

In [21]:
# df_resultados = pd.DataFrame(data=results, columns=["similar_1", "similar_2", "similar_3", "similar_4"])
df_resultados = pd.DataFrame(data=results, columns=["similar_1", "similar_2", "similar_3"])

In [22]:
# df_scores = pd.DataFrame(scores, columns=["score_1", "score_2", "score_3", "score_4"])
df_scores = pd.DataFrame(scores, columns=["score_1", "score_2", "score_3"])

In [23]:
df_resultados = df_resultados.map(lambda x: entidades[x])

In [24]:
df_final = pd.concat([df_resultados, df_scores], axis=1)

In [25]:
df_final['Entidad'] = entidades

In [26]:
# cols_reorder = ["Entidad", "similar_1", "score_1", "similar_2", "score_2", "similar_3", "score_3", "similar_4", "score_4"]
cols_reorder = ["Entidad", "similar_1", "score_1", "similar_2", "score_2", "similar_3", "score_3"]

In [27]:
df_final = df_final[cols_reorder]

### Revision resultados

In [28]:
print(entidades[1820])
print(entidades[1357])

tang-e khoshk
tang -e khoshk

In [29]:
df_final[df_final['Entidad'] == 'movies']

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
4108,movies,movies,3.303947,at the movies,3.303947,merton of the movies,2.598155

In [30]:
print(entidades[449])
print(entidades[4108])

at the movies
movies

In [31]:
print(entidades[1571])
print(entidades[2163])

do you remember dolly bell?
do you remember dolly bell

In [32]:
results[1571]

array([2163, 1571, 1385])

In [33]:
df_final[df_final['score_1'] != df_final['score_2']].sort_values('score_1', ascending = False)

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
1108,why did i get married? why did i get married too?,why did i get married? why did i get married too?,17.135550,why did i get married,16.190729,why did i get married?,16.190729
1219,"you're my heart, you're my soul'98 china in he...","you're my heart, you're my soul'98 china in he...",14.260234,"you're my love, you're my life",11.263678,you're my pet,10.647292
1499,"you're my love, you're my life","you're my love, you're my life",13.546166,you're my pet,10.647292,you're my boss,10.647292
2230,"ich für dich, du für mich","ich für dich, du für mich",12.588615,sms für dich,7.797125,les amants du pont-neuf,1.922313
1198,rafe kovich and alison barrington kovich,rafe kovich and alison barrington kovich,11.813978,rafe kovich and alison barrington,10.951963,alison skipper,3.014093
...,...,...,...,...,...,...,...
3974,river,river,2.802111,colorado river,2.203521,kouga river,2.203521
2839,province,province,2.760544,mazandaran province,2.170834,markazi province,2.170834
2758,march,march,2.686077,march 1963,2.112275,"march 3, 1981",2.112275
3557,airport,airport,2.576631,erzincan airport,2.026209,international airport,2.026209
2697,school,school,2.281208,secondary school,1.793894,girls' school,1.793894

In [34]:
# df_final[df_final['score_1'] > 6]
df_final[df_final['score_2'].between(5,6)].sort_values('score_2', ascending = False).head(60)

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
590,marie louise coidavid,marie louise coidavid,7.324757,louise coidavid,5.980070,louise rousseau,2.825818
3866,"cedar park, texas","cedar park, texas",7.411015,cedar park,5.980070,texas,3.832876
2981,"moss point, mississippi","moss point, mississippi",7.411015,moss point,5.980070,mississippi,3.832876
1858,curly ray cline,curly ray cline,7.701834,ray cline,5.980070,ray mccarey,2.825818
1820,tang-e khoshk,tang-e khoshk,5.980070,tang -e khoshk,5.980070,tang dynasty,2.825818
1357,tang -e khoshk,tang-e khoshk,5.980070,tang -e khoshk,5.980070,tang dynasty,2.825818
1432,homonymous album of the year 2011,homonymous album of the year 2011,8.480229,homonymous album,5.980070,album,3.593455
1277,belcher channel formation,belcher channel formation,7.411015,belcher channel,5.980070,formation,3.832876
1968,silent film era,silent film era,6.232367,silent era,5.980070,silent film,4.409479
1983,there is so much world to see,there is so much world to see,8.059259,so much,5.980070,medeweger see,3.154251
100,the good old soak,the good old soak,7.255880,the old soak,5.980070,good old days,4.656838
2385,paula elaine downing king,paula elaine downing king,8.289376,paula e. downing,5.980070,paula king,5.309656
3418,papua new guinea,papua new guinea,7.013742,"madang, papua new guinea",5.963968,"new york, new york",2.390205
701,california redwood coast – humboldt county air...,california redwood coast – humboldt county air...,8.622736,"humboldt county, california",5.957742,humboldt county,4.862250
1572,ghilamara model higher secondary school,ghilamara model higher secondary school,7.774994,the model technical higher secondary school,5.938099,model technical higher secondary school,5.938099
1816,technical higher secondary school,technical higher secondary school,6.826878,model technical higher secondary school,5.938099,the model technical higher secondary school,5.938099
2675,joaquim pimentel ribeiro,joaquim pimentel ribeiro,6.976600,josé joaquim pimentel ribeiro,5.932385,pimentel ribeiro,5.770325
3616,mohammed bin rashid al,mohammed bin rashid al,6.426744,rashid bin mohammed bin rashid al maktoum,5.931471,mohammed bin rashid al maktou,5.590058
316,brian patrick kennedy,brian patrick kennedy,7.209269,patrick kennedy,5.923501,patrick dewaere,3.014093
2682,"academy of science fiction, fantasy and horror...","academy of science fiction, fantasy and horror...",8.731565,science fiction,5.923501,fantasy,3.832876
370,daniel gregory mason,daniel gregory mason,7.655222,daniel mason,5.923501,james mason,3.014093
432,jatt & juliet 2,jatt & juliet,5.923501,jatt & juliet 2,5.923501,jatt& juliet,5.923501
1097,miguel ernesto littin,miguel ernesto littin,7.479891,miguel littin,5.923501,ernesto lecuona,3.154251
122,legislative assembly of ontario,legislative assembly of ontario,7.278145,legislative assembly,5.923501,kerala legislative assembly,4.880850
1471,gamizaj-e olya,gamizaj -e olya,5.923501,gamizaj-e olya,5.923501,gamizaj,3.832876
1726,jatt & juliet,jatt & juliet,5.923501,jatt & juliet 2,5.923501,jatt& juliet,5.923501
1788,mark kenneth woods,mark kenneth woods,7.102814,kenneth woods,5.923501,kenneth harlan,2.909408
1894,gamizaj -e olya,gamizaj -e olya,5.923501,gamizaj-e olya,5.923501,gamizaj,3.832876
2606,richard timothy jones,richard timothy jones,6.927484,timothy jones,5.923501,felicity jones,2.909408
2512,kerala legislative assembly,kerala legislative assembly,7.364404,legislative assembly,5.923501,legislative assembly of ontario,4.880850
2521,scr corporation sdn bhd,scr corporation sdn bhd,8.373976,scr corporation,5.923501,u mobile sdn bhd,4.967109
247,jatt& juliet,jatt & juliet,5.923501,jatt & juliet 2,5.923501,jatt& juliet,5.923501
4836,boggs steps out,boggs steps out,6.961835,mr. boggs steps out,5.919830,mruggs steps out,4.362793
688,muggs steps out,muggs steps out,6.961835,mr. muggs steps out,5.919830,boggs steps out,4.362793
3339,multiple people share the name george augustus,multiple people share the name george augustus,9.064654,multiple people,5.910483,george augustus,5.014163
1640,george lamb hannah,george lamb hannah,6.730615,lamb hannah,5.910483,george lamb,5.014163
2090,bill evans trio,bill evans trio,7.469165,bill evans,5.910483,trio,4.011107
735,william marshall tredway,william marshall tredway,6.622038,marshall tredway,5.910483,william marshall,4.882392
766,frederick bradley(1908- date of death unknown),frederick bradley(1908- date of death unknown),9.460693,frederick bradley,5.910483,the unknown,4.011107
3102,odrysian kingdom of thrace,odrysian kingdom of thrace,7.469165,odrysian kingdom,5.910483,thrace,4.011107
1578,sarre anglo- saxon,sarre anglo- saxon,6.939458,sarre anglo-saxon cemetery,5.900802,sarre anglo- saxon cemetery,5.900802
2618,roman catholic archdiocese of newark,roman catholic archdiocese of newark,8.242422,roman catholic archdiocese of boston,5.883300,roman catholic,5.242640
1744,roman catholic archdiocese of boston,roman catholic archdiocese of boston,7.995131,roman catholic archdiocese of newark,5.883300,roman catholic,5.242640
1307,another latin love song,another latin love song,7.632800,another latin love song/miss world,5.874331,another latin love song/ miss world,5.874331
268,abdullah ibn atik,abdullah ibn atik,6.900262,expedition of' abdullah ibn' atik,5.867473,abdullah ibn unais,4.301220
1380,josé joaquim pimentel,josé joaquim pimentel,6.890341,josé joaquim pimentel ribeiro,5.859037,joaquim pimentel,5.452854
2344,a pretty girl milking her cow,a pretty girl milking her cow,9.442811,pretty girl,5.850874,girl,3.429164
1321,erich chiram brauer,erich chiram brauer,7.595379,erich brauer,5.850874,erich šlomović,2.696623
325,there is a man in our house,there is a man in our house,7.218302,our house,5.850874,man,3.699752
1211,hamdan bin mohammed al maktoum,hamdan bin mohammed al maktoum,7.432384,hamdan bin rashid al maktoum,5.848977,mohammed bin rashid al maktoum,5.510071
2629,indie-rock,indie-rock,5.839911,indie rock,5.839911,indie,3.832876
2331,tang-e sorkh,tang-e sorkh,5.839911,tang -e sorkh,5.839911,cheshmeh sorkh,3.014093
1126,catherine & co,catherine & co,5.839911,catherine & co.,5.839911,catherine,3.593455
231,catherine & co.,catherine & co,5.839911,catherine & co.,5.839911,catherine,3.593455
395,danger point,point danger,5.839911,danger point,5.839911,the falcon in danger,3.014093
3960,australian rules footballer,australian rules footballer,7.411016,australian rules,5.839911,australian rules football,4.811974
548,yash raj chopra,yash raj chopra,7.411015,yash chopra,5.839911,yash raj films,5.082596
668,joseph edwin johnson,joseph edwin johnson,6.952802,edwin johnson,5.839911,edwin booth,3.014093
3291,"san francisco, california","san francisco, california",6.763316,san francisco,5.839911,francisco franco,3.014093
3410,public girls' schools,public girls' schools,7.209269,girls' schools,5.839911,public,3.699752

In [35]:
df_final[df_final['score_2'] > 6].sort_values('Entidad', ascending = False)[0:5]

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
154,åke leonard lindman,åke leonard lindman,7.479892,åke lindman,6.168344,åke leonard järvinen,4.880850
1163,zayed bin sultan al nahyan,zayed bin sultan al nahyan,8.130172,sheikh zayed bin sultan al nahyan,7.193644,mohammed bin rashid al,2.888497
1499,"you're my love, you're my life","you're my love, you're my life",13.546166,you're my pet,10.647292,you're my boss,10.647292
1219,"you're my heart, you're my soul'98 china in he...","you're my heart, you're my soul'98 china in he...",14.260234,"you're my love, you're my life",11.263678,you're my pet,10.647292
178,women's 4 × 400 metres relay event,women's 4 × 400 metres relay event,9.070564,women's 4 × 400 metres relay,8.218159,400 metres event,7.393633

In [36]:
df_final[df_final['score_2'] > 6].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
1108,why did i get married? why did i get married too?,why did i get married? why did i get married too?,17.135550,why did i get married,16.190729,why did i get married?,16.190729
1219,"you're my heart, you're my soul'98 china in he...","you're my heart, you're my soul'98 china in he...",14.260234,"you're my love, you're my life",11.263678,you're my pet,10.647292
1198,rafe kovich and alison barrington kovich,rafe kovich and alison barrington kovich,11.813978,rafe kovich and alison barrington,10.951963,alison skipper,3.014093
1499,"you're my love, you're my life","you're my love, you're my life",13.546166,you're my pet,10.647292,you're my boss,10.647292
37,santa maría de santa cruz de la serós,santa maría de santa cruz de la serós,11.260831,santa cruz de la serós,10.415339,santa maría de oseira,7.920996
601,saeed bin maktoum bin rashid al maktoum,saeed bin maktoum bin rashid al maktoum,10.854058,rashid bin saeed al maktoum,10.014881,saeed bin maktoum,9.939018
2181,rashid bin mohammed bin rashid al maktoum,rashid bin mohammed bin rashid al maktoum,10.800768,mohammed bin rashid al maktoum,9.841379,mohammed bin rashid al,9.688490
3159,"new york, new york","new york, new york",10.326508,new york,9.519973,new york city,7.844273
3725,david morris and jacqui morris,david morris and jacqui morris,10.286463,jacqui morris,8.973067,david morris,8.337386
439,why did i get married too?,why did i get married? why did i get married too?,9.199800,why did i get married too?,8.963757,why did i get married,8.095365
509,"walter john montagu douglas scott, 8th duke of...","walter john montagu douglas scott, 8th duke of...",9.214789,"john montagu douglas scott, 8th duke of buccleuch",8.887913,"douglas scott, 8th duke of buccleuch",8.187313
731,the taking of pelham one two three the convers...,the taking of pelham one two three the convers...,9.673492,the taking of pelham one two three,8.880876,two for two,4.107733
285,majid bin mohammed bin rashid al maktoum,majid bin mohammed bin rashid al maktoum,9.564405,rashid bin mohammed bin rashid al maktoum,8.827232,mohammed bin rashid al maktoum,8.347178
475,hind bint maktoum bin juma al maktoum,hind bint maktoum bin juma al maktoum,9.917479,maktoum bin juma al maktoum,8.797096,hind bint maktoum,8.564016
2067,rafe kovich and alison barrington,rafe kovich and alison barrington kovich,8.747749,rafe kovich and alison barrington,8.741930,alison skipper,3.014093
2163,do you remember dolly bell,do you remember dolly bell,8.733723,do you remember dolly bell?,8.733723,a night to remember,3.014093
1571,do you remember dolly bell?,do you remember dolly bell,8.733723,do you remember dolly bell?,8.733723,a night to remember,3.014093
1280,ottawa high school and junior high school,ottawa high school and junior high school,9.882195,ottawa high school,8.681040,high school,7.709672
1400,it goes like it goes,it goes like it goes,9.467316,it goes like this,8.644634,so it goes,5.818816
990,another latin love song/ miss world,another latin love song/miss world,8.637592,another latin love song/ miss world,8.637592,another latin love song,7.632800
1899,another latin love song/miss world,another latin love song/miss world,8.637592,another latin love song/ miss world,8.637592,another latin love song,7.632800
1950,princess augusta of saxe-gotha-altenburg,princess augusta of saxe-gotha-altenburg,9.206096,augusta of saxe-gotha-altenburg,8.545527,princess augusta of saxe-gotha,8.373976
1667,iglesia de santa maría de palacio,iglesia de santa maría de palacio,9.716439,iglesia de santa maría,8.488925,church of santa maría de palacio,7.469185
91,iglesia de santa maría de los reyes,iglesia de santa maría de los reyes,10.057711,iglesia de santa maría,8.488925,church of santa maría de los reyes,8.034793
441,mohamed husseini mohamed,mohamed husseini mohamed,9.087892,mohamed husseini,8.443224,mohamed habash,5.288972
1206,al-hasan ibn ali ibn abi talib,al-hasan ibn ali ibn abi talib,10.578569,al-hasan ibn ali,8.380231,hasan ibn ali,8.274044
2560,all nippon airways boeing 787(flight nh692),all nippon airways boeing 787(flight nh692),10.195814,boeing 787(flight nh692),8.373976,all nippon airways,7.526503
2224,shahzada mirza sultan muhammad farkhunda shah,shahzada mirza sultan muhammad farkhunda shah,9.155944,mirza sultan muhammad farkhunda shah,8.295948,farkhunda shah,5.710716
178,women's 4 × 400 metres relay event,women's 4 × 400 metres relay event,9.070564,women's 4 × 400 metres relay,8.218159,400 metres event,7.393633
1056,"john montagu douglas scott, 8th duke of buccleuch","john montagu douglas scott, 8th duke of buccleuch",8.887913,"douglas scott, 8th duke of buccleuch",8.187313,"walter john montagu douglas scott, 8th duke of...",8.055804
2435,sheikh zayed bin sultan al nahyan,sheikh zayed bin sultan al nahyan,8.679896,zayed bin sultan al nahyan,8.130172,sheikh mohammed bin rashid al maktoum,3.709289
1283,"john montagu douglas scott, 7th duke of buccleuch","john montagu douglas scott, 7th duke of buccleuch",9.046721,"john montagu douglas scott, 7th",8.115438,"john montagu douglas scott, 8th duke of buccleuch",7.521532
454,why did i get married?,why did i get married,8.095365,why did i get married?,8.095365,why did i get married? why did i get married too?,7.935747
1854,why did i get married,why did i get married,8.095365,why did i get married?,8.095365,why did i get married? why did i get married too?,7.935747
4825,maktoum bin juma al maktoum,maktoum bin juma al maktoum,8.797096,juma bin maktoum,8.037101,hind bint maktoum bin juma al maktoum,7.135991
3795,conservative national caucus chair for her maj...,conservative national caucus chair for her maj...,10.718406,conservative national caucus chair,8.019625,conservative national caucus,6.832192
4586,"grande- anse, new brunswick","grande- anse, new brunswick",8.002451,"grande-anse, new brunswick",8.002451,"moncton, new brunswick",4.212955
3674,"grande-anse, new brunswick","grande- anse, new brunswick",8.002451,"grande-anse, new brunswick",8.002451,"moncton, new brunswick",4.212955
1856,st. vincent – st. mary high school,st. vincent – st. mary high school,9.499565,st. mary high school,7.984271,st. mary's high school,7.984271
433,the sword stained with royal blood,sword stained with royal blood,7.973973,the sword stained with royal blood,7.973973,sword of blood and valour,4.599501
820,sword stained with royal blood,sword stained with royal blood,7.973973,the sword stained with royal blood,7.973973,sword of blood and valour,4.599501
1513,european bridge team championship in croatia i...,european bridge team championship in croatia i...,9.321115,european bridge team championship,7.921422,european bridge league,4.725715
2923,abd al- muttalib shaybah ibn hashim,abd al- muttalib shaybah ibn hashim,9.053810,abd al- muttalib shaybah,7.876493,shaybah ibn hashim,7.055397
1949,the taking of pelham one two three,the taking of pelham one two three,8.880876,the taking of pelham one two three the convers...,7.857873,two for two,4.107733
2230,"ich für dich, du für mich","ich für dich, du für mich",12.588615,sms für dich,7.797125,les amants du pont-neuf,1.922313
2542,united arab emirates(uae),united arab emirates(uae,7.794371,united arab emirates(uae),7.794371,united arab emirates,6.682778
3669,united arab emirates(uae,united arab emirates(uae,7.794371,united arab emirates(uae),7.794371,united arab emirates,6.682778
1735,sarre anglo- saxon cemetery,sarre anglo-saxon cemetery,7.790196,sarre anglo- saxon cemetery,7.790196,sarre anglo- saxon,6.939458
1771,sarre anglo-saxon cemetery,sarre anglo-saxon cemetery,7.790196,sarre anglo- saxon cemetery,7.790196,sarre anglo- saxon,6.939458
4598,president of the sahrawi arab democratic republic,president of the sahrawi arab democratic republic,8.397519,sahrawi arab democratic republic,7.765014,democratic republic of the congo,4.469248

In [37]:
df_final[df_final['Entidad'] == "why did i get married?"].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
454,why did i get married?,why did i get married,8.095365,why did i get married?,8.095365,why did i get married? why did i get married too?,7.935747

In [38]:
df_final[df_final['Entidad'] == "you're my pet"].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3
1347,you're my pet,you're my pet,7.682767,"you're my love, you're my life",5.631839,you're my boss,5.323646

CALCULO BM25s INVERSO - FUNCIONA OK

In [ ]:

def calcular_score_inverso(fila, retriever, entidades):

    similares = [fila['similar_1'], fila['similar_2'], fila['similar_3']]
    similares_tokenized = bm25s.tokenize(similares)
    
    # 2. Buscamos en el retriever. Pedimos los top 10 o 20 resultados 
    # para asegurarnos de encontrar la entidad original (A) entre ellos
    resultados, scores = retriever.retrieve(similares_tokenized, k=20)
    
    idx_entidad = entidades.index(fila['Entidad'])

    scores_inv = []
    for i, res in enumerate(resultados):
        if idx_entidad in res:
            idx_entidad_resultado = res.tolist().index(idx_entidad)
            score = scores[i][idx_entidad_resultado]
            scores_inv.append(score)
        else:
            scores_inv.append(0)

    return scores_inv[0], scores_inv[1], scores_inv[2]

In [40]:
df_final[['score_1_inv', 'score_2_inv', 'score_3_inv']] = df_final.apply(calcular_score_inverso, args = (retriever, entidades), axis=1, result_type='expand')

In [41]:
df_final[df_final['score_2'] > 6].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3,score_1_inv,score_2_inv,score_3_inv
1108,why did i get married? why did i get married too?,why did i get married? why did i get married too?,17.135550,why did i get married,16.190729,why did i get married?,16.190729,17.135550,7.935747,7.935747
1219,"you're my heart, you're my soul'98 china in he...","you're my heart, you're my soul'98 china in he...",14.260234,"you're my love, you're my life",11.263678,you're my pet,10.647292,14.260234,8.554621,4.277310
1198,rafe kovich and alison barrington kovich,rafe kovich and alison barrington kovich,11.813978,rafe kovich and alison barrington,10.951963,alison skipper,3.014093,11.813978,8.747749,1.836896
1499,"you're my love, you're my life","you're my love, you're my life",13.546166,you're my pet,10.647292,you're my boss,10.647292,13.546166,5.631839,5.631839
37,santa maría de santa cruz de la serós,santa maría de santa cruz de la serós,11.260831,santa cruz de la serós,10.415339,santa maría de oseira,7.920996,11.260831,6.898088,4.362741
601,saeed bin maktoum bin rashid al maktoum,saeed bin maktoum bin rashid al maktoum,10.854058,rashid bin saeed al maktoum,10.014881,saeed bin maktoum,9.939018,10.854058,7.212465,5.099012
2181,rashid bin mohammed bin rashid al maktoum,rashid bin mohammed bin rashid al maktoum,10.800768,mohammed bin rashid al maktoum,9.841379,mohammed bin rashid al,9.688490,10.800768,7.053528,5.931471
3159,"new york, new york","new york, new york",10.326508,new york,9.519973,new york city,7.844273,10.326508,5.163254,5.163254
3725,david morris and jacqui morris,david morris and jacqui morris,10.286463,jacqui morris,8.973067,david morris,8.337386,10.286463,5.365927,4.920536
439,why did i get married too?,why did i get married? why did i get married too?,9.199800,why did i get married too?,8.963757,why did i get married,8.095365,16.005199,8.963757,7.041444
509,"walter john montagu douglas scott, 8th duke of...","walter john montagu douglas scott, 8th duke of...",9.214789,"john montagu douglas scott, 8th duke of buccleuch",8.887913,"douglas scott, 8th duke of buccleuch",8.187313,9.214789,8.055804,5.887763
731,the taking of pelham one two three the convers...,the taking of pelham one two three the convers...,9.673492,the taking of pelham one two three,8.880876,two for two,4.107733,9.673492,7.857873,3.137702
285,majid bin mohammed bin rashid al maktoum,majid bin mohammed bin rashid al maktoum,9.564405,rashid bin mohammed bin rashid al maktoum,8.827232,mohammed bin rashid al maktoum,8.347178,9.564405,9.224735,6.265512
475,hind bint maktoum bin juma al maktoum,hind bint maktoum bin juma al maktoum,9.917479,maktoum bin juma al maktoum,8.797096,hind bint maktoum,8.564016,9.917479,7.135991,4.649377
2067,rafe kovich and alison barrington,rafe kovich and alison barrington kovich,8.747749,rafe kovich and alison barrington,8.741930,alison skipper,3.014093,10.951963,8.741930,2.111831
2163,do you remember dolly bell,do you remember dolly bell,8.733723,do you remember dolly bell?,8.733723,a night to remember,3.014093,8.733723,8.733723,1.836896
1571,do you remember dolly bell?,do you remember dolly bell,8.733723,do you remember dolly bell?,8.733723,a night to remember,3.014093,8.733723,8.733723,1.836896
1280,ottawa high school and junior high school,ottawa high school and junior high school,9.882195,ottawa high school,8.681040,high school,7.709672,9.882195,4.918560,3.394784
1400,it goes like it goes,it goes like it goes,9.467316,it goes like this,8.644634,so it goes,5.818816,9.467316,5.897867,3.569448
990,another latin love song/ miss world,another latin love song/miss world,8.637592,another latin love song/ miss world,8.637592,another latin love song,7.632800,8.637592,8.637592,5.874331
1899,another latin love song/miss world,another latin love song/miss world,8.637592,another latin love song/ miss world,8.637592,another latin love song,7.632800,8.637592,8.637592,5.874331
1950,princess augusta of saxe-gotha-altenburg,princess augusta of saxe-gotha-altenburg,9.206096,augusta of saxe-gotha-altenburg,8.545527,princess augusta of saxe-gotha,8.373976,9.206096,7.433000,7.283783
1667,iglesia de santa maría de palacio,iglesia de santa maría de palacio,9.716439,iglesia de santa maría,8.488925,church of santa maría de palacio,7.469185,9.716439,6.103803,6.179381
91,iglesia de santa maría de los reyes,iglesia de santa maría de los reyes,10.057711,iglesia de santa maría,8.488925,church of santa maría de los reyes,8.034793,10.057711,5.506429,6.852900
441,mohamed husseini mohamed,mohamed husseini mohamed,9.087892,mohamed husseini,8.443224,mohamed habash,5.288972,9.087892,5.843467,3.244425
1206,al-hasan ibn ali ibn abi talib,al-hasan ibn ali ibn abi talib,10.578569,al-hasan ibn ali,8.380231,hasan ibn ali,8.274044,10.578569,5.395197,4.467264
2560,all nippon airways boeing 787(flight nh692),all nippon airways boeing 787(flight nh692),10.195814,boeing 787(flight nh692),8.373976,all nippon airways,7.526503,10.195814,5.779055,4.416760
2224,shahzada mirza sultan muhammad farkhunda shah,shahzada mirza sultan muhammad farkhunda shah,9.155944,mirza sultan muhammad farkhunda shah,8.295948,farkhunda shah,5.710716,9.155944,7.340325,3.079411
178,women's 4 × 400 metres relay event,women's 4 × 400 metres relay event,9.070564,women's 4 × 400 metres relay,8.218159,400 metres event,7.393633,9.070564,7.148252,5.468506
1056,"john montagu douglas scott, 8th duke of buccleuch","john montagu douglas scott, 8th duke of buccleuch",8.887913,"douglas scott, 8th duke of buccleuch",8.187313,"walter john montagu douglas scott, 8th duke of...",8.055804,8.887913,6.495927,8.887913
2435,sheikh zayed bin sultan al nahyan,sheikh zayed bin sultan al nahyan,8.679896,zayed bin sultan al nahyan,8.130172,sheikh mohammed bin rashid al maktoum,3.709289,8.679896,7.193644,3.709289
1283,"john montagu douglas scott, 7th duke of buccleuch","john montagu douglas scott, 7th duke of buccleuch",9.046721,"john montagu douglas scott, 7th",8.115438,"john montagu douglas scott, 8th duke of buccleuch",7.521532,9.046721,6.438901,7.521532
454,why did i get married?,why did i get married,8.095365,why did i get married?,8.095365,why did i get married? why did i get married too?,7.935747,8.095365,8.095365,16.190729
1854,why did i get married,why did i get married,8.095365,why did i get married?,8.095365,why did i get married? why did i get married too?,7.935747,8.095365,8.095365,16.190729
4825,maktoum bin juma al maktoum,maktoum bin juma al maktoum,8.797096,juma bin maktoum,8.037101,hind bint maktoum bin juma al maktoum,7.135991,8.797096,5.371776,8.797096
3795,conservative national caucus chair for her maj...,conservative national caucus chair for her maj...,10.718406,conservative national caucus chair,8.019625,conservative national caucus,6.832192,10.718406,5.016354,3.633956
4586,"grande- anse, new brunswick","grande- anse, new brunswick",8.002451,"grande-anse, new brunswick",8.002451,"moncton, new brunswick",4.212955,8.002451,8.002451,3.582385
3674,"grande-anse, new brunswick","grande- anse, new brunswick",8.002451,"grande-anse, new brunswick",8.002451,"moncton, new brunswick",4.212955,8.002451,8.002451,3.582385
1856,st. vincent – st. mary high school,st. vincent – st. mary high school,9.499565,st. mary high school,7.984271,st. mary's high school,7.984271,9.499565,5.665727,5.665727
433,the sword stained with royal blood,sword stained with royal blood,7.973973,the sword stained with royal blood,7.973973,sword of blood and valour,4.599501,7.973973,7.973973,3.911075
820,sword stained with royal blood,sword stained with royal blood,7.973973,the sword stained with royal blood,7.973973,sword of blood and valour,4.599501,7.973973,7.973973,3.911075
1513,european bridge team championship in croatia i...,european bridge team championship in croatia i...,9.321115,european bridge team championship,7.921422,european bridge league,4.725715,9.321115,6.096459,3.092627
2923,abd al- muttalib shaybah ibn hashim,abd al- muttalib shaybah ibn hashim,9.053810,abd al- muttalib shaybah,7.876493,shaybah ibn hashim,7.055397,9.053810,6.061881,4.617230
1949,the taking of pelham one two three,the taking of pelham one two three,8.880876,the taking of pelham one two three the convers...,7.857873,two for two,4.107733,8.880876,8.880876,3.546193
2230,"ich für dich, du für mich","ich für dich, du für mich",12.588615,sms für dich,7.797125,les amants du pont-neuf,1.922313,12.588615,4.478688,1.700879
2542,united arab emirates(uae),united arab emirates(uae,7.794371,united arab emirates(uae),7.794371,united arab emirates,6.682778,7.794371,7.794371,5.682540
3669,united arab emirates(uae,united arab emirates(uae,7.794371,united arab emirates(uae),7.794371,united arab emirates,6.682778,7.794371,7.794371,5.682540
1735,sarre anglo- saxon cemetery,sarre anglo-saxon cemetery,7.790196,sarre anglo- saxon cemetery,7.790196,sarre anglo- saxon,6.939458,7.790196,7.790196,5.900802
1771,sarre anglo-saxon cemetery,sarre anglo-saxon cemetery,7.790196,sarre anglo- saxon cemetery,7.790196,sarre anglo- saxon,6.939458,7.790196,7.790196,5.900802
4598,president of the sahrawi arab democratic republic,president of the sahrawi arab democratic republic,8.397519,sahrawi arab democratic republic,7.765014,democratic republic of the congo,4.469248,8.397519,6.754101,3.305562

In [43]:
df_final[df_final['Entidad'] == 'rosie and the goldbug']

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3,score_1_inv,score_2_inv,score_3_inv
1872,rosie and the goldbug,rosie and the goldbug,6.168344,goldbug,4.011107,rosie,3.832876,6.168344,3.154251,3.014093

# Distancias entre textos

In [44]:
import textdistance

In [51]:
def calcular_jaro_winkler(fila):
    dist_jaro_1 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_1'])
    dist_jaro_2 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_2'])
    dist_jaro_3 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_3'])
    return dist_jaro_1, dist_jaro_2, dist_jaro_3

In [60]:
def calcular_levenshtein(fila):
    dist_leven_1 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_1'])
    dist_leven_2 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_2'])
    dist_leven_3 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_3'])
    return dist_leven_1, dist_leven_2, dist_leven_3

In [52]:
df_final[['dist_jaro_1', 'dist_jaro_2', 'dist_jaro_3']] = df_final.apply(calcular_jaro_winkler, axis = 1, result_type='expand')

In [61]:
df_final[['dist_leven_1', 'dist_leven_2', 'dist_leven_3']] = df_final.apply(calcular_levenshtein, axis = 1, result_type='expand')

In [56]:
df_final['Entidad'][1219]

"you're my heart, you're my soul'98 china in her eyes"

In [63]:
df_final.columns

Index(['Entidad', 'similar_1', 'score_1', 'similar_2', 'score_2', 'similar_3',
       'score_3', 'score_1_inv', 'score_2_inv', 'score_3_inv', 'dist_jaro_1',
       'dist_jaro_2', 'dist_jaro_3', 'dist_leven_1', 'dist_leven_2',
       'dist_leven_3'],
      dtype='object')

In [64]:
cols_ = ['Entidad', 'similar_1', 'score_1', 'score_1_inv', 'dist_jaro_1', 'dist_leven_1', 'similar_2', 'score_2', 'score_2_inv', 'dist_jaro_2', 'dist_leven_2']

In [65]:
df_final[df_final['score_2'] > 6][cols_].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,score_1_inv,dist_jaro_1,dist_leven_1,similar_2,score_2,score_2_inv,dist_jaro_2,dist_leven_2
1108,why did i get married? why did i get married too?,why did i get married? why did i get married too?,17.135550,17.135550,1.000000,1.000000,why did i get married,16.190729,7.935747,0.885714,0.428571
1219,"you're my heart, you're my soul'98 china in he...","you're my heart, you're my soul'98 china in he...",14.260234,14.260234,1.000000,1.000000,"you're my love, you're my life",11.263678,8.554621,0.831994,0.480769
1198,rafe kovich and alison barrington kovich,rafe kovich and alison barrington kovich,11.813978,11.813978,1.000000,1.000000,rafe kovich and alison barrington,10.951963,8.747749,0.965000,0.825000
1499,"you're my love, you're my life","you're my love, you're my life",13.546166,13.546166,1.000000,1.000000,you're my pet,10.647292,5.631839,0.842564,0.366667
37,santa maría de santa cruz de la serós,santa maría de santa cruz de la serós,11.260831,11.260831,1.000000,1.000000,santa cruz de la serós,10.415339,6.898088,0.864373,0.594595
601,saeed bin maktoum bin rashid al maktoum,saeed bin maktoum bin rashid al maktoum,10.854058,10.854058,1.000000,1.000000,rashid bin saeed al maktoum,10.014881,7.212465,0.695651,0.512821
2181,rashid bin mohammed bin rashid al maktoum,rashid bin mohammed bin rashid al maktoum,10.800768,10.800768,1.000000,1.000000,mohammed bin rashid al maktoum,9.841379,7.053528,0.788347,0.731707
3159,"new york, new york","new york, new york",10.326508,10.326508,1.000000,1.000000,new york,9.519973,5.163254,0.888889,0.444444
3725,david morris and jacqui morris,david morris and jacqui morris,10.286463,10.286463,1.000000,1.000000,jacqui morris,8.973067,5.365927,0.664103,0.433333
439,why did i get married too?,why did i get married? why did i get married too?,9.199800,16.005199,0.890738,0.530612,why did i get married too?,8.963757,8.963757,1.000000,1.000000
509,"walter john montagu douglas scott, 8th duke of...","walter john montagu douglas scott, 8th duke of...",9.214789,9.214789,1.000000,1.000000,"john montagu douglas scott, 8th duke of buccleuch",8.887913,8.055804,0.815476,0.875000
731,the taking of pelham one two three the convers...,the taking of pelham one two three the convers...,9.673492,9.673492,1.000000,1.000000,the taking of pelham one two three,8.880876,7.857873,0.933333,0.666667
285,majid bin mohammed bin rashid al maktoum,majid bin mohammed bin rashid al maktoum,9.564405,9.564405,1.000000,1.000000,rashid bin mohammed bin rashid al maktoum,8.827232,9.224735,0.897540,0.926829
475,hind bint maktoum bin juma al maktoum,hind bint maktoum bin juma al maktoum,9.917479,9.917479,1.000000,1.000000,maktoum bin juma al maktoum,8.797096,7.135991,0.774107,0.729730
2067,rafe kovich and alison barrington,rafe kovich and alison barrington kovich,8.747749,10.951963,0.965000,0.825000,rafe kovich and alison barrington,8.741930,8.741930,1.000000,1.000000
2163,do you remember dolly bell,do you remember dolly bell,8.733723,8.733723,1.000000,1.000000,do you remember dolly bell?,8.733723,8.733723,0.992593,0.962963
1571,do you remember dolly bell?,do you remember dolly bell,8.733723,8.733723,0.992593,0.962963,do you remember dolly bell?,8.733723,8.733723,1.000000,1.000000
1280,ottawa high school and junior high school,ottawa high school and junior high school,9.882195,9.882195,1.000000,1.000000,ottawa high school,8.681040,4.918560,0.887805,0.439024
1400,it goes like it goes,it goes like it goes,9.467316,9.467316,1.000000,1.000000,it goes like this,8.644634,5.897867,0.935735,0.750000
990,another latin love song/ miss world,another latin love song/miss world,8.637592,8.637592,0.982521,0.971429,another latin love song/ miss world,8.637592,8.637592,1.000000,1.000000
1899,another latin love song/miss world,another latin love song/miss world,8.637592,8.637592,1.000000,1.000000,another latin love song/ miss world,8.637592,8.637592,0.982521,0.971429
1950,princess augusta of saxe-gotha-altenburg,princess augusta of saxe-gotha-altenburg,9.206096,9.206096,1.000000,1.000000,augusta of saxe-gotha-altenburg,8.545527,7.433000,0.795968,0.775000
1667,iglesia de santa maría de palacio,iglesia de santa maría de palacio,9.716439,9.716439,1.000000,1.000000,iglesia de santa maría,8.488925,6.103803,0.933333,0.666667
91,iglesia de santa maría de los reyes,iglesia de santa maría de los reyes,10.057711,10.057711,1.000000,1.000000,iglesia de santa maría,8.488925,5.506429,0.925714,0.628571
441,mohamed husseini mohamed,mohamed husseini mohamed,9.087892,9.087892,1.000000,1.000000,mohamed husseini,8.443224,5.843467,0.933333,0.666667
1206,al-hasan ibn ali ibn abi talib,al-hasan ibn ali ibn abi talib,10.578569,10.578569,1.000000,1.000000,al-hasan ibn ali,8.380231,5.395197,0.906667,0.533333
2560,all nippon airways boeing 787(flight nh692),all nippon airways boeing 787(flight nh692),10.195814,10.195814,1.000000,1.000000,boeing 787(flight nh692),8.373976,5.779055,0.741602,0.558140
2224,shahzada mirza sultan muhammad farkhunda shah,shahzada mirza sultan muhammad farkhunda shah,9.155944,9.155944,1.000000,1.000000,mirza sultan muhammad farkhunda shah,8.295948,7.340325,0.794444,0.800000
178,women's 4 × 400 metres relay event,women's 4 × 400 metres relay event,9.070564,9.070564,1.000000,1.000000,women's 4 × 400 metres relay,8.218159,7.148252,0.964706,0.823529
1056,"john montagu douglas scott, 8th duke of buccleuch","john montagu douglas scott, 8th duke of buccleuch",8.887913,8.887913,1.000000,1.000000,"douglas scott, 8th duke of buccleuch",8.187313,6.495927,0.763416,0.734694
2435,sheikh zayed bin sultan al nahyan,sheikh zayed bin sultan al nahyan,8.679896,8.679896,1.000000,1.000000,zayed bin sultan al nahyan,8.130172,7.193644,0.801088,0.787879
1283,"john montagu douglas scott, 7th duke of buccleuch","john montagu douglas scott, 7th duke of buccleuch",9.046721,9.046721,1.000000,1.000000,"john montagu douglas scott, 7th",8.115438,6.438901,0.926531,0.632653
454,why did i get married?,why did i get married,8.095365,8.095365,0.990909,0.954545,why did i get married?,8.095365,8.095365,1.000000,1.000000
1854,why did i get married,why did i get married,8.095365,8.095365,1.000000,1.000000,why did i get married?,8.095365,8.095365,0.990909,0.954545
4825,maktoum bin juma al maktoum,maktoum bin juma al maktoum,8.797096,8.797096,1.000000,1.000000,juma bin maktoum,8.037101,5.371776,0.697531,0.481481
3795,conservative national caucus chair for her maj...,conservative national caucus chair for her maj...,10.718406,10.718406,1.000000,1.000000,conservative national caucus chair,8.019625,5.016354,0.897143,0.485714
4586,"grande- anse, new brunswick","grande- anse, new brunswick",8.002451,8.002451,1.000000,1.000000,"grande-anse, new brunswick",8.002451,8.002451,0.954131,0.962963
3674,"grande-anse, new brunswick","grande- anse, new brunswick",8.002451,8.002451,0.954131,0.962963,"grande-anse, new brunswick",8.002451,8.002451,1.000000,1.000000
1856,st. vincent – st. mary high school,st. vincent – st. mary high school,9.499565,9.499565,1.000000,1.000000,st. mary high school,7.984271,5.665727,0.857647,0.588235
433,the sword stained with royal blood,sword stained with royal blood,7.973973,7.973973,0.827451,0.882353,the sword stained with royal blood,7.973973,7.973973,1.000000,1.000000
820,sword stained with royal blood,sword stained with royal blood,7.973973,7.973973,1.000000,1.000000,the sword stained with royal blood,7.973973,7.973973,0.827451,0.882353
1513,european bridge team championship in croatia i...,european bridge team championship in croatia i...,9.321115,9.321115,1.000000,1.000000,european bridge team championship,7.921422,6.096459,0.926923,0.634615
2923,abd al- muttalib shaybah ibn hashim,abd al- muttalib shaybah ibn hashim,9.053810,9.053810,1.000000,1.000000,abd al- muttalib shaybah,7.876493,6.061881,0.937143,0.685714
1949,the taking of pelham one two three,the taking of pelham one two three,8.880876,8.880876,1.000000,1.000000,the taking of pelham one two three the convers...,7.857873,8.880876,0.933333,0.666667
2230,"ich für dich, du für mich","ich für dich, du für mich",12.588615,12.588615,1.000000,1.000000,sms für dich,7.797125,4.478688,0.555185,0.360000
2542,united arab emirates(uae),united arab emirates(uae,7.794371,7.794371,0.992000,0.960000,united arab emirates(uae),7.794371,7.794371,1.000000,1.000000
3669,united arab emirates(uae,united arab emirates(uae,7.794371,7.794371,1.000000,1.000000,united arab emirates(uae),7.794371,7.794371,0.992000,0.960000
1735,sarre anglo- saxon cemetery,sarre anglo-saxon cemetery,7.790196,7.790196,0.969516,0.962963,sarre anglo- saxon cemetery,7.790196,7.790196,1.000000,1.000000
1771,sarre anglo-saxon cemetery,sarre anglo-saxon cemetery,7.790196,7.790196,1.000000,1.000000,sarre anglo- saxon cemetery,7.790196,7.790196,0.969516,0.962963
4598,president of the sahrawi arab democratic republic,president of the sahrawi arab democratic republic,8.397519,8.397519,1.000000,1.000000,sahrawi arab democratic republic,7.765014,6.754101,0.748937,0.653061

In [68]:
df_final[(df_final['dist_jaro_2'].between(0.9, 0.999) ) & (df_final['dist_leven_2'].between(0.9, 0.999) )][cols_].sort_values('score_2', ascending = False)[0:50]

,Entidad,similar_1,score_1,score_1_inv,dist_jaro_1,dist_leven_1,similar_2,score_2,score_2_inv,dist_jaro_2,dist_leven_2
2163,do you remember dolly bell,do you remember dolly bell,8.733723,8.733723,1.000000,1.000000,do you remember dolly bell?,8.733723,8.733723,0.992593,0.962963
1899,another latin love song/miss world,another latin love song/miss world,8.637592,8.637592,1.000000,1.000000,another latin love song/ miss world,8.637592,8.637592,0.982521,0.971429
1854,why did i get married,why did i get married,8.095365,8.095365,1.000000,1.000000,why did i get married?,8.095365,8.095365,0.990909,0.954545
4586,"grande- anse, new brunswick","grande- anse, new brunswick",8.002451,8.002451,1.000000,1.000000,"grande-anse, new brunswick",8.002451,8.002451,0.954131,0.962963
3669,united arab emirates(uae,united arab emirates(uae,7.794371,7.794371,1.000000,1.000000,united arab emirates(uae),7.794371,7.794371,0.992000,0.960000
1771,sarre anglo-saxon cemetery,sarre anglo-saxon cemetery,7.790196,7.790196,1.000000,1.000000,sarre anglo- saxon cemetery,7.790196,7.790196,0.969516,0.962963
2340,william marshall(died 1540),william marshall(died 1540),7.742723,7.742723,1.000000,1.000000,william marshall(died 1540?),7.742723,7.742723,0.992857,0.964286
4166,warmian-masurian voivodeship,warmian-masurian voivodeship,7.681638,7.681638,1.000000,1.000000,warmian- masurian voivodeship,7.681638,7.681638,0.964532,0.965517
2505,mr. moto takes a chance,mr. moto takes a chance,7.549897,7.549897,1.000000,1.000000,mr moto takes a chance,7.549897,7.549897,0.988406,0.956522
4815,eleni zaude gabre-,eleni zaude gabre-,7.450663,7.450663,1.000000,1.000000,eleni zaude gabre,7.450663,7.450663,0.988889,0.944444
4480,metro- goldwyn- mayer,metro-goldwyn- mayer,7.450663,7.450663,0.950476,0.952381,metro-goldwyn-mayer,7.450663,7.450663,0.980952,0.904762
4409,metro-goldwyn- mayer,metro-goldwyn- mayer,7.450663,7.450663,1.000000,1.000000,metro-goldwyn-mayer,7.450663,7.450663,0.990000,0.950000
850,"sir andrew agnew, 2nd baronet","sir andrew agnew, 2nd baronet",9.198162,9.198162,1.000000,1.000000,"sir andrew agnew, 3rd baronet",7.361267,7.361267,0.965006,0.931034
968,"sir andrew agnew, 3rd baronet","sir andrew agnew, 3rd baronet",9.283579,9.283579,1.000000,1.000000,"sir andrew agnew, 2nd baronet",7.361267,7.361267,0.965006,0.931034
3865,dubai's ruling family,dubai's ruling family,7.261600,7.261600,1.000000,1.000000,dubai ruling family,7.261600,7.261600,0.980952,0.904762
650,dasht -e rum rural district,dasht -e rum rural district,7.096749,7.096749,1.000000,1.000000,dasht-e rum rural district,7.096749,7.096749,0.946439,0.962963
3897,poshtkuh-e rostam rural district,poshtkuh-e rostam rural district,7.096749,7.096749,1.000000,1.000000,poshtkuh -e rostam rural district,7.096749,7.096749,0.943939,0.969697
3270,malcolm st clair,malcolm st clair,7.078288,7.078288,1.000000,1.000000,malcolm st. clair,7.078288,7.078288,0.988235,0.941176
2814,kohgiluyeh and boyer- ahmad province,kohgiluyeh and boyer- ahmad province,6.870686,6.870686,1.000000,1.000000,kohgiluyeh and boyer-ahmad province,6.870686,6.870686,0.977302,0.972222
4645,anglo-saxon cemetery,anglo-saxon cemetery,6.764127,6.764127,1.000000,1.000000,anglo- saxon cemetery,6.764127,6.764127,0.960476,0.952381
2366,mr moto's gamble,mr moto's gamble,6.597018,6.597018,1.000000,1.000000,mr. moto's gamble,6.597018,6.597018,0.984314,0.941176
2045,university of wisconsin – madison,university of wisconsin – madison,6.462907,6.462907,1.000000,1.000000,university of wisconsin- madison,6.462907,6.462907,0.981629,0.939394
1929,a.b.m. fazle karim chowdhury,a. b. fazle karim chowdhury,6.343851,6.343851,0.950563,0.892857,a.m.b. fazle karim chowdhury,6.343851,6.343851,0.990476,0.928571
896,a. m. b. fazle karim chowdhury,a. b. fazle karim chowdhury,6.343851,6.343851,0.924815,0.900000,a.m.b. fazle karim chowdhury,6.343851,6.343851,0.906032,0.933333
490,st. mary high school,st. mary high school,6.287282,6.287282,1.000000,1.000000,st. mary's high school,6.287282,6.287282,0.951818,0.909091
4528,peer- reviewed,peer- reviewed,6.063659,6.063659,1.000000,1.000000,peer-reviewed,6.063659,6.063659,0.985714,0.928571
4051,peer- review,peer- review,6.063659,6.063659,1.000000,1.000000,peer-review,6.063659,6.063659,0.983333,0.916667
1820,tang-e khoshk,tang-e khoshk,5.980070,5.980070,1.000000,1.000000,tang -e khoshk,5.980070,5.980070,0.970330,0.928571
1894,gamizaj -e olya,gamizaj -e olya,5.923501,5.923501,1.000000,1.000000,gamizaj-e olya,5.923501,5.923501,0.972381,0.933333
1126,catherine & co,catherine & co,5.839911,5.839911,1.000000,1.000000,catherine & co.,5.839911,5.839911,0.986667,0.933333
2629,indie-rock,indie-rock,5.839911,5.839911,1.000000,1.000000,indie rock,5.839911,5.839911,0.960000,0.900000
2331,tang-e sorkh,tang-e sorkh,5.839911,5.839911,1.000000,1.000000,tang -e sorkh,5.839911,5.839911,0.967949,0.923077
1287,tiberius julius rhescuporis ii,tiberius julius rhescuporis ii,7.406119,7.406119,1.000000,1.000000,tiberius julius rhescuporis iii,5.780234,5.780234,0.993548,0.967742
2609,tiberius julius rhescuporis iv,tiberius julius rhescuporis iv,7.760149,7.760149,1.000000,1.000000,tiberius julius rhescuporis iii,5.780234,5.780234,0.980430,0.935484
2534,tiberius julius rhescuporis iii,tiberius julius rhescuporis iii,7.520540,7.520540,1.000000,1.000000,tiberius julius rhescuporis iv,5.780234,5.780234,0.980430,0.935484
224,boyer- ahmad county,boyer- ahmad county,5.738927,5.738927,1.000000,1.000000,boyer-ahmad county,5.738927,5.738927,0.956140,0.947368
2523,38th venice international film festival,38th venice international film festival,7.465407,7.465407,1.000000,1.000000,67th venice international film festival,5.413415,5.413415,0.965812,0.948718
2035,67th venice international film festival,67th venice international film festival,7.465407,7.465407,1.000000,1.000000,38th venice international film festival,5.413415,5.413415,0.965812,0.948718
1118,township high school district 211,township high school district 211,7.449911,7.449911,1.000000,1.000000,township high school district 214,5.397919,5.397919,0.987879,0.969697
2978,township high school district 214,township high school district 214,7.449911,7.449911,1.000000,1.000000,township high school district 211,5.397919,5.397919,0.987879,0.969697
2664,13th moscow international film festival,13th moscow international film festival,7.093161,7.093161,1.000000,1.000000,8th moscow international film festival,5.256265,5.256265,0.974134,0.948718
755,11th berlin international film festival,11th berlin international film festival,7.308257,7.308257,1.000000,1.000000,12th berlin international film festival,5.256265,5.256265,0.984615,0.974359
653,9th berlin international film festival,9th berlin international film festival,7.308257,7.308257,1.000000,1.000000,12th berlin international film festival,5.256265,5.256265,0.974134,0.948718
1155,north-central,north-central,5.240069,5.240069,1.000000,1.000000,north- central,5.240069,5.240069,0.985714,0.928571
3997,comedy- drama film,comedy- drama film,5.171711,5.171711,1.000000,1.000000,comedy drama film,5.171711,5.171711,0.988889,0.944444
4183,kohgiluyeh and boyer-,kohgiluyeh and boyer-,5.116725,5.116725,1.000000,1.000000,kohgiluyeh and boyer,5.116725,5.116725,0.990476,0.952381
3822,5 january 1973,5 january 1973,4.896758,4.896758,1.000000,1.000000,4 january 1973,4.896758,4.896758,0.952381,0.928571
2650,17th lok sabha,17th lok sabha,7.393632,7.393632,1.000000,1.000000,14th lok sabha,4.794591,4.794591,0.957143,0.928571
2443,14th lok sabha,14th lok sabha,7.568964,7.568964,1.000000,1.000000,17th lok sabha,4.794591,4.794591,0.957143,0.928571
2377,13th lok sabha,13th lok sabha,7.278145,7.278145,1.000000,1.000000,14th lok sabha,4.794591,4.794591,0.957143,0.928571

# Excluir fechas, numeros romanos y numeros al lado de texto de la fusion

In [69]:
import regex as re

In [71]:
def excluir_de_fusion(fila):
    excluir = False
    regex_romanos = r'\b(v[ii]{0,3}|i[vx]|x[lcvi]{0,4}|i{1,3})\b'
    romanos_a = set(re.findall(regex_romanos, fila['Entidad']))
    romanos_b = set(re.findall(regex_romanos, fila['similar_2']))
    if romanos_a and romanos_b and romanos_a != romanos_b:
        excluir = True
    numeros_a = set(re.findall(r'\d+', fila['Entidad']))
    numeros_b = set(re.findall(r'\d+', fila['similar_2']))

    if numeros_a and numeros_b and numeros_a != numeros_b:
        excluir = True
    return excluir

In [74]:
df_final['excluir_2'] = df_final.apply(excluir_de_fusion, axis = 1)

In [84]:
cols_ = ['Entidad', 'similar_1', 'score_1', 'score_1_inv', 'dist_jaro_1', 'dist_leven_1', 'similar_2', 'score_2', 'score_2_inv', 'dist_jaro_2', 'dist_leven_2', 'excluir_2']

In [88]:
df_final[
    (df_final['dist_jaro_2'].between(0.85, 0.999)) &
    (df_final['dist_leven_2'].between(0.85, 0.999)) &
    (df_final['excluir_2'] == False)
    ][cols_].sort_values('score_2', ascending = False)

,Entidad,similar_1,score_1,score_1_inv,dist_jaro_1,dist_leven_1,similar_2,score_2,score_2_inv,dist_jaro_2,dist_leven_2,excluir_2
285,majid bin mohammed bin rashid al maktoum,majid bin mohammed bin rashid al maktoum,9.564405,9.564405,1.0,1.0,rashid bin mohammed bin rashid al maktoum,8.827232,9.224735,0.897540,0.926829,False
2163,do you remember dolly bell,do you remember dolly bell,8.733723,8.733723,1.0,1.0,do you remember dolly bell?,8.733723,8.733723,0.992593,0.962963,False
1899,another latin love song/miss world,another latin love song/miss world,8.637592,8.637592,1.0,1.0,another latin love song/ miss world,8.637592,8.637592,0.982521,0.971429,False
1854,why did i get married,why did i get married,8.095365,8.095365,1.0,1.0,why did i get married?,8.095365,8.095365,0.990909,0.954545,False
4586,"grande- anse, new brunswick","grande- anse, new brunswick",8.002451,8.002451,1.0,1.0,"grande-anse, new brunswick",8.002451,8.002451,0.954131,0.962963,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1088,luciano orodisio,luciano orodisio,6.381130,6.381130,1.0,1.0,luciano odorisio,3.014093,3.014093,0.987500,0.875000,False
4030,nandi awards,nandi awards,6.028187,6.028187,1.0,1.0,nandi award,3.014093,3.014093,0.983333,0.916667,False
3197,mass cycles,mass cycles,6.381130,6.381130,1.0,1.0,mass cycle,3.014093,3.014093,0.981818,0.909091,False
680,trade register,trade register,6.063659,6.063659,1.0,1.0,trade registers,2.909408,2.909408,0.986667,0.933333,False
3861,girls' school,girls' school,4.619713,4.619713,1.0,1.0,girls' schools,2.825818,2.825818,0.985714,0.928571,False

In [120]:
pd.set_option('display.max_rows', 50) # Quita el límite de filas

In [92]:
display(df_final[
    (df_final['excluir_2'] == True)][["Entidad", "similar_2"]])

,Entidad,similar_2
25,theodred ii,theodred i
31,"henry lawes luttrell, 2nd earl of carhampton","simon luttrell, 1st earl of carhampton"
237,rhoemetalces i,rhoemetalces ii
409,flight nh692,boeing 787(flight nh692)
482,1999 cannes film festival,1985 cannes film festival
596,"simon luttrell, 1st earl of carhampton","henry lawes luttrell, 2nd earl of carhampton"
653,9th berlin international film festival,12th berlin international film festival
755,11th berlin international film festival,12th berlin international film festival
768,cotys iii,cotys i
817,cotys vi,cotys i
834,king george v,king george iii of the united kingdom
845,highway 9,highway 2
850,"sir andrew agnew, 2nd baronet","sir andrew agnew, 3rd baronet"
881,boeing 787(flight nh692),flight nh692
911,1996 summer olympics,2016 summer olympics
968,"sir andrew agnew, 3rd baronet","sir andrew agnew, 2nd baronet"
1081,cotys iv,cotys i
1110,1922,"january 5, 1922"
1118,township high school district 211,township high school district 214
1130,census division 17,division 1
1172,39th venice film festival,67th venice international film festival
1236,1985 cannes film festival,1961 cannes film festival
1266,2008 summer olympics,2016 summer olympics
1282,cotys i,cotys viii
1287,tiberius julius rhescuporis ii,tiberius julius rhescuporis iii
1437,cotys vii,cotys i
1447,1969,"june 22, 1969"
1498,"william lamb, 2nd viscount melbourne","peniston lamb, 1st viscount melbourne"
1526,1980 summer olympics,2016 summer olympics
1548,2007 cannes film festival,1985 cannes film festival
1673,boeing 787,boeing 787(flight nh692)
1687,sauromates iii,sauromates ii
1689,"peniston lamb, 1st viscount melbourne","william lamb, 2nd viscount melbourne"
1717,16th lok sabha,17th lok sabha
1720,1954,"november 6, 1954"
1824,1934,"april 4, 1934"
1842,2020 summer olympics,2016 summer olympics
1863,2016 summer olympics,2020 summer olympics
1975,1986 world rowing championships,1992 world championships
2035,67th venice international film festival,38th venice international film festival
2094,1995 cannes film festival,1985 cannes film festival
2104,10 october 2009,11 october 2009
2238,rhoemetalces ii,rhoemetalces i
2377,13th lok sabha,14th lok sabha
2433,1957,2 november 1957
2443,14th lok sabha,17th lok sabha
2465,1951 cannes film festival,1995 cannes film festival
2467,1961 cannes film festival,1995 cannes film festival
2523,38th venice international film festival,67th venice international film festival
2534,tiberius julius rhescuporis iii,tiberius julius rhescuporis iv
2545,3rd moscow international film festival,13th moscow international film festival
2547,1953 cannes film festival,1961 cannes film festival
2563,2002,10 november 2002
2575,8th moscow international film festival,3rd moscow international film festival
2577,1961,"july 2, 1961"
2609,tiberius julius rhescuporis iv,tiberius julius rhescuporis iii
2613,30th international film festival of india,12th moscow international film festival
2650,17th lok sabha,14th lok sabha
2664,13th moscow international film festival,8th moscow international film festival
2689,"july 4, 2014",17 july 2014
2696,1921,9 october 1921
2698,"july 17, 1887",17 july 2014
2699,1915,"april 7, 1915"
2700,9 april 1897,6 october 1897
2703,2001,21 june 2001
2705,2007,7 october 2007
2708,"july 29, 1937","july 3, 1937"
2709,1973,4 january 1973
2711,1962,1 october 1962
2715,1953,8 may 1953
2720,"april 4, 1934",1934
2724,"may 1, 1895",23 november 1895
2725,6 november 1991,1991
2726,"june 2, 1958",1958
2731,1938,"march 21, 1938"
2738,1940,24 december 1940
2740,1965,20 june 1965
2746,1900,"october 16, 1900"
2751,"august 11, 1927","august 3, 1927"
2760,1944,7 september 1944
2764,"november 15, 1961",5 november 1961
2768,3 march 2009,2009
2772,23 november 1982,23 november 1895
2774,"february 8, 1955",1955
2777,1943,9 november 1943
2782,1968,"november 6, 1968"
2791,12 november 1897,"november 13, 1897"
2796,"november 5, 1970",21 november 1970
2799,1 october 1962,1962
2803,1980,"march 8, 1980"
2808,1893,"february 22, 1893"
2812,28 april 1877,"april 28, 2005"
2818,1933,"june 2, 1933"
2825,"august 19, 1997",1997
2831,"march 30, 1990","march 30, 1913"
2842,1974,4 may 1974
2844,"may 11, 1894","april 8, 1894"
2847,"february 22, 1893",1893
2863,24 october 1994,1994
2871,30 september 1988,1988
2874,"april 11, 1916",1916
2884,"september 16, 1918",1918
2885,"june 22, 1969",1969
2888,1996,15 june 1996
2889,23 june 1906,1906
2890,1976,"july 7, 1976"
2891,2011,"february 9, 2011"
2897,1999,5 august 1999
2909,1991,6 november 1991
2914,"january 16, 2013","january 16, 1972"
2915,"october 26, 1941","october 26, 1912"
2916,8 july 1836,"february 3, 1836"
2920,5 february 1943,1943
2926,1929,6 december 1929
2930,1923,"september 1, 1923"
2932,31 july 1914,2 july 1914
2933,"august 24, 1807",24 august 1973
2938,1926,8 august 1926
2946,1919,"june 9, 1919"
2952,30 june 1931,1931
2958,1951,"december 8, 1951"
2962,10 november 2002,2002
2973,"october 26, 1912","october 26, 1941"
2975,8 july 1908,1908
2976,"february 21, 2011","february 9, 2011"
2978,township high school district 214,township high school district 211
2983,4 may 1974,1974
2992,19 february 1990,19 february 1901
2995,1945,31 august 1945
2996,1942,9 august 1942
2997,1987,16 october 1987
3004,4 september 1887,"july 17, 1887"
3006,"march 3, 1981",1981
3011,16 june 2017,2017
3014,1972,"march 3, 1972"
3018,1959,"april 9, 1959"
3019,2009,3 march 2009
3022,"july 16, 1906","july 16, 2012"
3024,14 march 1918,"march 23, 1918"
3027,23 january 1974,17 january 1974
3028,1950,10 july 1950
3029,"december 8, 1951",1951
3042,10 april 1911,1911
3045,14 december 1985,"december 14, 1949"
3059,10 april 1912,1912
3063,1952,2 november 1952
3064,16 october 1987,1987
3066,2005,3 march 2005
3070,1993,"june 9, 1993"
3071,11 october 2009,10 october 2009
3072,2013,"february 1, 2013"
3073,10 august 1960,1960
3074,2006,"may 5, 2006"
3087,1995,"december 4, 1995"
3088,4 november 1992,1992
3115,"july 31, 1926",31 july 1914
3118,10 march 1904,1904
3122,"february 10, 1967",1967
3125,16 may 1921,1921
3131,1947,23 january 1947
3133,"september 2, 1802",7 september 1925
3137,1998,3 april 1998
3139,"july 7, 1976",1976
3140,"february 16, 2001",2001
3144,15 july 1995,"july 15, 1979"
3148,1927,7 june 1927
3150,1946,13 june 1946
3152,"november 6, 1954",24 november 1954
3166,1939,"september 26, 1939"
3167,1905,30 september 1905
3168,25 december 1945,1945
3171,14 september 1975,14 september 1910
3172,9 june 1962,1962
3175,6 november 1956,1956
3178,1997,"august 19, 1997"
3180,1960,6 november 1960
3184,1920,8 march 1920
3185,2018,7 may 2018
3191,28 september 1837,28 september 1832
3194,9 november 1943,1943
3196,1971,6 august 1971
3200,1928,"august 1, 1928"
3202,1981,"march 3, 1981"
3212,"march 26, 1952",1952
3213,14 october 1927,1927
3215,31 may 1999,22 may 1999
3216,"june 13th, 1922","june 10, 1922"
3221,"february 3, 2012",2012
3239,1985,14 december 1985
3241,2 november 1952,1952
3242,31 may 2016,31 may 1999
3246,1979,15 december 1979
3248,"november 10, 1914",1914
3249,29 may 1971,1971
3250,8 august 1926,1926
3255,"april 8, 1894",12 november 1894
3259,21 october 2012,21 october 1946
3269,"october 22, 1951","october 22, 1970"
3271,"february 15, 1958",1958
3275,27 october 1888,"may 8, 1888"
3276,"may 16, 1982",16 may 1872
3282,19 june 1999,"june 19, 1905"
3284,4 october 1973,1973
3286,"february 24, 1880",25 january 1880
3288,1937,"july 3, 1937"
3295,"april 9, 1959",1959
3303,1989,"june 12, 1989"
3304,9 august 1942,1942
3315,5 february 1917,1917
3316,22 june 2002,2002
3319,1912,"october 26, 1912"
3322,1975,"july 3, 1975"
3323,2015,18 september 2015
3327,25 june 1923,25 june 2019
3328,"february 19, 1877",19 february 1901
3343,11 august 2005,"august 11, 1927"
3345,"august 10, 1896","august 10, 1982"
3346,1982,"january 4, 1982"
3355,15 august 1981,1981
3356,24 july 1881,24 july 1931
3359,"june 2, 2006","june 18, 2006"
3361,12 february 1962,12 february 1953
3365,1964,25 june 1964
3367,19 may 2019,2019
3369,1930,"july 10, 1930"
3371,11 january 1928,11 january 1995
3373,28 january 1993,28 january 1951
3376,sauromates ii,sauromates iii
3379,2019,25 june 2019
3380,9 october 1921,1921
3386,"august 8, 1921",1921
3387,"may 1, 1891","may 9, 1943"
3390,26 august 1968,"august 26, 1894"
3392,1913,"august 16, 1913"
3396,2014,"july 4, 2014"
3397,17 july 1936,2 july 1936
3398,1910,6 november 1910
3405,29 october 2004,2004
3408,2012,"february 3, 2012"
3411,1958,"june 2, 1958"
3413,1941,"october 26, 1941"
3414,"april 22, 1868",lyon cohen(1868–1937)
3421,1898,"august 5, 1898"
3423,2003,15 july 2003
3424,1956,6 november 1956
3425,25 november 2008,"november 25, 1917"
3426,15 june 1996,1996
3432,2004,2 november 2004
3438,"march 30, 1913",1913
3442,28 may 1901,19 february 1901
3448,1949,"april 5, 1949"
3449,"march 21, 1938",1938
3458,"april 25, 1961",25 april 1821
3461,5 january 1906,1906
3466,6 may 1993,1993
3467,"june 18, 2006","june 2, 2006"
3468,1936,2 july 1936
3469,21 august 1813,21
3471,"august 22, 1954",1954
3473,"december 15, 2010",2010
3474,2 november 1957,1957
3479,"april 10, 1886",10 april 1911
3480,5 november 1961,"november 15, 1961"
3481,"august 17, 1977","august 16, 1977"
3486,1988,"february 1, 1988"
3489,"december 13, 1903",1903
3492,25 june 1964,"june 18, 1964"
3500,7 september 1925,1925
3508,1986,9 october 1986
3514,"july 13, 1884","april 13, 1954"
3520,1903,"october 3, 1903"
3521,"april 7, 1915",1915
3533,"september 21, 1961",21 september 1952
3536,"february 1, 2013",2013
3546,"january 8, 1935",1935
3550,28 january 1951,28 january 1993
3553,1917,5 february 1917
3554,2 february 1886,"february 11, 1886"
3556,"may 23, 1941",1941
3558,27 september 1985,27 september 1932
3559,7 december 1871,1 december 1968
3561,"january 4, 1982",1982
3562,"november 3, 1951",1951
3564,23 january 1947,1947
3565,"july 24, 1904",1904
3568,"april 1, 1580","april 5, 1949"
3575,"march 8, 1980",1980
3577,"september 1, 1923","september 11, 1923"
3580,"july 25, 1935",1935
3585,30 december 1894,"december 30, 1922"
3586,1994,25 august 1994
3588,14 december 1946,14 december 1985
3589,23 november 1895,23 november 1982
3591,1932,4 december 1932
3593,28 june 1895,28 june 2013
3597,"june 19, 1905",1905
3598,2010,"december 15, 2010"
3604,"february 1, 1988",1988
3606,"december 23, 1919",26 december 1919
3610,5 september 1875,7 september 1925
3612,"october 11, 1952",11 october 2009
3619,"december 19, 2018","december 19, 1944"
3620,"july 16, 2012","july 16, 1906"
3624,"april 20, 1991",1991
3626,1925,3 january 1925
3628,13 june 1946,1946
3629,10 may 1992,"may 10, 1940"
3640,1970,"november 5, 1970"
3642,1931,24 july 1931
3646,"march 14, 2014",14 march 1918
3647,"december 19, 1944","december 19, 2018"
3652,8 february 1772,"february 1, 1988"
3653,1935,"january 8, 1935"
3654,17 november 1906,1906
3657,1916,"january 4, 1916"
3664,"september 4, 1942",1942
3665,9 may 1942,23 may 1942
3666,1977,"august 17, 1977"
3683,21,21 october 1946
3684,1955,"february 8, 1955"
3686,"may 18, 1924",1924
3690,1914,2 july 1914
3695,28 december 1906,28 december 1808
3698,29 january 1745,7 november 1745
3712,1918,6 may 1918
3715,"may 5, 2006",2006
3716,"february 25, 1944",1944
3717,9 july 1956,1956
3721,"may 8th, 2008",2008
3731,3 april 1998,1998
3737,7 september 1944,1944
3739,25 september 1914,25 september 1922
3740,29 march 1902,1902
3746,7 october 2007,2007
3757,27 december 1680,27 october 1888
3758,8 march 1920,1920
3761,"july 22, 1869",22 july 1828
3765,"june 19, 1981",19 june 1999
3769,"december 11, 1958",1958
3772,"august 26, 1894",26 august 1968
3790,30 april 2016,30 april 1947
3791,"july 31, 1907",1907
3792,"january 21, 1992",1992
3796,"november 13, 1897",12 november 1897
3806,3 january 1925,1925
3815,"october 16, 1900",1900
3817,"august 7, 1963",1963
3822,5 january 1973,4 january 1973
3824,7 march 1942,1942
3825,22 march 1956,1956
3830,23 may 1950,1950
3834,"december 4, 1995",1995
3837,1 october 1976,1976
3844,1907,"july 31, 1907"
3854,"july 12, 2015",2015
3855,"may 19, 1953",8 may 1953
3857,9 february 1960,1960
3864,"march 3, 1972",1972
3869,7 november 1745,29 january 1745
3870,"may 17, 1985",1985
3882,24 december 2005,24 december 1940
3887,15 july 2003,2003
3892,"august 14, 1899",1899
3899,"november 9, 1899",1899
3906,14 february 1950,1950
3908,"april 13, 1954",1954
3917,"may 13, 2000",2000
3918,"december 14, 1949",1949
3927,18 december 1881,24 july 1881
3932,5 march 1934,1934
3934,"august 16, 1977","august 17, 1977"
3935,4 december 1932,1932
3936,24 january 1743,7 august 1743
3946,22 november 1981,12 november 1981
3947,19 july 1983,27 january 1983
3952,"july 30, 1972",1972
3957,1967,"february 10, 1967"
3959,25 april 1821,"april 25, 1961"
3961,"june 30, 1968",1968
3967,28 december 1808,28 december 1906
3978,20 august 1961,10 august 1961
3989,17 january 1974,23 january 1974
3991,17 august 1946,"august 17, 1977"
3996,"june 30, 1964",25 june 1964
4001,"february 11, 1886",2 february 1886
4006,"august 20, 1860",20 august 1961
4008,30 may 1769,30
4014,27 june 1989,"june 12, 1989"
4017,"november 11, 1879",9 november 1943
4024,1908,8 july 1908
4027,"september 24, 1865","september 24, 1937"
4028,2 november 1962,1962
4029,12 february 1953,12 february 1962
4033,"january 12, 1945","january 12, 1976"
4035,18 september 1790,18 september 1882
4048,"july 17, 1959",1959
4061,"june 2, 1933",1933
4062,21 june 2001,2001
4068,27 july 1765,27 october 1888
4074,16 november 1743,"november 16, 1927"
4078,12 november 1894,12 november 1981
4085,19 february 1901,"february 19, 1877"
4087,"september 11, 1957",1957
4091,"july 3, 1975",1975
4105,"july 3, 1937","july 29, 1937"
4111,"july 10, 1930",1930
4113,8 may 1953,"may 19, 1953"
4115,28 september 1832,28 september 1837
4121,"december 17, 2017",17 december 1989
4140,1 september 1981,1981
4143,25 may 2018,7 may 2018
4152,18 september 1882,18 september 1790
4155,1902,29 march 1902
4160,"february 7, 1972",1972
4169,21 november 1970,"november 5, 1970"
4174,6 november 1910,1910
4176,"january 17, 1878",17 january 1974
4177,24 november 1954,"november 6, 1954"
4189,"september 26, 1939",1939
4190,cotys viii,cotys i
4193,"may 14, 2005",2005
4195,20 september 1969,23 september 1969
4199,23 may 1942,9 may 1942
4206,27 september 1932,27 september 1985
4207,20 may 1975,1975
4208,"july 31, 1981","july 31, 1926"
4216,30 april 1947,1947
4218,"november 7, 1926",1926
4222,"february 9, 2011","february 21, 2011"
4224,12 july 1946,"july 12, 2015"
4225,"november 20, 1993",1993
4229,3 july 1746,8 july 1908
4233,"august 16, 1913",1913
4234,27 january 1983,28 october 1983
4235,27 april 1980,1980
4237,7 june 1927,1927
4240,29 april 1995,1995
4242,"july 2, 1961",1961
4243,8 march 1962,"march 23, 1962"
4245,"october 20, 2017",2017
4246,22 july 1828,"july 22, 1869"
4248,21 march 1994,"march 21, 1938"
4254,"april 5, 1949",1949
4258,"june 2, 1970",1970
4260,"november 16, 1927",16 november 1743
4262,"september 24, 1937",24 september 1982
4268,20 june 1990,20 june 1965
4270,1924,"may 18, 1924"
4272,"october 3, 1903",1903
4274,"march 23, 1962",8 march 1962
4278,20 september 1984,20 september 1969
4287,1904,10 march 1904
4293,"january 4, 1916",1916
4297,"june 2, 1992",1992
4298,"24 april, 1990",1990
4301,11 january 1995,11 january 1928
4302,"may 9, 1943",1943
4311,9 october 1986,1986
4313,"december 30, 1922",30 december 1894
4315,6 december 1929,1929
4323,18 september 2015,18 september 1882
4327,"august 10, 1982","august 10, 1896"
4330,"june 12, 1989",27 june 1989
4339,6 november 1960,22 november 1960
4340,21 september 1952,"september 21, 1961"
4348,"june 10, 1974","june 10, 1922"
4353,3 march 2005,2005
4374,8 july 1863,8 july 1908
4375,24 september 1982,"september 24, 1937"
4377,23 february 1986,1986
4380,1 december 1968,1968
4391,"october 12, 1970","october 22, 1970"
4393,"july 9, 1933",1933
4395,23 february 1935,23 february 1986
4396,16 may 1872,16 may 1921
4400,19 august 1995,"august 19, 1997"
4403,"november 28, 1929",1929
4411,"november 6, 1968",1968
4417,"august 16, 1958","august 16, 1913"
4419,17 december 1989,"december 17, 2017"
4420,7 september 1955,1955
4428,2 october 1944,1944
4434,"january 5, 1933",1933
4435,22 november 1960,6 november 1960
4438,"may 22, 1989","may 22, 1970"
4445,14 september 1910,1910
4446,6 october 1897,9 april 1897
4451,6 august 1971,"august 8, 1971"
4452,"april 28, 2005",28 april 1877
4458,"july 29, 2000","july 29, 1937"
4459,2 july 1914,31 july 1914
4461,25 august 1994,1994
4478,25 september 1922,25 september 1914
4489,"january 16, 1972","january 16, 2013"
4491,"july 21, 1984",21
4493,11 july 1784,"april 11, 1916"
4504,30 october 1971,"october 6, 1971"
4505,24 august 1973,"august 24, 1807"
4509,24 july 1931,1931
4520,6 june 1845,9 june 1962
4521,"november 28, 1919","november 28, 1929"
4525,10 july 1950,1950
4526,"january 5, 1922",1922
4533,31 august 1945,1945
4542,1990,"august 4, 1990"
4543,"may 2, 1911",1911
4545,"august 4, 1990",1990
4549,"august 5, 1898",1898
4550,"october 23, 1766",1 october 1962
4552,"august 3, 1927","august 11, 1927"
4568,28 october 1983,27 january 1983
4575,"february 11, 1908",1908
4581,5 october 1791,"october 3, 1903"
4591,26 december 1897,26 december 1919
4607,7 may 2018,25 may 2018
4618,22 may 1999,31 may 1999
4621,10 august 1961,20 august 1961
4627,1992,4 november 1992
4629,1911,"may 2, 1911"
4634,"june 4, 1973",1973
4639,"june 10, 1922","june 13th, 1922"
4643,1906,5 january 1906
4651,"september 11, 1923","september 1, 1923"
4653,30 september 1905,1905
4658,2 july 1936,17 july 1936
4659,1899,"november 9, 1899"
4660,15 november 2012,"november 15, 1961"
4666,29 june 2012,2012
4673,2 november 2004,2004
4679,24 december 1940,14 december 1940
4682,23 september 1969,20 september 1969
4683,26 december 1919,"december 23, 1919"
4689,6 may 1918,1918
4693,14 december 1940,24 december 1940
4695,"november 28, 2009",2009
4696,24 october 1775,24 october 1994
4697,"march 23, 1918",14 march 1918
4698,"june 18, 1964",25 june 1964
4709,"february 6, 2007",2007
4714,"november 25, 1917",1917
4716,"august 1, 1928",1928
4717,"october 17, 1939",1939
4720,5 august 1999,1999
4725,"february 3, 1836",8 july 1836
4726,21 october 1946,21 october 2012
4730,"january 12, 1976","january 12, 1945"
4739,12 november 1981,22 november 1981
4741,17 july 2014,"july 4, 2014"
4744,7 august 1743,16 november 1743
4747,25 january 1880,"february 24, 1880"
4748,22 december 1928,1928
4751,"june 9, 1993",1993
4757,25 december 1901,"december 25, 2019"
4763,"june 9, 1919","june 8, 1919"
4767,20 june 1965,1965
4778,2 january 1834,"january 4, 1916"
4782,"october 6, 1971",30 october 1971

# Excluir cambios con terminos poco frecuentes

NO FUNCIONA .+- SON CASI TODOS POCO FRECUENTES

In [154]:
from sklearn.feature_extraction.text import TfidfVectorizer


coleccion = [
    "procesador memoria_ram tarjeta_grafica",
    "procesador memoria_ram disco_duro fuente_poder",
    "procesador memoria_ram",
    "procesador placa_base refrigeracion_liquida",
]

# 2. Inicializamos el vectorizador
# Usamos token_pattern para que acepte guiones bajos si tus entidades los tienen
vectorizer = TfidfVectorizer(stop_words="english")

In [155]:

# 3. Ajustamos el modelo a los datos
tfidf_matrix = vectorizer.fit_transform(entidades)

In [156]:
entidades_vectorizer = vectorizer.get_feature_names_out()
valores_idf = vectorizer.idf_

In [157]:
entidades_vectorizer

array(['10', '100', '11', ..., 'šlomović', 'žižek', '濰水之戰'],
      shape=(4786,), dtype=object)

In [158]:
valores_idf

array([6.39754548, 8.38997565, 6.65537459, ..., 8.79544075, 8.79544075,
       8.79544075], shape=(4786,))

In [160]:
idf_df = pd.DataFrame()

In [ ]:
data=[entidades_vectorizer, valores_idf], columns=['entidades', 'idf']

In [161]:
idf_df['entidades'] = entidades_vectorizer
idf_df['idf'] = valores_idf

In [ ]:
idf_df[idf_df['entidades'] == '']

In [162]:
idf_df

     entidades       idf
0           10  6.397545
1          100  8.389976
2           11  6.655375
3         11th  8.795441
4           12  7.003681
...        ...       ...
4781     élise  8.389976
4782      łódź  8.795441
4783  šlomović  8.795441
4784     žižek  8.795441
4785      濰水之戰  8.795441

[4786 rows x 2 columns]

# EXCLUIR CUANDO SOLO CAMBIE 1 PALABRA Y SEA UN NOMNRE PROPIO, CIUDAD...

In [ ]:
# Cargamos el modelo ligero en inglés
nlp = spacy.load("en_core_web_sm")

In [ ]:
def es_falso_positivo_por_nombre(fila):
    
    if len(fila['Entidad'].strip()) == len(fila['similar_2'].strip()):
        doc1 = nlp(fila['Entidad'])
        doc2 = nlp(fila['similar_2'])
        
        ents_dict1 = {ent.text: ent.label_ for ent in doc1.ents}
        ents_dict2 = {ent.text: ent.label_ for ent in doc2.ents}

        palabras_str1 = {ent.text for ent in doc1.ents}
        palabras_str2 = {ent.text for ent in doc2.ents}

        diferencias = palabras_str1.symmetric_difference(palabras_str2)
        labels_excluir = ["PERSON", "GPE"]

        for palabra_dif in diferencias:
            label_1 = ents_dict1.get(palabra_dif)
            label_2 = ents_dict2.get(palabra_dif)
            if label_1 in labels_excluir or label_2 in labels_excluir:
                return True

    return False

In [270]:
df_final['excluir_por_nombre_propio'] = df_final.apply(es_falso_positivo_por_nombre, axis=1)

In [187]:
df_final_excluidos_nombres = df_final[df_final['excluir_por_nombre_propio'] == True]

In [271]:
df_final_excluidos_nombres = df_final[
    (df_final['dist_jaro_2'].between(0.7, 0.999)) &
    (df_final['dist_leven_2'].between(0.7, 0.999)) &
    (df_final['score_2'] > 5) &
    (df_final['excluir_por_nombre_propio'] == True)
    ][cols_].sort_values('score_2', ascending = False)

In [272]:
df_final_excluidos_nombres

,Entidad,similar_1,score_1,score_1_inv,dist_jaro_1,dist_leven_1,similar_2,score_2,score_2_inv,dist_jaro_2,dist_leven_2,excluir_2
1744,roman catholic archdiocese of boston,roman catholic archdiocese of boston,7.995131,7.995131,1.0,1.0,roman catholic archdiocese of newark,5.883300,5.883300,0.944444,0.833333,False
2618,roman catholic archdiocese of newark,roman catholic archdiocese of newark,8.242422,8.242422,1.0,1.0,roman catholic archdiocese of boston,5.883300,5.883300,0.944444,0.833333,False
1325,12th moscow international film festival,12th moscow international film festival,7.178578,7.178578,1.0,1.0,12th berlin international film festival,5.498832,5.498832,0.859674,0.846154,False
2206,12th berlin international film festival,12th berlin international film festival,7.178578,7.178578,1.0,1.0,12th moscow international film festival,5.498832,5.498832,0.859674,0.846154,False
755,11th berlin international film festival,11th berlin international film festival,7.308257,7.308257,1.0,1.0,12th berlin international film festival,5.256265,5.256265,0.984615,0.974359,True
2575,8th moscow international film festival,8th moscow international film festival,6.978419,6.978419,1.0,1.0,3rd moscow international film festival,5.256265,5.256265,0.861654,0.921053,True
2306,beshr ibn hasan,beshr ibn hasan,6.678320,6.678320,1.0,1.0,hasan ibn hasan,5.109236,6.185756,0.700000,0.733333,False

# Calculo completo

In [197]:
def tokenize(text):
    return text.lower().replace(".", "").replace(",", "").replace("'", "").replace("  ", " ").split()

In [198]:
def calcular_rank_B25s(entidades):
   entidades_token = bm25s.tokenize(entidades, stopwords="en")
   retriever = bm25s.BM25()
   retriever.index(entidades_token)
   results, scores = retriever.retrieve(entidades_token, k=3)
   df_resultados = pd.DataFrame(data=results, columns=["similar_1", "similar_2", "similar_3"])
   df_scores = pd.DataFrame(scores, columns=["score_1", "score_2", "score_3"])
   df_resultados = df_resultados.map(lambda x: entidades[x])
   df_final = pd.concat([df_resultados, df_scores], axis=1)
   df_final['Entidad'] = entidades
   cols_reorder = ["Entidad", "similar_1", "score_1", "similar_2", "score_2", "similar_3", "score_3"]
   df_final = df_final[cols_reorder]
   return df_final

In [199]:
# def calcular_score_inverso(fila, retriever, entidades):

#     similares = [fila['similar_1'], fila['similar_2'], fila['similar_3']]
#     similares_tokenized = bm25s.tokenize(similares)

#     resultados, scores = retriever.retrieve(similares_tokenized, k=20)
    
#     idx_entidad = entidades.index(fila['Entidad'])

#     scores_inv = []
#     for i, res in enumerate(resultados):
#         if idx_entidad in res:
#             idx_entidad_resultado = res.tolist().index(idx_entidad)
#             score = scores[i][idx_entidad_resultado]
#             scores_inv.append(score)
#         else:
#             scores_inv.append(0)

#     return scores_inv[0], scores_inv[1], scores_inv[2]

In [200]:
# def get_spacy_docs(fila):
    
#     nlp = spacy.load("en_core_web_sm")
#     doc_ent = nlp(fila['Entidad'])
#     doc_sim_1 = nlp(fila['similar_1'])
#     doc_sim_2 = nlp(fila['similar_2'])
#     doc_sim_3 = nlp(fila['similar_3'])
#     return doc_ent, doc_sim_1, doc_sim_2, doc_sim_3
""""
TARDA MUCHO Y PETA LA MEMORIA - IMPOSIBLE GUARDAR OBJETOS DE SPACY EN COLUMNAS DE PANDAS
"""

'"\nTARDA MUCHO Y PETA LA MEMORIA - IMPOSIBLE GUARDAR OBJETOS DE SPACY EN COLUMNAS DE PANDAS\n'

In [201]:
def calcular_jaro_winkler(fila):
    # dist_jaro_1 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_1'])
    # dist_jaro_2 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_2'])
    # dist_jaro_3 = textdistance.jaro_winkler(fila['Entidad'], fila['similar_3'])
    
    doc_ent = nlp(fila['Entidad'])
    doc_sim_1 = nlp(fila['similar_1'])
    doc_sim_2 = nlp(fila['similar_2'])
    doc_sim_3 = nlp(fila['similar_3'])
    
    ent_sw_removed = " ".join([token.text for token in doc_ent if not token.is_stop and not token.is_punct])
    sim_1_sw_removed = " ".join([token.text for token in doc_sim_1 if not token.is_stop and not token.is_punct])
    sim_2_sw_removed = " ".join([token.text for token in doc_sim_2 if not token.is_stop and not token.is_punct])
    sim_3_sw_removed = " ".join([token.text for token in doc_sim_3 if not token.is_stop and not token.is_punct])
    
    dist_jaro_1 = textdistance.jaro_winkler(ent_sw_removed, sim_1_sw_removed)
    dist_jaro_2 = textdistance.jaro_winkler(ent_sw_removed, sim_2_sw_removed)
    dist_jaro_3 = textdistance.jaro_winkler(ent_sw_removed, sim_3_sw_removed)
    return dist_jaro_1, dist_jaro_2, dist_jaro_3

In [202]:
def calcular_levenshtein(fila):
    # dist_leven_1 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_1'])
    # dist_leven_2 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_2'])
    # dist_leven_3 = textdistance.levenshtein.normalized_similarity(fila['Entidad'], fila['similar_3'])
    
    doc_ent = nlp(fila['Entidad'])
    doc_sim_1 = nlp(fila['similar_1'])
    doc_sim_2 = nlp(fila['similar_2'])
    doc_sim_3 = nlp(fila['similar_3'])
    
    ent_sw_removed = " ".join([token.text for token in doc_ent if not token.is_stop and not token.is_punct])
    sim_1_sw_removed = " ".join([token.text for token in doc_sim_1 if not token.is_stop and not token.is_punct])
    sim_2_sw_removed = " ".join([token.text for token in doc_sim_2 if not token.is_stop and not token.is_punct])
    sim_3_sw_removed = " ".join([token.text for token in doc_sim_3 if not token.is_stop and not token.is_punct])
    
    dist_leven_1 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_leven_2 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_leven_3 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_3_sw_removed)
    
    return dist_leven_1, dist_leven_2, dist_leven_3

In [203]:
def calcular_jaccard(fila):
    
    # Filtrar stop words y puntuacion
    doc_ent = nlp(fila['Entidad'])
    doc_sim_1 = nlp(fila['similar_1'])
    doc_sim_2 = nlp(fila['similar_2'])
    doc_sim_3 = nlp(fila['similar_3'])
    
    ent_sw_removed = [token.text for token in doc_ent if not token.is_stop and not token.is_punct]
    sim_1_sw_removed = [token.text for token in doc_sim_1 if not token.is_stop and not token.is_punct]
    sim_2_sw_removed = [token.text for token in doc_sim_2 if not token.is_stop and not token.is_punct]
    sim_3_sw_removed = [token.text for token in doc_sim_3 if not token.is_stop and not token.is_punct]
    
    
    dist_jaccard_1 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_jaccard_2 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_jaccard_3 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_3_sw_removed)
    
    return dist_jaccard_1, dist_jaccard_2, dist_jaccard_3

In [204]:
def calcular_overlap(fila):

    doc_ent = nlp(fila['Entidad'])
    doc_sim_1 = nlp(fila['similar_1'])
    doc_sim_2 = nlp(fila['similar_2'])
    doc_sim_3 = nlp(fila['similar_3'])
    
    ent_sw_removed = [token.text for token in doc_ent if not token.is_stop and not token.is_punct]
    sim_1_sw_removed = [token.text for token in doc_sim_1 if not token.is_stop and not token.is_punct]
    sim_2_sw_removed = [token.text for token in doc_sim_2 if not token.is_stop and not token.is_punct]
    sim_3_sw_removed = [token.text for token in doc_sim_3 if not token.is_stop and not token.is_punct]
    
    dist_overlap_1 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_overlap_2 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_overlap_3 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_3_sw_removed)
    
    return dist_overlap_1, dist_overlap_2, dist_overlap_3

In [205]:
def calcular_distancias(fila):
    doc_ent = nlp(fila['Entidad'])
    doc_sim_1 = nlp(fila['similar_1'])
    doc_sim_2 = nlp(fila['similar_2'])
    doc_sim_3 = nlp(fila['similar_3'])
    
    ent_sw_removed = " ".join([token.text for token in doc_ent if not token.is_stop and not token.is_punct])
    sim_1_sw_removed = " ".join([token.text for token in doc_sim_1 if not token.is_stop and not token.is_punct])
    sim_2_sw_removed = " ".join([token.text for token in doc_sim_2 if not token.is_stop and not token.is_punct])
    sim_3_sw_removed = " ".join([token.text for token in doc_sim_3 if not token.is_stop and not token.is_punct])
    
    dist_jaro_1 = textdistance.jaro_winkler(ent_sw_removed, sim_1_sw_removed)
    dist_jaro_2 = textdistance.jaro_winkler(ent_sw_removed, sim_2_sw_removed)
    dist_jaro_3 = textdistance.jaro_winkler(ent_sw_removed, sim_3_sw_removed)

    dist_leven_1 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_leven_2 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_leven_3 = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_3_sw_removed)

    dist_jaccard_1 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_jaccard_2 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_jaccard_3 = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_3_sw_removed)

    dist_overlap_1 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_1_sw_removed)
    dist_overlap_2 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_2_sw_removed)
    dist_overlap_3 = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_3_sw_removed)
    
    return dist_jaro_1, dist_jaro_2, dist_jaro_3, dist_leven_1, dist_leven_2, dist_leven_3, dist_jaccard_1, dist_jaccard_2, dist_jaccard_3, dist_overlap_1, dist_overlap_2, dist_overlap_3

In [206]:
def excluir_por_numeros(fila):
    excluir_1 = False
    excluir_2 = False
    excluir_3 = False
    
    regex_romanos = r'\b(v[ii]{0,3}|i[vx]|x[lcvi]{0,4}|i{1,3})\b'
    
    romanos_e = set(re.findall(regex_romanos, fila['Entidad']))
    romanos_1 = set(re.findall(regex_romanos, fila['similar_1']))
    romanos_2 = set(re.findall(regex_romanos, fila['similar_2']))
    romanos_3 = set(re.findall(regex_romanos, fila['similar_3']))
    
    if romanos_e and romanos_1 and romanos_e != romanos_1:
        excluir_1 = True
    if romanos_e and romanos_2 and romanos_e != romanos_2:
        excluir_2 = True
    if romanos_e and romanos_3 and romanos_e != romanos_3:
        excluir_3 = True
    
    regex_numeros = r'\d+'
    numeros_e = set(re.findall(regex_numeros, fila['Entidad']))
    numeros_1 = set(re.findall(regex_numeros, fila['similar_1']))
    numeros_2 = set(re.findall(regex_numeros, fila['similar_2']))
    numeros_3 = set(re.findall(regex_numeros, fila['similar_3']))

    if numeros_e != numeros_1:
        excluir_1 = True
    if numeros_e != numeros_2:
        excluir_2 = True
    if numeros_e != numeros_3:
        excluir_3 = True
    
    return excluir_1, excluir_2, excluir_3

In [207]:
def excluir_por_nombre(fila):
    
    doc_ent = nlp(fila['Entidad'])
    ents_ent = {ent.text: ent.label_ for ent in doc_ent.ents}
    palabras_ent = {ent.text for ent in doc_ent.ents}
    labels_excluir = ["PERSON", "GPE", "ORG"]
    
    exclusion = [False, False, False]
    
    for i in range(1,4):
        if len(fila['Entidad'].split()) == len(fila[f'similar_{i}'].split()):

            doc_sim = nlp(fila[f'similar_{i}'])
            ents_sim = {ent.text: ent.label_ for ent in doc_sim.ents}
            palabras_sim = {ent.text for ent in doc_sim.ents}
            
            diferencias = palabras_ent.symmetric_difference(palabras_sim)

            for palabra_dif in diferencias:
                label_e = ents_ent.get(palabra_dif)
                label_sim = ents_sim.get(palabra_dif)
                if label_e in labels_excluir or label_sim in labels_excluir:
                    exclusion[i-1] = True

    return exclusion

In [208]:
nlp = spacy.load("en_core_web_sm")

In [209]:
database_Neo = "2wiki.prueba.rebel.4"
conn_Neo4j = ConexionNeo4j(database_Neo)

In [210]:
entidades = conn_Neo4j.extraer_all_entidades_neo4j()
len(entidades)

6258

In [211]:
df_final = calcular_rank_B25s(entidades)

In [212]:
df_final['entidad_similar_1_iguales'] = False
df_final['entidad_similar_2_iguales'] = False
df_final['entidad_similar_3_iguales'] = False
df_final.loc[df_final['Entidad'] == df_final['similar_1'], 'entidad_similar_1_iguales'] = True
df_final.loc[df_final['Entidad'] == df_final['similar_2'], 'entidad_similar_2_iguales'] = True
df_final.loc[df_final['Entidad'] == df_final['similar_3'], 'entidad_similar_3_iguales'] = True

In [213]:
# df_final[['score_1_inv', 'score_2_inv', 'score_3_inv']] = df_final.apply(calcular_score_inverso, args = (retriever, entidades), axis=1, result_type='expand')

In [214]:
# df_final[['doc_spacy_ent', 'doc_spacy_1', 'doc_spacy_2', 'doc_spacy_3']] = df_final.apply(get_spacy_docs, axis = 1, result_type='expand')

In [215]:
# df_final[['dist_jaro_1', 'dist_jaro_2', 'dist_jaro_3']] = df_final.apply(calcular_jaro_winkler, axis = 1, result_type='expand')

In [216]:
# df_final[['dist_leven_1', 'dist_leven_2', 'dist_leven_3']] = df_final.apply(calcular_levenshtein, axis = 1, result_type='expand')

In [217]:
# df_final[['dist_jaccard_1', 'dist_jaccard_2', 'dist_jaccard_3']] = df_final.apply(calcular_jaccard, axis = 1, result_type='expand')

In [218]:
# df_final[['dist_overlap_1', 'dist_overlap_2', 'dist_overlap_3']] = df_final.apply(calcular_overlap, axis = 1, result_type='expand')

In [219]:
df_final[['dist_jaro_1', 'dist_jaro_2', 'dist_jaro_3', 'dist_leven_1', 'dist_leven_2', 'dist_leven_3', 'dist_jaccard_1', 'dist_jaccard_2', 'dist_jaccard_3', 'dist_overlap_1', 'dist_overlap_2', 'dist_overlap_3']] = df_final.apply(calcular_distancias, axis = 1, result_type='expand')

In [220]:
df_final[['excluir_num_1', 'excluir_num_2', 'excluir_num_3']] = df_final.apply(excluir_por_numeros, axis = 1, result_type='expand')

In [221]:
df_final[['excluir_nom_1', 'excluir_nom_2', 'excluir_nom_3']] = df_final.apply(excluir_por_nombre, axis = 1, result_type='expand')

In [222]:
# df_final['excluir_por_nombre_propio'] = df_final.apply(es_falso_positivo_por_nombre, axis=1)

# Filtros de fusion

In [223]:
df_final['fusion_1'] = False
df_final['fusion_2'] = False
df_final['fusion_3'] = False

## Filtro 1

In [224]:
filtro_1_1 = (
    (
        (
            (df_final['dist_jaro_1'].between(0.8, 0.999)) & (df_final['dist_leven_1'].between(0.75, 0.999))
            ) |
        (
            (df_final['dist_jaro_1'].between(0.9, 0.999)) & (df_final['dist_leven_1'].between(0.71, 0.999))
            )
        ) &
    (df_final['score_1'] > 4.5) &
    (df_final['excluir_num_1'] == False) &
    (df_final['excluir_nom_1'] == False) &
    (df_final['entidad_similar_1_iguales'] == False)
    )

In [225]:
filtro_1_2 = (
    (
        (
            (df_final['dist_jaro_2'].between(0.8, 0.999)) & (df_final['dist_leven_2'].between(0.75, 0.999))
            ) |
        (
            (df_final['dist_jaro_2'].between(0.9, 0.999)) & (df_final['dist_leven_2'].between(0.71, 0.999))
            )
        ) &
    (df_final['score_2'] > 4.5) &
    (df_final['excluir_num_2'] == False) &
    (df_final['excluir_nom_2'] == False) &
    (df_final['entidad_similar_2_iguales'] == False)
    )

In [226]:
filtro_1_3 = (
    (
        (
            (df_final['dist_jaro_3'].between(0.8, 0.999)) & (df_final['dist_leven_3'].between(0.75, 0.999))
            ) |
        (
            (df_final['dist_jaro_3'].between(0.9, 0.999)) & (df_final['dist_leven_3'].between(0.71, 0.999))
            )
        ) &
    (df_final['score_3'] > 4.5) &
    (df_final['excluir_num_3'] == False) &
    (df_final['excluir_nom_3'] == False) &
    (df_final['entidad_similar_3_iguales'] == False)
    )

In [227]:
df_final.loc[filtro_1_1, 'fusion_1'] = True
df_final.loc[filtro_1_2, 'fusion_2'] = True
df_final.loc[filtro_1_3, 'fusion_3'] = True

## Filtro 2

In [228]:
filtro_2_1 = (
    (df_final['dist_jaro_1'].between(0.9, 0.999)) &
    (df_final['dist_leven_1'].between(0.8, 0.999)) &
    (df_final['score_1'] > 1) &
    (df_final['excluir_num_1'] == False) &
    (df_final['excluir_nom_1'] == False) &
    (df_final['entidad_similar_1_iguales'] == False)
    )

In [229]:
filtro_2_2 = (
    (df_final['dist_jaro_2'].between(0.9, 0.999)) &
    (df_final['dist_leven_2'].between(0.8, 0.999)) &
    (df_final['score_2'] > 2) &
    (df_final['excluir_num_2'] == False) &
    (df_final['excluir_nom_2'] == False) &
    (df_final['entidad_similar_2_iguales'] == False)
    )

In [230]:
filtro_2_3 = (
    (df_final['dist_jaro_3'].between(0.9, 0.999)) &
    (df_final['dist_leven_3'].between(0.8, 0.999)) &
    (df_final['score_3'] > 2) &
    (df_final['excluir_num_3'] == False) &
    (df_final['excluir_nom_3'] == False) &
    (df_final['entidad_similar_3_iguales'] == False)
    )

In [231]:
df_final.loc[filtro_2_1, 'fusion_1'] = True
df_final.loc[filtro_2_2, 'fusion_2'] = True
df_final.loc[filtro_2_3, 'fusion_3'] = True

## Filtro 3

In [232]:
filtro_3_1 = (
    (df_final["dist_overlap_1"] == 1) &
    (df_final["dist_jaro_1"] >= 0.9) &
    (df_final["score_1"] >= 4.5) &
    (df_final['excluir_num_1'] == False) &
    (df_final['excluir_nom_1'] == False) &
    (df_final['entidad_similar_1_iguales'] == False)
    )

In [233]:
filtro_3_2 = (
    (df_final["dist_overlap_2"] == 1) &
    (df_final["dist_jaro_2"] >= 0.9) &
    (df_final["score_2"] >= 4.5) &
    (df_final['excluir_num_2'] == False) &
    (df_final['excluir_nom_2'] == False) &
    (df_final['entidad_similar_2_iguales'] == False)
    )

In [234]:
filtro_3_3 = (
    (df_final["dist_overlap_3"] == 1) &
    (df_final["dist_jaro_3"] >= 0.9) &
    (df_final["score_3"] >= 4.5) &
    (df_final['excluir_num_3'] == False) &
    (df_final['excluir_nom_3'] == False) &
    (df_final['entidad_similar_3_iguales'] == False)
    )

In [235]:
df_final.loc[filtro_3_1, 'fusion_1'] = True
df_final.loc[filtro_3_2, 'fusion_2'] = True
df_final.loc[filtro_3_3, 'fusion_3'] = True

In [236]:
df_final

,Entidad,similar_1,score_1,similar_2,score_2,similar_3,score_3,entidad_similar_1_iguales,entidad_similar_2_iguales,entidad_similar_3_iguales,...,dist_overlap_3,excluir_num_1,excluir_num_2,excluir_num_3,excluir_nom_1,excluir_nom_2,excluir_nom_3,fusion_1,fusion_2,fusion_3
0,night at the movies,night at the movies,5.382150,a night at the movies,5.382150,saturday night at the movies,4.438026,True,False,False,...,1.000000,False,False,False,False,False,False,False,True,False
1,chicago ten,chicago ten,5.939967,chicago,3.391698,ten ready rifles,2.696221,True,False,False,...,0.285714,False,False,False,False,False,False,False,False,False
2,jack shea,jack shea,6.195229,jack ferver,2.711984,jack macgowran,2.711984,True,False,False,...,0.666667,False,False,False,False,True,True,False,False,False
3,harry johnson,harry johnson,5.582535,emory johnson,2.870550,daniel johnson,2.870550,True,False,False,...,0.692308,False,False,False,False,True,True,False,False,False
4,harsin,harsin,4.153368,harsin county,3.269801,chahār,0.000000,True,False,False,...,0.500000,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6253,mathews,j e mathews,3.974786,mathews,3.974786,travis mathews,3.129210,False,True,False,...,1.000000,False,False,False,False,False,False,False,False,False
6254,romanian,romanian,4.424488,roman,0.000000,greek,0.000000,True,False,False,...,0.200000,False,False,False,False,False,False,False,False,False
6255,chahār,chahār,4.424488,roman,0.000000,greek,0.000000,True,False,False,...,0.200000,False,False,False,False,False,False,False,False,False
6256,greek,greek,4.424488,roman,0.000000,chahār,0.000000,True,False,False,...,0.200000,False,False,False,False,False,False,False,False,False
6257,roman,roman,3.343415,roman emperor,2.632154,roman empire,2.632154,True,False,False,...,1.000000,False,False,False,False,False,False,False,False,False

# UNION FINAL

In [237]:
cols_1 = ['Entidad', 'similar_1','score_1','dist_jaro_1', 'dist_leven_1','dist_jaccard_1', 'dist_overlap_1','fusion_1']
cols_2 = ['Entidad', 'similar_2','score_2','dist_jaro_2', 'dist_leven_2','dist_jaccard_2', 'dist_overlap_2','fusion_2']
cols_3 = ['Entidad', 'similar_3','score_3','dist_jaro_3', 'dist_leven_3','dist_jaccard_3', 'dist_overlap_3','fusion_3']

df_final_fusion_1 = df_final.loc[df_final['fusion_1'] == True][cols_1]
df_final_fusion_2 = df_final.loc[df_final['fusion_2'] == True][cols_2]
df_final_fusion_3 = df_final.loc[df_final['fusion_3'] == True][cols_3]

rename_cols_1 = {'similar_1': "similar",'score_1': "score",'dist_jaro_1': "dist_jaro", 'dist_leven_1': "dist_leven",'dist_jaccard_1': "dist_jaccard", 'dist_overlap_1': "dist_overlap",'fusion_1': "fusion"}
rename_cols_2 = {'similar_2': "similar",'score_2': "score",'dist_jaro_2': "dist_jaro", 'dist_leven_2': "dist_leven",'dist_jaccard_2': "dist_jaccard", 'dist_overlap_2': "dist_overlap",'fusion_2': "fusion"}
rename_cols_3 = {'similar_3': "similar",'score_3': "score",'dist_jaro_3': "dist_jaro", 'dist_leven_3': "dist_leven",'dist_jaccard_3': "dist_jaccard", 'dist_overlap_3': "dist_overlap",'fusion_3': "fusion"}

df_final_fusion_1 = df_final_fusion_1.rename(columns = rename_cols_1)
df_final_fusion_2 = df_final_fusion_2.rename(columns = rename_cols_2)
df_final_fusion_3 = df_final_fusion_3.rename(columns = rename_cols_3)

In [238]:
df_final_fusion = pd.concat([df_final_fusion_1, df_final_fusion_2, df_final_fusion_3], ignore_index=True)

In [239]:
df_final_fusion = df_final_fusion.drop_duplicates(["Entidad", "similar"]).sort_values("Entidad")

In [240]:
df_final_fusion

,Entidad,similar,score,dist_jaro,dist_leven,dist_jaccard,dist_overlap,fusion
536,1934 film of the same title,1934 film,4.548065,0.920000,0.600000,0.600000,1.0,True
232,400 metres,400 metres event,4.987405,0.925000,0.625000,0.625000,1.0,True
328,400 metres event,400 metres,6.048401,0.925000,0.625000,0.625000,1.0,True
235,a b fazle karim chowdhury,a m b fazle karim chowdhury,6.707862,0.871884,0.920000,0.920000,1.0,True
33,a b fazle karim chowdhury,a b m fazle karim chowdhury,6.707862,0.909101,0.920000,0.920000,1.0,True
...,...,...,...,...,...,...,...,...
561,"wyoming county, west virginia",wyoming county,4.923106,0.900000,0.500000,0.500000,1.0,True
156,young philadelphians,the young philadelphians,5.621514,1.000000,1.000000,1.000000,1.0,True
195,yukon – koyukuk census area,"yukon – koyukuk census area, alaska",7.898044,0.956250,0.781250,0.781250,1.0,True
470,"yukon – koyukuk census area, alaska",yukon – koyukuk census area,9.076736,0.956250,0.781250,0.781250,1.0,True
127,zayed bin sultan al nahyan,sheikh zayed bin sultan al nahyan,7.492914,0.801088,0.787879,0.787879,1.0,True

# Obtencion de parejas y gruupos de fusion

In [265]:

entidades_1 = df_final_fusion['Entidad'].tolist()
entidades_2 = df_final_fusion['similar'].tolist()
set_entidades = list(set(entidades_1 + entidades_2)) # PAra buscar nodos con grados muy altos

In [262]:
grupos = []

for item1, item2 in zip(entidades_1, entidades_2):
    encontrados = []
    for grupo in grupos:
        if item1 in grupo or item2 in grupo:
            encontrados.append(grupo)

    if not encontrados:
        grupos.append({item1, item2})
    else:
        nuevo_grupo = {item1, item2}
        for g in encontrados:
            nuevo_grupo.update(g)
            grupos.remove(g)
        grupos.append(nuevo_grupo)

resultado = [list(g) for g in grupos]

[['1934 film', '1934 film of the same title'], ['400 metres', '400 metres event'], ['abd al-muttalib shaybah', 'abd al-muttalib shaybah ibn hashim'], ['abstract art', 'abstract artist'], ['academy award for best picture', 'academy award for best director'], ['adventure film', 'adventure drama film'], ['al-hasan ibn ali', 'al-hasan ibn ali ibn abi talib'], ['alexander of cyprus', 'alexander cyprius'], ['alexander von zemlinsky', 'alexander zemlinsky'], ['american director', 'american film director'], ['andrew ii', 'andrew ii of hungary'], ['andrew murray craven', 'andrew murray'], ['anne, duchess of cumberland', 'anne, duchess of cumberland and strathearn'], ['another latin love song/ miss world', 'another latin love song/miss world', 'another latin love song'], ['bob dylan', 'another side of bob dylan'], ['archibald bulloch roosevelt', 'archibald bulloch', 'archibald bulloch roosevelt jr'], ['australian rules football', 'australian rules', 'australian rules footballer'], ['battle of wei river (濰水之戰)', 'battle of wei river'], ['belcher channel', 'belcher channel formation'], ['bergen county, new jersey', 'bergen county'], ['bernard nathanson', 'bernard n nathanson'], ['bertha wehnert-beckmann', 'bertha wehnert'], ['bill evans', 'bill evans trio'], ['bomba, the jungle boy', 'bomba and the jungle girl'], ['calcasieu parish', 'calcasieu parish, louisiana'], ['canadian football', 'canadian football league'], ['carbon-fibre composite', 'carbon-fiber', 'carbon-fibre'], ['cedar park', 'cedar park, texas'], ['chahar taq', 'chahar taq bon', 'chahar taq-e bala'], ['charles anselm sallier', 'charles sallier'], ['chemung county, new york', 'chemung county'], ['cheshmeh-ye ali mohammad', 'cheshmeh-ye hajji mohammad', 'cheshmeh-ye hajji soleyman'], ["children's book", "children's books"], ['collegiate gothic style', 'collegiate gothic'], ['comedy-drama film', 'comedy-drama', 'comedy drama film'], ['coming-of-age drama', 'coming-of-age film'], ['compilation albums', 'compilation album'], ['conservative national caucus chair', 'conservative national caucus chair for her majesty ’s loyal opposition', 'conservative national caucus'], ['cranbrook school, sydney', 'cranbrook school'], ['crime drama film', 'crime drama'], ['dark mountain', 'dark mountain project'], ['dinesh babu', 'dinesh baboo'], ['director general of police in punjab', 'director general of police'], ['do you remember dolly bell?', 'do you remember dolly bell'], ['drb-hicom', 'drb-hicom berhad'], ['dubai ruling family', "dubai's ruling family"], ['eastern cape', 'eastern cape province'], ['ecumenical patriarch', 'ecumenical patriarch of constantinople'], ['edward iv of england', 'edward iv, king of england'], ['efzar district', 'efzar rural district'], ['eleni zaude gabre-madhin', 'eleni zaude gabre'], ['elvis presley', 'elvis aaron presley'], ['fatima bint mubarak al ketbi', 'fatima bint mubarak'], ['a b m fazle karim chowdhury', 'a m b fazle karim chowdhury', 'a b fazle karim chowdhury', 'a m fazle karim chowdhury', 'fazle karim chowdhury', 'abm fazle karim chowdhury'], ['felix frankfurter professor of law', 'felix frankfurter'], ['films produced in turkmenistan', 'film produced in turkmenistan'], ['television director', 'film and television director', 'film/television director'], ['television producer', 'film/television producer'], ['films produced in japan', 'films produced', 'a list of films produced in japan'], ['first romanesque style', 'first romanesque'], ['frank zappa', 'frank vincent zappa'], ['g devarajan', 'devarajan'], ['george lamb hannah', 'george lamb'], ['george h melford', 'george melford'], ['george plantagenet, 1st duke of', 'george plantagenet, 1st duke of bedford'], ['georgina rose', 'georgina rose chapman'], ['gertrude of saxony', 'gertrude of saxony and bavaria'], ["girls' school", "girls' schools"], ['giyan rural district', 'giyan district'], ['glen cove, long island, new york', 'glen cove, long island'], ['grand canyon', 'grand canyon adventure'], ['greene county, new york', 'greene county'], ['group stage', 'first group stage'], ['gus green van sant jr', 'gus green van sant'], ['hasan ibn hasan', 'hasan ibn ali'], ['hassan ii university in casablanca', 'hassan ii university'], ['henry bryant', 'henry bryant bigelow'], ['horror drama film', 'horror drama'], ['humboldt county', 'humboldt county, california'], ["i don't believe you (she acts like we never have met)", "i don't believe you (she acts like we never have met"], ["i'm a celebrity  get me out of here!", "i'm a celebrity get me out of here!"], ['identity documents', 'identity document'], ['iglesia de santa maría de los reyes', 'iglesia de santa maría', 'iglesia de santa maría de palacio'], ['indie rock', 'indie-rock'], ['international school', 'international school of koje'], ['islamic revivalist movement in syria', 'islamic revivalist'], ['it goes like this', 'it goes like it goes'], ['jack conway', 'jack ryan conway'], ['jatt & juliet', 'jatt& juliet'], ['john montagu douglas scott, 7th duke of buccleuch', 'john montagu douglas scott, 7th'], ['josephine roberto', 'josephine roberto aka banig'], ['joaquim pimentel ribeiro', 'joaquim pimentel', 'joaquim viana pimentel', 'josé joaquim pimentel ribeiro', 'joaquim viana', 'josé joaquim pimentel'], ['josefina tapias', 'joséfina tapias'], ['kamazan-e sofla rural district', 'kamazan-e vosta rural district'], ['karamana janardanan', 'karamana janardanan nair'], ['kekuʻiapoiwa', 'kekuʻiapoiwa ii'], ['kfar yedidia', 'kfar yedidia, israel'], ['george iii of the united kingdom', 'king george iii of the united kingdom'], ['kinga of poland (kunegunda)', 'kinga of poland', 'kinga of poland (cunegunda)'], ['knox county, kentucky', 'knox county'], ['kohanabad district', 'kohanabad rural district'], ['kohgiluyeh and boyer', 'kohgiluyeh and boyer-ahmand province', 'kohgiluyeh and boyer-ahmad province', 'kohgiluyeh and boyer-ah province', 'kohgiluyeh and boyer-ahmir province'], ['krishnankoil venkadachalam mahadevan', 'krishnankoil venkadachalam'], ['kuhenjan rural district', 'kuhenjan district'], ['la torre de los suplicios', 'la torre de suso'], ['lady almeria carpenter', 'almeria carpenter'], ['lake charles', 'lake charles, louisiana'], ['legislative assembly', 'legislative assembly of ontario'], ['lesser slave lake provincial park', 'lesser slave river', 'lesser slave lake'], ['lewis county', 'lewis county, missouri'], ['cork senior inter-county team', 'limerick senior inter-county team'], ['linda lee cadwell', 'linda lee caldwell'], ['a list of films produced in turkmenistan', 'list of films produced in turkmenistan'], ['film produced in uruguay', 'list of films produced in uruguay', 'a list of films produced in uruguay', 'films produced in uruguay'], ['little man, what now?', 'little man'], ['los angeles, california', 'los angeles'], ['manuel i komnenos', 'manuel komnenos'], ['margown rural district', 'margown district'], ['martha bulloch roosevelt', 'martha bulloch'], ['marthandan', 'g marthandan'], ['mass cycle', 'mass cycles'], ['mazraeh-ye ali shafi', 'mazraeh-ye ali sirjani', 'mazraeh-ye ali hasan-e sofla', 'mazraeh-ye ali akbar hayati', 'mazraeh-ye ali hasan', 'mazraeh-ye ali', 'mazraeh-ye ali faqihi', 'mazraeh-ye ali akbar khan', 'mazraeh-ye ali reza baharlu'], ['mazraeh-ye rezavi', 'mazraeh-ye razavi'], ['mazraeh-ye shomali rural district', 'mazraeh-ye jonubi rural district'], ['me', 'me or me'], ['melissa moore', 'melissa ann moore'], ['michael powell', 'michael latham powell'], ['michel jacques boisrond', 'michel boisrond'], ['miklós jancs', 'miklós jancs ó'], ['military intelligence', 'military intelligence organization'], ['mirza ghulam ahmad', 'mirza ghulam ahmad of qadian'], ['mohamed husseini', 'mohamed husseini mohamed'], ['mohamed mahmoud abdelaziz', 'mohamed abdelaziz tchikou', 'mohamed abdelaziz'], ['morena clara (telenovela)', 'morena clara'], ['motion picture actor', 'motion picture', 'motion picture director'], ['mph group malaysia', 'mph group'], ['mr moto', "mr moto's gamble"], ['mr boggs steps out', 'mr muggs steps out', 'muggs steps out', 'boggs steps out'], ['musical film', 'musical drama film'], ['my heart', 'always in my heart', 'in my heart'], ['naghan district', 'naghan rural district'], ['nancy travis', 'nancy ann travis'], ['nandi award for best director', 'nandi award for best director – telugu'], ['national gallery of australia', 'national gallery of australia (canberra)'], ['democratic party', 'new democratic party'], ['new kent county, virginia', 'new kent county'], ['new york city', 'new york'], ['a night at the movies', 'night at the movies'], ['nila madhab', 'nila madhab panda'], ['noura khalifa al suwaidi', 'noura khalifa'], ["o'grady", "o' grady"], ['odrysian kingdom', 'odrysian kingdom of thrace'], ['one touch of venus', 'one touch of venus (film)'], ['oscar c apfel', 'oscar apfel'], ['oxford university', 'oxford university cricket club'], ['pahlavi dynasties', 'pahlavi dynasty'], ['marc paul alain dutroux', 'paul alain dutroux'], ['peer-reviewed', 'peer-review'], ['philip ives dunne', 'philip dunne'], ["giorgio dall'acqua", "pier giorgio dall'acqua"], ['pinal county, arizona', 'pinal county'], ['pornographic film director', 'pornographic film'], ['prince henry, duke of cumberland', 'prince henry, duke of cumberland and strathearn'], ['princess augusta of saxe-gotha-altenburg', 'princess augusta of saxe-gotha'], ['rafe kovich and alison barrington kovich', 'rafe kovich and alison barrington'], ['rapid rail', 'rapid rail sdn bhd'], ['razavi khorasan province', 'razavi khorasan'], ['rhett akins jr', 'rhett akins'], ['richard of shrewsbury, 1st duke of york', 'richard of shrewsbury, 1'], ['richard woodville, 1st', 'richard woodville, 1st earl rivers'], ['robert parrish', 'robert r parrish'], ['robert the bruce', 'robert the bruce, king of scots'], ['roman catholic', 'roman catholic church'], ['roman catholic diocese of springfield', 'roman catholic diocese of sioux falls', 'roman catholic diocese of springfield in illinois'], ['romantic comedy', 'romantic comedy film'], ['royal oak', 'royal oak, michigan'], ['royal veterinary academy', 'royal veterinary academy of berlin'], ['rukn al-din mubarak khwaja', 'rukn al-din mubarak'], ['rush dew holt sr', 'rush dew holt'], ['salehabad rural district', 'salehabad district'], ['english name', 'same english name'], ['san francisco, california', 'san francisco'], ['santa clara county, california', 'santa clara university', 'santa clara', 'santa clara, california', 'santa clara county'], ['santa maría de oseira', 'santa maría'], ['sarre anglo-saxon cemetery', 'sarre anglo-saxon'], ['j sasikumar', 'sasikumar'], ['saturday night fever', 'saturday night at the movies'], ['science fiction film', 'science fiction'], ['scr corporation sdn bhd', 'scr corporation'], ['sedeh district', 'sedeh rural district'], ['sex comedy film', 'sex comedy'], ['shannon lee sanderford', 'shannon lee dawdy', 'shannon lee tweed', 'shannon emery', 'shannon lee day', 'shannon emery lee', 'shannon lee tweed simmons', 'shannon lee'], ['sheika latifa', 'sheikha latifa'], ['ahmed bin rashid al maktoum', 'sheikh ahmed bin rashid al maktoum'], ['mohammed bin rashid al', 'sheikh mohammed bin rashid al maktoum', 'mohammed bin rashid al maktoum', 'mohammed bin rashid al maktou'], ['sherlock holmes films', 'sherlock holmes'], ['shocking asia ii', 'shocking asia'], ['sierra leone president', 'sierra leone'], ['sierra leonean president', 'sierra leonean', 'sierra leonean army'], ['silent film era', 'silent film', 'silent era'], ['sir humphry davy', 'humphry davy'], ['siskiyou county, california', 'siskiyou county'], ['six nations of the grand river territory, ontario', 'six nations of the grand river territory'], ['sky dylan dayton', 'dylan dayton'], ['slave lake', 'slave lake airport'], ['sme ordnance', 'sme ordnance sdn bhd'], ['and so it goes', 'so it goes'], ['sorority house massacre ii', 'sorority house massacre'], ['south australian', 'south australian government'], ["st antony's college, oxford", "st antony's college"], ["st mary's high school", 'st mary high school', "st mary's high school, quetta"], ["st rumbold's cathedral", "rumbold's cathedral"], ['st mother teresa high school', 'st teresa high school'], ['star trek into darkness', 'star trek'], ["stefano dell' arzere", "stefano dell'"], ['still-life', 'still-lifes'], ['suspense-thriller-drama film', 'suspense thriller film'], ["takeshi's castle", "takeshi's castle wwe raw"], ['tavistock clinic and institute', 'tavistock clinic'], ['the colvos store', 'colvos store'], ['the cradle of humankind', 'cradle of humankind'], ['the first part', 'first part'], ["the fools' hall of fame", "fools' hall of fame"], ['good old days', 'the good old days'], ['the international school of columbus', 'international school of columbus'], ['the legend of the condor heroes', 'legend of the condor heroes'], ['model technical higher secondary schools', 'model technical higher secondary school', 'the model technical higher secondary school'], ['norman rockwell code', 'the norman rockwell code'], ['the piano tuner', 'the piano tuner has', 'the piano tuner has arrived'], ['pony express', 'the pony express'], ['the second part', 'second part'], ['star of india', 'the star of india'], ['sword stained with royal blood', 'the sword stained with royal blood'], ['the taking of pelham one two three', 'the taking of pelham one two three the conversation'], ['theme from" mission: impossible', 'mission: impossible iii', 'mission: impossible'], ['the theme music', 'theme music'], ['theodore roosevelt, jr', 'theodore roosevelt'], ['thief has arrived', 'a thief has arrived'], ['three days of the condor', 'last days of the condor', 'six days of the condor'], ['time on my hands (song)', 'time on my hands'], ['toma t socolescu', 'toma n socolescu'], ['tomás fernández', 'tomás fernández ruiz'], ['trade register', 'trade registers in several countries', 'trade registers'], ['trinidad perez', 'trinidad perez tecson'], ['trinity college', 'trinity college, cambridge'], ['trois-rivières, quebec', 'trois-rivières'], ['electric clouds', 'under electric clouds'], ['united arab emirates (uae)', 'united arab emirates (uae', 'united arab emirates'], ['united states senator', 'united states'], ['university of chicago press', 'university of chicago'], ['university of wisconsin-madison', 'university of wisconsin – madison', 'university of wisconsin'], ['victor schertzinger', 'victor l schertzinger'], ['augustus barratt', 'w augustus barratt'], ['when father was away on businessunderground', 'when father was away on business'], ['the white god', 'white god'], ['why did i get married?', 'why did i get married too?', 'why did i get married'], ['william berke', 'william a berke'], ['william marshall (died 1540)', 'william marshall (died 1540?)'], ['william marshall', 'william marshall tredway'], ["women's 4 × 400 metres relay event", "women's 4 × 400 metres relay"], ['wood island light, maine', 'wood island light'], ['wyoming county, west virginia', 'wyoming county'], ['young philadelphians', 'the young philadelphians'], ['yukon – koyukuk census area, alaska', 'yukon – koyukuk census area'], ['zayed bin sultan al nahyan', 'sheikh zayed bin sultan al nahyan']]

In [263]:
grupos

[{'1934 film', '1934 film of the same title'},
 {'400 metres', '400 metres event'},
 {'abd al-muttalib shaybah', 'abd al-muttalib shaybah ibn hashim'},
 {'abstract art', 'abstract artist'},
 {'academy award for best director', 'academy award for best picture'},
 {'adventure drama film', 'adventure film'},
 {'al-hasan ibn ali', 'al-hasan ibn ali ibn abi talib'},
 {'alexander cyprius', 'alexander of cyprus'},
 {'alexander von zemlinsky', 'alexander zemlinsky'},
 {'american director', 'american film director'},
 {'andrew ii', 'andrew ii of hungary'},
 {'andrew murray', 'andrew murray craven'},
 {'anne, duchess of cumberland', 'anne, duchess of cumberland and strathearn'},
 {'another latin love song',
  'another latin love song/ miss world',
  'another latin love song/miss world'},
 {'another side of bob dylan', 'bob dylan'},
 {'archibald bulloch',
  'archibald bulloch roosevelt',
  'archibald bulloch roosevelt jr'},
 {'australian rules',
  'australian rules football',
  'australian rules footballer'},
 {'battle of wei river', 'battle of wei river (濰水之戰)'},
 {'belcher channel', 'belcher channel formation'},
 {'bergen county', 'bergen county, new jersey'},
 {'bernard n nathanson', 'bernard nathanson'},
 {'bertha wehnert', 'bertha wehnert-beckmann'},
 {'bill evans', 'bill evans trio'},
 {'bomba and the jungle girl', 'bomba, the jungle boy'},
 {'calcasieu parish', 'calcasieu parish, louisiana'},
 {'canadian football', 'canadian football league'},
 {'carbon-fiber', 'carbon-fibre', 'carbon-fibre composite'},
 {'cedar park', 'cedar park, texas'},
 {'chahar taq', 'chahar taq bon', 'chahar taq-e bala'},
 {'charles anselm sallier', 'charles sallier'},
 {'chemung county', 'chemung county, new york'},
 {'cheshmeh-ye ali mohammad',
  'cheshmeh-ye hajji mohammad',
  'cheshmeh-ye hajji soleyman'},
 {"children's book", "children's books"},
 {'collegiate gothic', 'collegiate gothic style'},
 {'comedy drama film', 'comedy-drama', 'comedy-drama film'},
 {'coming-of-age drama', 'coming-of-age film'},
 {'compilation album', 'compilation albums'},
 {'conservative national caucus',
  'conservative national caucus chair',
  'conservative national caucus chair for her majesty ’s loyal opposition'},
 {'cranbrook school', 'cranbrook school, sydney'},
 {'crime drama', 'crime drama film'},
 {'dark mountain', 'dark mountain project'},
 {'dinesh baboo', 'dinesh babu'},
 {'director general of police', 'director general of police in punjab'},
 {'do you remember dolly bell', 'do you remember dolly bell?'},
 {'drb-hicom', 'drb-hicom berhad'},
 {'dubai ruling family', "dubai's ruling family"},
 {'eastern cape', 'eastern cape province'},
 {'ecumenical patriarch', 'ecumenical patriarch of constantinople'},
 {'edward iv of england', 'edward iv, king of england'},
 {'efzar district', 'efzar rural district'},
 {'eleni zaude gabre', 'eleni zaude gabre-madhin'},
 {'elvis aaron presley', 'elvis presley'},
 {'fatima bint mubarak', 'fatima bint mubarak al ketbi'},
 {'a b fazle karim chowdhury',
  'a b m fazle karim chowdhury',
  'a m b fazle karim chowdhury',
  'a m fazle karim chowdhury',
  'abm fazle karim chowdhury',
  'fazle karim chowdhury'},
 {'felix frankfurter', 'felix frankfurter professor of law'},
 {'film produced in turkmenistan', 'films produced in turkmenistan'},
 {'film and television director',
  'film/television director',
  'television director'},
 {'film/television producer', 'television producer'},
 {'a list of films produced in japan',
  'films produced',
  'films produced in japan'},
 {'first romanesque', 'first romanesque style'},
 {'frank vincent zappa', 'frank zappa'},
 {'devarajan', 'g devarajan'},
 {'george lamb', 'george lamb hannah'},
 {'george h melford', 'george melford'},
 {'george plantagenet, 1st duke of',
  'george plantagenet, 1st duke of bedford'},
 {'georgina rose', 'georgina rose chapman'},
 {'gertrude of saxony', 'gertrude of saxony and bavaria'},
 {"girls' school", "girls' schools"},
 {'giyan district', 'giyan rural district'},
 {'glen cove, long island', 'glen cove, long island, new york'},
 {'grand canyon', 'grand canyon adventure'},
 {'greene county', 'greene county, new york'},
 {'first group stage', 'group stage'},
 {'gus green van sant', 'gus green van sant jr'},
 {'hasan ibn ali', 'hasan ibn hasan'},
 {'hassan ii university', 'hassan ii university in casablanca'},
 {'henry bryant', 'henry bryant bigelow'},
 {'horror drama', 'horror drama film'},
 {'humboldt county', 'humboldt county, california'},
 {"i don't believe you (she acts like we never have met",
  "i don't believe you (she acts like we never have met)"},
 {"i'm a celebrity  get me out of here!",
  "i'm a celebrity get me out of here!"},
 {'identity document', 'identity documents'},
 {'iglesia de santa maría',
  'iglesia de santa maría de los reyes',
  'iglesia de santa maría de palacio'},
 {'indie rock', 'indie-rock'},
 {'international school', 'international school of koje'},
 {'islamic revivalist', 'islamic revivalist movement in syria'},
 {'it goes like it goes', 'it goes like this'},
 {'jack conway', 'jack ryan conway'},
 {'jatt & juliet', 'jatt& juliet'},
 {'john montagu douglas scott, 7th',
  'john montagu douglas scott, 7th duke of buccleuch'},
 {'josephine roberto', 'josephine roberto aka banig'},
 {'joaquim pimentel',
  'joaquim pimentel ribeiro',
  'joaquim viana',
  'joaquim viana pimentel',
  'josé joaquim pimentel',
  'josé joaquim pimentel ribeiro'},
 {'josefina tapias', 'joséfina tapias'},
 {'kamazan-e sofla rural district', 'kamazan-e vosta rural district'},
 {'karamana janardanan', 'karamana janardanan nair'},
 {'kekuʻiapoiwa', 'kekuʻiapoiwa ii'},
 {'kfar yedidia', 'kfar yedidia, israel'},
 {'george iii of the united kingdom', 'king george iii of the united kingdom'},
 {'kinga of poland',
  'kinga of poland (cunegunda)',
  'kinga of poland (kunegunda)'},
 {'knox county', 'knox county, kentucky'},
 {'kohanabad district', 'kohanabad rural district'},
 {'kohgiluyeh and boyer',
  'kohgiluyeh and boyer-ah province',
  'kohgiluyeh and boyer-ahmad province',
  'kohgiluyeh and boyer-ahmand province',
  'kohgiluyeh and boyer-ahmir province'},
 {'krishnankoil venkadachalam', 'krishnankoil venkadachalam mahadevan'},
 {'kuhenjan district', 'kuhenjan rural district'},
 {'la torre de los suplicios', 'la torre de suso'},
 {'almeria carpenter', 'lady almeria carpenter'},
 {'lake charles', 'lake charles, louisiana'},
 {'legislative assembly', 'legislative assembly of ontario'},
 {'lesser slave lake',
  'lesser slave lake provincial park',
  'lesser slave river'},
 {'lewis county', 'lewis county, missouri'},
 {'cork senior inter-county team', 'limerick senior inter-county team'},
 {'linda lee cadwell', 'linda lee caldwell'},
 {'a list of films produced in turkmenistan',
  'list of films produced in turkmenistan'},
 {'a list of films produced in uruguay',
  'film produced in uruguay',
  'films produced in uruguay',
  'list of films produced in uruguay'},
 {'little man', 'little man, what now?'},
 {'los angeles', 'los angeles, california'},
 {'manuel i komnenos', 'manuel komnenos'},
 {'margown district', 'margown rural district'},
 {'martha bulloch', 'martha bulloch roosevelt'},
 {'g marthandan', 'marthandan'},
 {'mass cycle', 'mass cycles'},
 {'mazraeh-ye ali',
  'mazraeh-ye ali akbar hayati',
  'mazraeh-ye ali akbar khan',
  'mazraeh-ye ali faqihi',
  'mazraeh-ye ali hasan',
  'mazraeh-ye ali hasan-e sofla',
  'mazraeh-ye ali reza baharlu',
  'mazraeh-ye ali shafi',
  'mazraeh-ye ali sirjani'},
 {'mazraeh-ye razavi', 'mazraeh-ye rezavi'},
 {'mazraeh-ye jonubi rural district', 'mazraeh-ye shomali rural district'},
 {'me', 'me or me'},
 {'melissa ann moore', 'melissa moore'},
 {'michael latham powell', 'michael powell'},
 {'michel boisrond', 'michel jacques boisrond'},
 {'miklós jancs', 'miklós jancs ó'},
 {'military intelligence', 'military intelligence organization'},
 {'mirza ghulam ahmad', 'mirza ghulam ahmad of qadian'},
 {'mohamed husseini', 'mohamed husseini mohamed'},
 {'mohamed abdelaziz',
  'mohamed abdelaziz tchikou',
  'mohamed mahmoud abdelaziz'},
 {'morena clara', 'morena clara (telenovela)'},
 {'motion picture', 'motion picture actor', 'motion picture director'},
 {'mph group', 'mph group malaysia'},
 {'mr moto', "mr moto's gamble"},
 {'boggs steps out',
  'mr boggs steps out',
  'mr muggs steps out',
  'muggs steps out'},
 {'musical drama film', 'musical film'},
 {'always in my heart', 'in my heart', 'my heart'},
 {'naghan district', 'naghan rural district'},
 {'nancy ann travis', 'nancy travis'},
 {'nandi award for best director', 'nandi award for best director – telugu'},
 {'national gallery of australia', 'national gallery of australia (canberra)'},
 {'democratic party', 'new democratic party'},
 {'new kent county', 'new kent county, virginia'},
 {'new york', 'new york city'},
 {'a night at the movies', 'night at the movies'},
 {'nila madhab', 'nila madhab panda'},
 {'noura khalifa', 'noura khalifa al suwaidi'},
 {"o' grady", "o'grady"},
 {'odrysian kingdom', 'odrysian kingdom of thrace'},
 {'one touch of venus', 'one touch of venus (film)'},
 {'oscar apfel', 'oscar c apfel'},
 {'oxford university', 'oxford university cricket club'},
 {'pahlavi dynasties', 'pahlavi dynasty'},
 {'marc paul alain dutroux', 'paul alain dutroux'},
 {'peer-review', 'peer-reviewed'},
 {'philip dunne', 'philip ives dunne'},
 {"giorgio dall'acqua", "pier giorgio dall'acqua"},
 {'pinal county', 'pinal county, arizona'},
 {'pornographic film', 'pornographic film director'},
 {'prince henry, duke of cumberland',
  'prince henry, duke of cumberland and strathearn'},
 {'princess augusta of saxe-gotha',
  'princess augusta of saxe-gotha-altenburg'},
 {'rafe kovich and alison barrington',
  'rafe kovich and alison barrington kovich'},
 {'rapid rail', 'rapid rail sdn bhd'},
 {'razavi khorasan', 'razavi khorasan province'},
 {'rhett akins', 'rhett akins jr'},
 {'richard of shrewsbury, 1', 'richard of shrewsbury, 1st duke of york'},
 {'richard woodville, 1st', 'richard woodville, 1st earl rivers'},
 {'robert parrish', 'robert r parrish'},
 {'robert the bruce', 'robert the bruce, king of scots'},
 {'roman catholic', 'roman catholic church'},
 {'roman catholic diocese of sioux falls',
  'roman catholic diocese of springfield',
  'roman catholic diocese of springfield in illinois'},
 {'romantic comedy', 'romantic comedy film'},
 {'royal oak', 'royal oak, michigan'},
 {'royal veterinary academy', 'royal veterinary academy of berlin'},
 {'rukn al-din mubarak', 'rukn al-din mubarak khwaja'},
 {'rush dew holt', 'rush dew holt sr'},
 {'salehabad district', 'salehabad rural district'},
 {'english name', 'same english name'},
 {'san francisco', 'san francisco, california'},
 {'santa clara',
  'santa clara county',
  'santa clara county, california',
  'santa clara university',
  'santa clara, california'},
 {'santa maría', 'santa maría de oseira'},
 {'sarre anglo-saxon', 'sarre anglo-saxon cemetery'},
 {'j sasikumar', 'sasikumar'},
 {'saturday night at the movies', 'saturday night fever'},
 {'science fiction', 'science fiction film'},
 {'scr corporation', 'scr corporation sdn bhd'},
 {'sedeh district', 'sedeh rural district'},
 {'sex comedy', 'sex comedy film'},
 {'shannon emery',
  'shannon emery lee',
  'shannon lee',
  'shannon lee dawdy',
  'shannon lee day',
  'shannon lee sanderford',
  'shannon lee tweed',
  'shannon lee tweed simmons'},
 {'sheika latifa', 'sheikha latifa'},
 {'ahmed bin rashid al maktoum', 'sheikh ahmed bin rashid al maktoum'},
 {'mohammed bin rashid al',
  'mohammed bin rashid al maktou',
  'mohammed bin rashid al maktoum',
  'sheikh mohammed bin rashid al maktoum'},
 {'sherlock holmes', 'sherlock holmes films'},
 {'shocking asia', 'shocking asia ii'},
 {'sierra leone', 'sierra leone president'},
 {'sierra leonean', 'sierra leonean army', 'sierra leonean president'},
 {'silent era', 'silent film', 'silent film era'},
 {'humphry davy', 'sir humphry davy'},
 {'siskiyou county', 'siskiyou county, california'},
 {'six nations of the grand river territory',
  'six nations of the grand river territory, ontario'},
 {'dylan dayton', 'sky dylan dayton'},
 {'slave lake', 'slave lake airport'},
 {'sme ordnance', 'sme ordnance sdn bhd'},
 {'and so it goes', 'so it goes'},
 {'sorority house massacre', 'sorority house massacre ii'},
 {'south australian', 'south australian government'},
 {"st antony's college", "st antony's college, oxford"},
 {'st mary high school',
  "st mary's high school",
  "st mary's high school, quetta"},
 {"rumbold's cathedral", "st rumbold's cathedral"},
 {'st mother teresa high school', 'st teresa high school'},
 {'star trek', 'star trek into darkness'},
 {"stefano dell'", "stefano dell' arzere"},
 {'still-life', 'still-lifes'},
 {'suspense thriller film', 'suspense-thriller-drama film'},
 {"takeshi's castle", "takeshi's castle wwe raw"},
 {'tavistock clinic', 'tavistock clinic and institute'},
 {'colvos store', 'the colvos store'},
 {'cradle of humankind', 'the cradle of humankind'},
 {'first part', 'the first part'},
 {"fools' hall of fame", "the fools' hall of fame"},
 {'good old days', 'the good old days'},
 {'international school of columbus', 'the international school of columbus'},
 {'legend of the condor heroes', 'the legend of the condor heroes'},
 {'model technical higher secondary school',
  'model technical higher secondary schools',
  'the model technical higher secondary school'},
 {'norman rockwell code', 'the norman rockwell code'},
 {'the piano tuner', 'the piano tuner has', 'the piano tuner has arrived'},
 {'pony express', 'the pony express'},
 {'second part', 'the second part'},
 {'star of india', 'the star of india'},
 {'sword stained with royal blood', 'the sword stained with royal blood'},
 {'the taking of pelham one two three',
  'the taking of pelham one two three the conversation'},
 {'mission: impossible',
  'mission: impossible iii',
  'theme from" mission: impossible'},
 {'the theme music', 'theme music'},
 {'theodore roosevelt', 'theodore roosevelt, jr'},
 {'a thief has arrived', 'thief has arrived'},
 {'last days of the condor',
  'six days of the condor',
  'three days of the condor'},
 {'time on my hands', 'time on my hands (song)'},
 {'toma n socolescu', 'toma t socolescu'},
 {'tomás fernández', 'tomás fernández ruiz'},
 {'trade register', 'trade registers', 'trade registers in several countries'},
 {'trinidad perez', 'trinidad perez tecson'},
 {'trinity college', 'trinity college, cambridge'},
 {'trois-rivières', 'trois-rivières, quebec'},
 {'electric clouds', 'under electric clouds'},
 {'united arab emirates',
  'united arab emirates (uae',
  'united arab emirates (uae)'},
 {'united states', 'united states senator'},
 {'university of chicago', 'university of chicago press'},
 {'university of wisconsin',
  'university of wisconsin – madison',
  'university of wisconsin-madison'},
 {'victor l schertzinger', 'victor schertzinger'},
 {'augustus barratt', 'w augustus barratt'},
 {'when father was away on business',
  'when father was away on businessunderground'},
 {'the white god', 'white god'},
 {'why did i get married',
  'why did i get married too?',
  'why did i get married?'},
 {'william a berke', 'william berke'},
 {'william marshall (died 1540)', 'william marshall (died 1540?)'},
 {'william marshall', 'william marshall tredway'},
 {"women's 4 × 400 metres relay", "women's 4 × 400 metres relay event"},
 {'wood island light', 'wood island light, maine'},
 {'wyoming county', 'wyoming county, west virginia'},
 {'the young philadelphians', 'young philadelphians'},
 {'yukon – koyukuk census area', 'yukon – koyukuk census area, alaska'},
 {'sheikh zayed bin sultan al nahyan', 'zayed bin sultan al nahyan'}]

# Obtener nodos con grados muy altos para prevenir fusion

In [266]:
from neo4j import GraphDatabase
driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=("neo4j", "password"),
    database = "2wiki.prueba.rebel.4",
)

In [278]:
get_n_relaciones = """
UNWIND $entidades as entidad
MATCH (n:Entity {name: entidad})
RETURN n.name AS name, COUNT{(n)--()} AS n_relaciones
"""
records, summary, key = driver.execute_query(get_n_relaciones, entidades = set_entidades)

In [ ]:
records

In [281]:
grados = {rec['name']: rec['n_relaciones'] for rec in records}

In [282]:
grados

{'mazraeh-ye shomali rural district': 4,
 'bomba, the jungle boy': 5,
 'do you remember dolly bell': 1,
 'naghan rural district': 4,
 'a b fazle karim chowdhury': 1,
 'eleni zaude gabre': 1,
 'santa maría': 7,
 'cheshmeh-ye ali mohammad': 4,
 'bill evans': 1,
 'indie rock': 5,
 'gus green van sant jr': 7,
 'star trek': 7,
 'dinesh babu': 1,
 'calcasieu parish': 6,
 'me': 6,
 'w augustus barratt': 1,
 'edward iv of england': 18,
 'trinidad perez tecson': 3,
 'electric clouds': 1,
 'philip dunne': 3,
 'mazraeh-ye ali': 11,
 'royal oak': 2,
 'when father was away on business': 9,
 'english name': 4,
 "takeshi's castle wwe raw": 1,
 'theodore roosevelt': 18,
 'knox county, kentucky': 2,
 'archibald bulloch': 10,
 'dinesh baboo': 4,
 'trade registers': 1,
 'felix frankfurter professor of law': 1,
 'the sword stained with royal blood': 8,
 'abm fazle karim chowdhury': 2,
 'the piano tuner has': 1,
 'gertrude of saxony': 4,
 'bill evans trio': 1,
 'motion picture director': 3,
 'odrysian kingdom of thrace': 1,
 'military intelligence organization': 1,
 'augustus barratt': 3,
 'conservative national caucus chair': 1,
 'los angeles': 8,
 'science fiction film': 1,
 'alexander zemlinsky': 4,
 'battle of wei river': 1,
 'kinga of poland': 3,
 'martha bulloch roosevelt': 6,
 'siskiyou county, california': 1,
 'odrysian kingdom': 3,
 'scr corporation': 1,
 'sheikh zayed bin sultan al nahyan': 2,
 'archibald bulloch roosevelt jr': 7,
 'the second part': 2,
 'musical drama film': 1,
 'peer-review': 1,
 'rapid rail': 3,
 'scr corporation sdn bhd': 1,
 'royal oak, michigan': 2,
 'academy award for best director': 2,
 'when father was away on businessunderground': 1,
 'marc paul alain dutroux': 2,
 'compilation album': 2,
 'drb-hicom berhad': 1,
 'edward iv, king of england': 4,
 'new york city': 10,
 'william marshall (died 1540?)': 1,
 'sherlock holmes films': 4,
 'list of films produced in turkmenistan': 2,
 'margown district': 8,
 'karamana janardanan nair': 5,
 'mirza ghulam ahmad': 5,
 'united arab emirates (uae': 1,
 'abd al-muttalib shaybah': 1,
 'young philadelphians': 3,
 'lewis county': 3,
 'university of chicago': 2,
 'charles anselm sallier': 4,
 'why did i get married': 1,
 'saturday night at the movies': 7,
 'cork senior inter-county team': 1,
 'kohanabad district': 5,
 'horror drama': 1,
 'sky dylan dayton': 3,
 'robert the bruce': 4,
 'rafe kovich and alison barrington': 2,
 'kfar yedidia, israel': 1,
 'glen cove, long island': 1,
 'sherlock holmes': 7,
 'little man': 6,
 'peer-reviewed': 1,
 'united states senator': 1,
 'santa clara county, california': 3,
 'films produced in uruguay': 3,
 'archibald bulloch roosevelt': 4,
 'always in my heart': 6,
 'why did i get married too?': 2,
 "i'm a celebrity get me out of here!": 1,
 'the young philadelphians': 9,
 'united arab emirates': 13,
 'bob dylan': 12,
 'iglesia de santa maría de los reyes': 2,
 'george plantagenet, 1st duke of bedford': 2,
 'rapid rail sdn bhd': 1,
 'lesser slave lake provincial park': 1,
 "st rumbold's cathedral": 2,
 'belcher channel formation': 3,
 'lesser slave river': 6,
 'shannon emery': 7,
 'yukon – koyukuk census area': 5,
 'noura khalifa al suwaidi': 4,
 'kohanabad rural district': 5,
 'first romanesque': 1,
 "mr moto's gamble": 2,
 'george h melford': 4,
 'philip ives dunne': 4,
 'rafe kovich and alison barrington kovich': 2,
 "the fools' hall of fame": 5,
 'mph group': 1,
 'mr boggs steps out': 5,
 'st mary high school': 11,
 'melissa moore': 1,
 'g marthandan': 3,
 'islamic revivalist': 1,
 'josé joaquim pimentel ribeiro': 2,
 'richard woodville, 1st': 1,
 'the model technical higher secondary school': 1,
 'alexander cyprius': 1,
 'la torre de los suplicios': 4,
 'the colvos store': 1,
 'television producer': 1,
 'efzar district': 6,
 'elvis aaron presley': 4,
 'film/television producer': 1,
 'director general of police in punjab': 3,
 'josé joaquim pimentel': 1,
 'dark mountain project': 2,
 'australian rules': 3,
 'mazraeh-ye ali hasan-e sofla': 3,
 'sedeh district': 6,
 'romantic comedy film': 3,
 'night at the movies': 2,
 'gertrude of saxony and bavaria': 8,
 'jack ryan conway': 4,
 'greene county': 5,
 'the white god': 6,
 'another side of bob dylan': 3,
 'victor schertzinger': 1,
 'john montagu douglas scott, 7th': 1,
 'karamana janardanan': 2,
 'hassan ii university': 3,
 'robert parrish': 1,
 'iglesia de santa maría': 7,
 'still-lifes': 1,
 'chahar taq-e bala': 2,
 'mazraeh-ye ali akbar khan': 4,
 'martha bulloch': 4,
 'pornographic film director': 2,
 'do you remember dolly bell?': 1,
 'william marshall (died 1540)': 1,
 'pahlavi dynasty': 1,
 'rukn al-din mubarak': 3,
 'salehabad district': 4,
 'andrew ii of hungary': 4,
 'group stage': 1,
 'sierra leonean army': 3,
 'sierra leone': 2,
 'university of chicago press': 1,
 'democratic party': 1,
 'new democratic party': 1,
 'ahmed bin rashid al maktoum': 6,
 'joaquim pimentel': 1,
 'joaquim viana pimentel': 4,
 'mr muggs steps out': 4,
 'oscar apfel': 1,
 'razavi khorasan province': 10,
 'compilation albums': 2,
 'american film director': 1,
 'six nations of the grand river territory, ontario': 1,
 'comedy-drama': 1,
 'list of films produced in uruguay': 2,
 'carbon-fibre composite': 1,
 'new kent county': 4,
 'pinal county, arizona': 1,
 'trinity college, cambridge': 1,
 'mr moto': 5,
 'fazle karim chowdhury': 3,
 'santa clara': 6,
 'mohamed abdelaziz tchikou': 5,
 'carbon-fibre': 1,
 'south australian government': 2,
 'norman rockwell code': 1,
 'shannon lee dawdy': 5,
 'tomás fernández ruiz': 5,
 'cranbrook school, sydney': 1,
 'south australian': 2,
 'first part': 2,
 'legislative assembly': 1,
 'the piano tuner': 3,
 "pier giorgio dall'acqua": 3,
 'musical film': 3,
 'michael latham powell': 10,
 'slave lake airport': 2,
 'conservative national caucus chair for her majesty ’s loyal opposition': 1,
 'mass cycles': 1,
 'george lamb hannah': 3,
 'sme ordnance': 2,
 'mph group malaysia': 2,
 'henry bryant': 4,
 'mazraeh-ye ali shafi': 4,
 'mission: impossible': 10,
 'university of wisconsin-madison': 3,
 'kamazan-e sofla rural district': 5,
 'films produced': 1,
 'shannon emery lee': 7,
 "women's 4 × 400 metres relay": 2,
 'a night at the movies': 7,
 'film and television director': 3,
 'rukn al-din mubarak khwaja': 3,
 'comedy drama film': 1,
 'eastern cape': 3,
 'j sasikumar': 1,
 'kohgiluyeh and boyer-ah province': 3,
 'trinidad perez': 2,
 'josephine roberto aka banig': 3,
 'bergen county, new jersey': 1,
 'the norman rockwell code': 4,
 'linda lee cadwell': 11,
 'collegiate gothic style': 1,
 'the international school of columbus': 1,
 'motion picture': 4,
 'another latin love song/miss world': 2,
 'colvos store': 5,
 'roman catholic diocese of springfield': 2,
 'sedeh rural district': 4,
 'greene county, new york': 1,
 'a list of films produced in japan': 1,
 'devarajan': 2,
 'crime drama film': 1,
 'rush dew holt sr': 2,
 'humboldt county': 9,
 '400 metres event': 1,
 'abd al-muttalib shaybah ibn hashim': 2,
 'krishnankoil venkadachalam': 6,
 'lake charles, louisiana': 3,
 'princess augusta of saxe-gotha': 6,
 'slave lake': 4,
 'richard of shrewsbury, 1': 2,
 'kohgiluyeh and boyer': 1,
 'model technical higher secondary school': 3,
 'silent film era': 1,
 'miklós jancs': 1,
 'prince henry, duke of cumberland': 7,
 'sasikumar': 4,
 'the cradle of humankind': 1,
 'drb-hicom': 3,
 'elvis presley': 2,
 'little man, what now?': 13,
 "st mary's high school, quetta": 3,
 "o'grady": 1,
 'frank vincent zappa': 5,
 'josephine roberto': 1,
 "children's books": 2,
 'star of india': 3,
 'santa clara university': 5,
 'alexander von zemlinsky': 4,
 'iglesia de santa maría de palacio': 2,
 'islamic revivalist movement in syria': 1,
 'six nations of the grand river territory': 2,
 'al-hasan ibn ali': 6,
 'mohamed abdelaziz': 12,
 'theme from" mission: impossible': 1,
 'nancy ann travis': 4,
 'theme music': 2,
 "women's 4 × 400 metres relay event": 1,
 'humphry davy': 2,
 'toma n socolescu': 2,
 'new kent county, virginia': 1,
 'chemung county': 5,
 'al-hasan ibn ali ibn abi talib': 6,
 'andrew ii': 2,
 'shocking asia': 4,
 'crime drama': 2,
 'sierra leonean president': 1,
 'st teresa high school': 2,
 'joaquim viana': 4,
 'australian rules football': 6,
 'six days of the condor': 7,
 'trade register': 6,
 "i'm a celebrity  get me out of here!": 1,
 'same english name': 1,
 'mirza ghulam ahmad of qadian': 5,
 'mohamed husseini': 3,
 'shocking asia ii': 3,
 'another latin love song/ miss world': 2,
 'sheikh mohammed bin rashid al maktoum': 8,
 'glen cove, long island, new york': 1,
 'tavistock clinic': 3,
 'kinga of poland (kunegunda)': 1,
 'naghan district': 5,
 'bertha wehnert-beckmann': 6,
 'white god': 6,
 "children's book": 2,
 'limerick senior inter-county team': 1,
 "giorgio dall'acqua": 2,
 'trade registers in several countries': 2,
 'canadian football': 3,
 'kuhenjan district': 5,
 'adventure film': 5,
 'a m b fazle karim chowdhury': 1,
 'one touch of venus': 2,
 'cheshmeh-ye hajji mohammad': 4,
 'lesser slave lake': 10,
 'the piano tuner has arrived': 7,
 'efzar rural district': 4,
 "dubai's ruling family": 1,
 'under electric clouds': 3,
 "girls' schools": 1,
 'jatt & juliet': 1,
 'lewis county, missouri': 2,
 'one touch of venus (film)': 1,
 'grand canyon': 1,
 'university of wisconsin': 1,
 'michel boisrond': 1,
 'eastern cape province': 6,
 'the legend of the condor heroes': 8,
 'dark mountain': 4,
 '400 metres': 3,
 'manuel i komnenos': 9,
 'sir humphry davy': 2,
 'noura khalifa': 1,
 'national gallery of australia': 3,
 'military intelligence': 1,
 'mazraeh-ye ali hasan': 1,
 'second part': 3,
 'mazraeh-ye ali faqihi': 3,
 'nancy travis': 1,
 'a b m fazle karim chowdhury': 1,
 'la torre de suso': 8,
 'jatt& juliet': 6,
 'a m fazle karim chowdhury': 1,
 '1934 film': 4,
 'first romanesque style': 1,
 "o' grady": 1,
 'manuel komnenos': 5,
 'william a berke': 7,
 'rhett akins jr': 1,
 'films produced in turkmenistan': 3,
 'chemung county, new york': 5,
 'zayed bin sultan al nahyan': 10,
 'comedy-drama film': 5,
 "i don't believe you (she acts like we never have met)": 3,
 'george iii of the united kingdom': 3,
 'australian rules footballer': 5,
 'ecumenical patriarch of constantinople': 2,
 'battle of wei river (濰水之戰)': 1,
 'kekuʻiapoiwa': 2,
 'oxford university cricket club': 2,
 'kohgiluyeh and boyer-ahmand province': 2,
 'trois-rivières': 1,
 'horror drama film': 1,
 "rumbold's cathedral": 1,
 'sarre anglo-saxon cemetery': 3,
 'siskiyou county': 3,
 'paul alain dutroux': 1,
 'lake charles': 9,
 'pinal county': 5,
 'rhett akins': 2,
 'royal veterinary academy of berlin': 1,
 "stefano dell'": 1,
 'st mother teresa high school': 4,
 'wyoming county': 4,
 'dubai ruling family': 2,
 'new york': 9,
 'roman catholic diocese of springfield in illinois': 2,
 'international school': 5,
 'muggs steps out': 2,
 'santa clara, california': 3,
 'morena clara (telenovela)': 4,
 'the star of india': 4,
 'bernard n nathanson': 3,
 'good old days': 2,
 'united states': 77,
 'kamazan-e vosta rural district': 4,
 'indie-rock': 2,
 'nila madhab': 1,
 'shannon lee sanderford': 6,
 'pornographic film': 3,
 'mazraeh-ye razavi': 8,
 'silent film': 19,
 'trinity college': 1,
 'santa maría de oseira': 2,
 'star trek into darkness': 2,
 'legend of the condor heroes': 5,
 'belcher channel': 2,
 'marthandan': 2,
 'mohammed bin rashid al maktou': 1,
 'los angeles, california': 7,
 'george plantagenet, 1st duke of': 1,
 'sorority house massacre ii': 7,
 'saturday night fever': 2,
 'salehabad rural district': 5,
 'fatima bint mubarak': 2,
 'morena clara': 4,
 'sex comedy': 1,
 'a list of films produced in turkmenistan': 1,
 'legislative assembly of ontario': 2,
 'krishnankoil venkadachalam mahadevan': 5,
 'humboldt county, california': 4,
 'eleni zaude gabre-madhin': 4,
 'it goes like this': 6,
 'three days of the condor': 1,
 'yukon – koyukuk census area, alaska': 1,
 'abstract artist': 2,
 'cradle of humankind': 2,
 'san francisco': 2,
 'mohamed mahmoud abdelaziz': 2,
 'the pony express': 1,
 'academy award for best picture': 3,
 'santa clara county': 5,
 'richard woodville, 1st earl rivers': 5,
 'suspense-thriller-drama film': 1,
 'thief has arrived': 1,
 'coming-of-age drama': 1,
 'sword stained with royal blood': 9,
 'prince henry, duke of cumberland and strathearn': 19,
 'george melford': 1,
 'hasan ibn ali': 7,
 "st antony's college, oxford": 2,
 'wyoming county, west virginia': 3,
 'william marshall': 6,
 'cranbrook school': 1,
 'dylan dayton': 1,
 'anne, duchess of cumberland and strathearn': 5,
 'time on my hands (song)': 1,
 'mazraeh-ye ali akbar hayati': 2,
 'mohamed husseini mohamed': 4,
 'coming-of-age film': 1,
 'oxford university': 1,
 'jack conway': 2,
 'nandi award for best director – telugu': 1,
 'rush dew holt': 2,
 'wood island light, maine': 1,
 'linda lee caldwell': 9,
 'bertha wehnert': 1,
 "st mary's high school": 11,
 'andrew murray': 5,
 'roman catholic church': 1,
 'razavi khorasan': 4,
 'alexander of cyprus': 3,
 'a list of films produced in uruguay': 1,
 'kinga of poland (cunegunda)': 2,
 'john montagu douglas scott, 7th duke of buccleuch': 8,
 'margown rural district': 5,
 'felix frankfurter': 1,
 'film produced in turkmenistan': 1,
 'sme ordnance sdn bhd': 1,
 'the good old days': 5,
 'shannon lee day': 3,
 'model technical higher secondary schools': 2,
 'the taking of pelham one two three': 2,
 'romantic comedy': 13,
 "st antony's college": 2,
 'michel jacques boisrond': 6,
 'knox county': 3,
 'shannon lee tweed simmons': 4,
 'conservative national caucus': 2,
 'mazraeh-ye ali reza baharlu': 4,
 'television director': 5,
 'roman catholic diocese of sioux falls': 3,
 'carbon-fiber': 1,
 'so it goes': 5,
 'time on my hands': 4,
 'nila madhab panda': 4,
 'princess augusta of saxe-gotha-altenburg': 4,
 'first group stage': 9,
 'sorority house massacre': 6,
 'grand canyon adventure': 4,
 'robert the bruce, king of scots': 4,
 'mohammed bin rashid al': 1,
 'giyan district': 6,
 'boggs steps out': 1,
 'sex comedy film': 1,
 'joaquim pimentel ribeiro': 1,
 'kohgiluyeh and boyer-ahmad province': 9,
 'trois-rivières, quebec': 1,
 'identity document': 5,
 'george lamb': 4,
 'hasan ibn hasan': 3,
 'king george iii of the united kingdom': 2,
 'calcasieu parish, louisiana': 2,
 'pahlavi dynasties': 1,
 "girls' school": 1,
 'films produced in japan': 4,
 'andrew murray craven': 2,
 'tomás fernández': 4,
 'mass cycle': 2,
 'roman catholic': 6,
 'giyan rural district': 4,
 'frank zappa': 3,
 'josefina tapias': 1,
 'film produced in uruguay': 1,
 'lady almeria carpenter': 3,
 'in my heart': 5,
 'theodore roosevelt, jr': 2,
 'and so it goes': 5,
 'silent era': 2,
 'san francisco, california': 2,
 'michael powell': 5,
 'the taking of pelham one two three the conversation': 1,
 'joséfina tapias': 1,
 'chahar taq bon': 5,
 'toma t socolescu': 9,
 "takeshi's castle": 1,
 'suspense thriller film': 1,
 'international school of koje': 4,
 'united arab emirates (uae)': 4,
 'kfar yedidia': 2,
 'international school of columbus': 3,
 'sheikh ahmed bin rashid al maktoum': 7,
 'georgina rose chapman': 6,
 'sierra leonean': 1,
 'mission: impossible iii': 9,
 'a thief has arrived': 6,
 'wood island light': 3,
 'director general of police': 3,
 'mazraeh-ye rezavi': 6,
 'motion picture actor': 1,
 'shannon lee tweed': 5,
 'mohammed bin rashid al maktoum': 43,
 '1934 film of the same title': 1,
 'chahar taq': 25,
 'identity documents': 1,
 'me or me': 3,
 'american director': 2,
 'cedar park, texas': 2,
 'g devarajan': 3,
 'sarre anglo-saxon': 1,
 'mazraeh-ye jonubi rural district': 5,
 'henry bryant bigelow': 3,
 'melissa ann moore': 3,
 'ecumenical patriarch': 2,
 'georgina rose': 3,
 'adventure drama film': 1,
 'anne, duchess of cumberland': 4,
 'national gallery of australia (canberra)': 1,
 'nandi award for best director': 3,
 'royal veterinary academy': 1,
 'shannon lee': 8,
 'film/television director': 1,
 "i don't believe you (she acts like we never have met": 2,
 'the first part': 2,
 'collegiate gothic': 1,
 'fatima bint mubarak al ketbi': 4,
 'hassan ii university in casablanca': 2,
 'last days of the condor': 3,
 'kohgiluyeh and boyer-ahmir province': 1,
 'bomba and the jungle girl': 5,
 'still-life': 2,
 'gus green van sant': 1,
 'almeria carpenter': 1,
 'the theme music': 1,
 'mazraeh-ye ali sirjani': 3,
 'another latin love song': 2,
 'sierra leone president': 1,
 'bergen county': 3,
 'my heart': 2,
 'kekuʻiapoiwa ii': 3,
 'william marshall tredway': 4,
 'science fiction': 2,
 'pony express': 9,
 'bernard nathanson': 2,
 'university of wisconsin – madison': 3,
 'victor l schertzinger': 8,
 'robert r parrish': 5,
 'abstract art': 3,
 'kuhenjan rural district': 4,
 'cheshmeh-ye hajji soleyman': 4,
 'why did i get married?': 2,
 'richard of shrewsbury, 1st duke of york': 3,
 "stefano dell' arzere": 1,
 'william berke': 4,
 'sheikha latifa': 4,
 'canadian football league': 2,
 'it goes like it goes': 2,
 'oscar c apfel': 5,
 "fools' hall of fame": 2,
 'cedar park': 2,
 'tavistock clinic and institute': 5,
 'sheika latifa': 4,
 'charles sallier': 4,
 'miklós jancs ó': 1}

In [285]:
max(grupos[0], key=len)

'1934 film of the same title'

In [287]:
fusion_final = {}
for grupo in grupos:
    
    nodo_principal = max(grupo, key = len)
    for ent in grupo:
        if grados[ent] > grados[nodo_principal]:
            nodo_principal = ent
    fusion_final[nodo_principal] = [sec for sec in grupo if sec != nodo_principal]

In [288]:
fusion_final

{'1934 film': ['1934 film of the same title'],
 '400 metres': ['400 metres event'],
 'abd al-muttalib shaybah ibn hashim': ['abd al-muttalib shaybah'],
 'abstract art': ['abstract artist'],
 'academy award for best picture': ['academy award for best director'],
 'adventure film': ['adventure drama film'],
 'al-hasan ibn ali ibn abi talib': ['al-hasan ibn ali'],
 'alexander of cyprus': ['alexander cyprius'],
 'alexander von zemlinsky': ['alexander zemlinsky'],
 'american director': ['american film director'],
 'andrew ii of hungary': ['andrew ii'],
 'andrew murray': ['andrew murray craven'],
 'anne, duchess of cumberland and strathearn': ['anne, duchess of cumberland'],
 'another latin love song/ miss world': ['another latin love song/miss world',
  'another latin love song'],
 'bob dylan': ['another side of bob dylan'],
 'archibald bulloch': ['archibald bulloch roosevelt',
  'archibald bulloch roosevelt jr'],
 'australian rules football': ['australian rules',
  'australian rules footballer'],
 'battle of wei river (濰水之戰)': ['battle of wei river'],
 'belcher channel formation': ['belcher channel'],
 'bergen county': ['bergen county, new jersey'],
 'bernard n nathanson': ['bernard nathanson'],
 'bertha wehnert-beckmann': ['bertha wehnert'],
 'bill evans trio': ['bill evans'],
 'bomba and the jungle girl': ['bomba, the jungle boy'],
 'calcasieu parish': ['calcasieu parish, louisiana'],
 'canadian football': ['canadian football league'],
 'carbon-fibre composite': ['carbon-fiber', 'carbon-fibre'],
 'cedar park, texas': ['cedar park'],
 'chahar taq': ['chahar taq bon', 'chahar taq-e bala'],
 'charles anselm sallier': ['charles sallier'],
 'chemung county, new york': ['chemung county'],
 'cheshmeh-ye hajji mohammad': ['cheshmeh-ye ali mohammad',
  'cheshmeh-ye hajji soleyman'],
 "children's books": ["children's book"],
 'collegiate gothic style': ['collegiate gothic'],
 'comedy-drama film': ['comedy-drama', 'comedy drama film'],
 'coming-of-age drama': ['coming-of-age film'],
 'compilation albums': ['compilation album'],
 'conservative national caucus': ['conservative national caucus chair',
  'conservative national caucus chair for her majesty ’s loyal opposition'],
 'cranbrook school, sydney': ['cranbrook school'],
 'crime drama': ['crime drama film'],
 'dark mountain': ['dark mountain project'],
 'dinesh baboo': ['dinesh babu'],
 'director general of police in punjab': ['director general of police'],
 'do you remember dolly bell?': ['do you remember dolly bell'],
 'drb-hicom': ['drb-hicom berhad'],
 'dubai ruling family': ["dubai's ruling family"],
 'eastern cape province': ['eastern cape'],
 'ecumenical patriarch of constantinople': ['ecumenical patriarch'],
 'edward iv of england': ['edward iv, king of england'],
 'efzar district': ['efzar rural district'],
 'eleni zaude gabre-madhin': ['eleni zaude gabre'],
 'elvis aaron presley': ['elvis presley'],
 'fatima bint mubarak al ketbi': ['fatima bint mubarak'],
 'fazle karim chowdhury': ['a b m fazle karim chowdhury',
  'a m b fazle karim chowdhury',
  'a b fazle karim chowdhury',
  'a m fazle karim chowdhury',
  'abm fazle karim chowdhury'],
 'felix frankfurter professor of law': ['felix frankfurter'],
 'films produced in turkmenistan': ['film produced in turkmenistan'],
 'television director': ['film and television director',
  'film/television director'],
 'film/television producer': ['television producer'],
 'films produced in japan': ['films produced',
  'a list of films produced in japan'],
 'first romanesque style': ['first romanesque'],
 'frank vincent zappa': ['frank zappa'],
 'g devarajan': ['devarajan'],
 'george lamb': ['george lamb hannah'],
 'george h melford': ['george melford'],
 'george plantagenet, 1st duke of bedford': ['george plantagenet, 1st duke of'],
 'georgina rose chapman': ['georgina rose'],
 'gertrude of saxony and bavaria': ['gertrude of saxony'],
 "girls' schools": ["girls' school"],
 'giyan district': ['giyan rural district'],
 'glen cove, long island, new york': ['glen cove, long island'],
 'grand canyon adventure': ['grand canyon'],
 'greene county': ['greene county, new york'],
 'first group stage': ['group stage'],
 'gus green van sant jr': ['gus green van sant'],
 'hasan ibn ali': ['hasan ibn hasan'],
 'hassan ii university': ['hassan ii university in casablanca'],
 'henry bryant': ['henry bryant bigelow'],
 'horror drama film': ['horror drama'],
 'humboldt county': ['humboldt county, california'],
 "i don't believe you (she acts like we never have met)": ["i don't believe you (she acts like we never have met"],
 "i'm a celebrity  get me out of here!": ["i'm a celebrity get me out of here!"],
 'identity document': ['identity documents'],
 'iglesia de santa maría': ['iglesia de santa maría de los reyes',
  'iglesia de santa maría de palacio'],
 'indie rock': ['indie-rock'],
 'international school': ['international school of koje'],
 'islamic revivalist movement in syria': ['islamic revivalist'],
 'it goes like this': ['it goes like it goes'],
 'jack ryan conway': ['jack conway'],
 'jatt& juliet': ['jatt & juliet'],
 'john montagu douglas scott, 7th duke of buccleuch': ['john montagu douglas scott, 7th'],
 'josephine roberto aka banig': ['josephine roberto'],
 'joaquim viana pimentel': ['joaquim pimentel ribeiro',
  'joaquim pimentel',
  'josé joaquim pimentel ribeiro',
  'joaquim viana',
  'josé joaquim pimentel'],
 'josefina tapias': ['joséfina tapias'],
 'kamazan-e sofla rural district': ['kamazan-e vosta rural district'],
 'karamana janardanan nair': ['karamana janardanan'],
 'kekuʻiapoiwa ii': ['kekuʻiapoiwa'],
 'kfar yedidia': ['kfar yedidia, israel'],
 'george iii of the united kingdom': ['king george iii of the united kingdom'],
 'kinga of poland': ['kinga of poland (kunegunda)',
  'kinga of poland (cunegunda)'],
 'knox county': ['knox county, kentucky'],
 'kohanabad rural district': ['kohanabad district'],
 'kohgiluyeh and boyer-ahmad province': ['kohgiluyeh and boyer',
  'kohgiluyeh and boyer-ahmand province',
  'kohgiluyeh and boyer-ah province',
  'kohgiluyeh and boyer-ahmir province'],
 'krishnankoil venkadachalam': ['krishnankoil venkadachalam mahadevan'],
 'kuhenjan district': ['kuhenjan rural district'],
 'la torre de suso': ['la torre de los suplicios'],
 'lady almeria carpenter': ['almeria carpenter'],
 'lake charles': ['lake charles, louisiana'],
 'legislative assembly of ontario': ['legislative assembly'],
 'lesser slave lake': ['lesser slave lake provincial park',
  'lesser slave river'],
 'lewis county': ['lewis county, missouri'],
 'limerick senior inter-county team': ['cork senior inter-county team'],
 'linda lee cadwell': ['linda lee caldwell'],
 'list of films produced in turkmenistan': ['a list of films produced in turkmenistan'],
 'films produced in uruguay': ['film produced in uruguay',
  'list of films produced in uruguay',
  'a list of films produced in uruguay'],
 'little man, what now?': ['little man'],
 'los angeles': ['los angeles, california'],
 'manuel i komnenos': ['manuel komnenos'],
 'margown district': ['margown rural district'],
 'martha bulloch roosevelt': ['martha bulloch'],
 'g marthandan': ['marthandan'],
 'mass cycle': ['mass cycles'],
 'mazraeh-ye ali': ['mazraeh-ye ali shafi',
  'mazraeh-ye ali sirjani',
  'mazraeh-ye ali hasan-e sofla',
  'mazraeh-ye ali akbar hayati',
  'mazraeh-ye ali hasan',
  'mazraeh-ye ali faqihi',
  'mazraeh-ye ali akbar khan',
  'mazraeh-ye ali reza baharlu'],
 'mazraeh-ye razavi': ['mazraeh-ye rezavi'],
 'mazraeh-ye jonubi rural district': ['mazraeh-ye shomali rural district'],
 'me': ['me or me'],
 'melissa ann moore': ['melissa moore'],
 'michael latham powell': ['michael powell'],
 'michel jacques boisrond': ['michel boisrond'],
 'miklós jancs ó': ['miklós jancs'],
 'military intelligence organization': ['military intelligence'],
 'mirza ghulam ahmad of qadian': ['mirza ghulam ahmad'],
 'mohamed husseini mohamed': ['mohamed husseini'],
 'mohamed abdelaziz': ['mohamed mahmoud abdelaziz',
  'mohamed abdelaziz tchikou'],
 'morena clara (telenovela)': ['morena clara'],
 'motion picture': ['motion picture actor', 'motion picture director'],
 'mph group malaysia': ['mph group'],
 'mr moto': ["mr moto's gamble"],
 'mr boggs steps out': ['mr muggs steps out',
  'muggs steps out',
  'boggs steps out'],
 'musical film': ['musical drama film'],
 'always in my heart': ['my heart', 'in my heart'],
 'naghan district': ['naghan rural district'],
 'nancy ann travis': ['nancy travis'],
 'nandi award for best director': ['nandi award for best director – telugu'],
 'national gallery of australia': ['national gallery of australia (canberra)'],
 'new democratic party': ['democratic party'],
 'new kent county': ['new kent county, virginia'],
 'new york city': ['new york'],
 'a night at the movies': ['night at the movies'],
 'nila madhab panda': ['nila madhab'],
 'noura khalifa al suwaidi': ['noura khalifa'],
 "o' grady": ["o'grady"],
 'odrysian kingdom': ['odrysian kingdom of thrace'],
 'one touch of venus': ['one touch of venus (film)'],
 'oscar c apfel': ['oscar apfel'],
 'oxford university cricket club': ['oxford university'],
 'pahlavi dynasties': ['pahlavi dynasty'],
 'marc paul alain dutroux': ['paul alain dutroux'],
 'peer-reviewed': ['peer-review'],
 'philip ives dunne': ['philip dunne'],
 "pier giorgio dall'acqua": ["giorgio dall'acqua"],
 'pinal county': ['pinal county, arizona'],
 'pornographic film': ['pornographic film director'],
 'prince henry, duke of cumberland and strathearn': ['prince henry, duke of cumberland'],
 'princess augusta of saxe-gotha': ['princess augusta of saxe-gotha-altenburg'],
 'rafe kovich and alison barrington kovich': ['rafe kovich and alison barrington'],
 'rapid rail': ['rapid rail sdn bhd'],
 'razavi khorasan province': ['razavi khorasan'],
 'rhett akins': ['rhett akins jr'],
 'richard of shrewsbury, 1st duke of york': ['richard of shrewsbury, 1'],
 'richard woodville, 1st earl rivers': ['richard woodville, 1st'],
 'robert r parrish': ['robert parrish'],
 'robert the bruce, king of scots': ['robert the bruce'],
 'roman catholic': ['roman catholic church'],
 'roman catholic diocese of sioux falls': ['roman catholic diocese of springfield',
  'roman catholic diocese of springfield in illinois'],
 'romantic comedy': ['romantic comedy film'],
 'royal oak, michigan': ['royal oak'],
 'royal veterinary academy of berlin': ['royal veterinary academy'],
 'rukn al-din mubarak khwaja': ['rukn al-din mubarak'],
 'rush dew holt sr': ['rush dew holt'],
 'salehabad rural district': ['salehabad district'],
 'english name': ['same english name'],
 'san francisco, california': ['san francisco'],
 'santa clara': ['santa clara county, california',
  'santa clara university',
  'santa clara, california',
  'santa clara county'],
 'santa maría': ['santa maría de oseira'],
 'sarre anglo-saxon cemetery': ['sarre anglo-saxon'],
 'sasikumar': ['j sasikumar'],
 'saturday night at the movies': ['saturday night fever'],
 'science fiction': ['science fiction film'],
 'scr corporation sdn bhd': ['scr corporation'],
 'sedeh district': ['sedeh rural district'],
 'sex comedy film': ['sex comedy'],
 'shannon lee': ['shannon lee sanderford',
  'shannon lee dawdy',
  'shannon lee tweed',
  'shannon emery',
  'shannon lee day',
  'shannon emery lee',
  'shannon lee tweed simmons'],
 'sheikha latifa': ['sheika latifa'],
 'sheikh ahmed bin rashid al maktoum': ['ahmed bin rashid al maktoum'],
 'mohammed bin rashid al maktoum': ['mohammed bin rashid al',
  'sheikh mohammed bin rashid al maktoum',
  'mohammed bin rashid al maktou'],
 'sherlock holmes': ['sherlock holmes films'],
 'shocking asia': ['shocking asia ii'],
 'sierra leone': ['sierra leone president'],
 'sierra leonean army': ['sierra leonean president', 'sierra leonean'],
 'silent film': ['silent film era', 'silent era'],
 'sir humphry davy': ['humphry davy'],
 'siskiyou county': ['siskiyou county, california'],
 'six nations of the grand river territory': ['six nations of the grand river territory, ontario'],
 'sky dylan dayton': ['dylan dayton'],
 'slave lake': ['slave lake airport'],
 'sme ordnance': ['sme ordnance sdn bhd'],
 'and so it goes': ['so it goes'],
 'sorority house massacre ii': ['sorority house massacre'],
 'south australian government': ['south australian'],
 "st antony's college, oxford": ["st antony's college"],
 "st mary's high school": ['st mary high school',
  "st mary's high school, quetta"],
 "st rumbold's cathedral": ["rumbold's cathedral"],
 'st mother teresa high school': ['st teresa high school'],
 'star trek': ['star trek into darkness'],
 "stefano dell' arzere": ["stefano dell'"],
 'still-life': ['still-lifes'],
 'suspense-thriller-drama film': ['suspense thriller film'],
 "takeshi's castle wwe raw": ["takeshi's castle"],
 'tavistock clinic and institute': ['tavistock clinic'],
 'colvos store': ['the colvos store'],
 'cradle of humankind': ['the cradle of humankind'],
 'the first part': ['first part'],
 "the fools' hall of fame": ["fools' hall of fame"],
 'the good old days': ['good old days'],
 'international school of columbus': ['the international school of columbus'],
 'the legend of the condor heroes': ['legend of the condor heroes'],
 'model technical higher secondary school': ['model technical higher secondary schools',
  'the model technical higher secondary school'],
 'the norman rockwell code': ['norman rockwell code'],
 'the piano tuner has arrived': ['the piano tuner', 'the piano tuner has'],
 'pony express': ['the pony express'],
 'second part': ['the second part'],
 'the star of india': ['star of india'],
 'sword stained with royal blood': ['the sword stained with royal blood'],
 'the taking of pelham one two three': ['the taking of pelham one two three the conversation'],
 'mission: impossible': ['theme from" mission: impossible',
  'mission: impossible iii'],
 'theme music': ['the theme music'],
 'theodore roosevelt': ['theodore roosevelt, jr'],
 'a thief has arrived': ['thief has arrived'],
 'six days of the condor': ['three days of the condor',
  'last days of the condor'],
 'time on my hands': ['time on my hands (song)'],
 'toma t socolescu': ['toma n socolescu'],
 'tomás fernández ruiz': ['tomás fernández'],
 'trade register': ['trade registers in several countries', 'trade registers'],
 'trinidad perez tecson': ['trinidad perez'],
 'trinity college, cambridge': ['trinity college'],
 'trois-rivières, quebec': ['trois-rivières'],
 'under electric clouds': ['electric clouds'],
 'united arab emirates': ['united arab emirates (uae)',
  'united arab emirates (uae'],
 'united states': ['united states senator'],
 'university of chicago': ['university of chicago press'],
 'university of wisconsin – madison': ['university of wisconsin-madison',
  'university of wisconsin'],
 'victor l schertzinger': ['victor schertzinger'],
 'augustus barratt': ['w augustus barratt'],
 'when father was away on business': ['when father was away on businessunderground'],
 'the white god': ['white god'],
 'why did i get married too?': ['why did i get married?',
  'why did i get married'],
 'william a berke': ['william berke'],
 'william marshall (died 1540?)': ['william marshall (died 1540)'],
 'william marshall': ['william marshall tredway'],
 "women's 4 × 400 metres relay": ["women's 4 × 400 metres relay event"],
 'wood island light': ['wood island light, maine'],
 'wyoming county': ['wyoming county, west virginia'],
 'the young philadelphians': ['young philadelphians'],
 'yukon – koyukuk census area': ['yukon – koyukuk census area, alaska'],
 'zayed bin sultan al nahyan': ['sheikh zayed bin sultan al nahyan']}

# Fusion en Neo4j

A neo4j no se le puede pasar directamente los diccionarios donde la key es el noso principal. Hay que indicarle con nombre. Por ejempo [{"principal":nodo_princ, "secundarios":lista_secundarios}]

In [292]:
datos_para_neo4j = [
    {
        "nodo_principal": grupo,
        "nodos_a_fusionar": fusion_final[grupo]
    }
    for grupo in fusion_final # La lista generada en el paso anterior
]

In [307]:
datos_para_neo4j

[{'nodo_principal': '1934 film',
  'nodos_a_fusionar': ['1934 film of the same title']},
 {'nodo_principal': '400 metres', 'nodos_a_fusionar': ['400 metres event']},
 {'nodo_principal': 'abd al-muttalib shaybah ibn hashim',
  'nodos_a_fusionar': ['abd al-muttalib shaybah']},
 {'nodo_principal': 'abstract art', 'nodos_a_fusionar': ['abstract artist']},
 {'nodo_principal': 'academy award for best picture',
  'nodos_a_fusionar': ['academy award for best director']},
 {'nodo_principal': 'adventure film',
  'nodos_a_fusionar': ['adventure drama film']},
 {'nodo_principal': 'al-hasan ibn ali ibn abi talib',
  'nodos_a_fusionar': ['al-hasan ibn ali']},
 {'nodo_principal': 'alexander of cyprus',
  'nodos_a_fusionar': ['alexander cyprius']},
 {'nodo_principal': 'alexander von zemlinsky',
  'nodos_a_fusionar': ['alexander zemlinsky']},
 {'nodo_principal': 'american director',
  'nodos_a_fusionar': ['american film director']},
 {'nodo_principal': 'andrew ii of hungary', 'nodos_a_fusionar': ['andrew ii']},
 {'nodo_principal': 'andrew murray',
  'nodos_a_fusionar': ['andrew murray craven']},
 {'nodo_principal': 'anne, duchess of cumberland and strathearn',
  'nodos_a_fusionar': ['anne, duchess of cumberland']},
 {'nodo_principal': 'another latin love song/ miss world',
  'nodos_a_fusionar': ['another latin love song/miss world',
   'another latin love song']},
 {'nodo_principal': 'bob dylan',
  'nodos_a_fusionar': ['another side of bob dylan']},
 {'nodo_principal': 'archibald bulloch',
  'nodos_a_fusionar': ['archibald bulloch roosevelt',
   'archibald bulloch roosevelt jr']},
 {'nodo_principal': 'australian rules football',
  'nodos_a_fusionar': ['australian rules', 'australian rules footballer']},
 {'nodo_principal': 'battle of wei river (濰水之戰)',
  'nodos_a_fusionar': ['battle of wei river']},
 {'nodo_principal': 'belcher channel formation',
  'nodos_a_fusionar': ['belcher channel']},
 {'nodo_principal': 'bergen county',
  'nodos_a_fusionar': ['bergen county, new jersey']},
 {'nodo_principal': 'bernard n nathanson',
  'nodos_a_fusionar': ['bernard nathanson']},
 {'nodo_principal': 'bertha wehnert-beckmann',
  'nodos_a_fusionar': ['bertha wehnert']},
 {'nodo_principal': 'bill evans trio', 'nodos_a_fusionar': ['bill evans']},
 {'nodo_principal': 'bomba and the jungle girl',
  'nodos_a_fusionar': ['bomba, the jungle boy']},
 {'nodo_principal': 'calcasieu parish',
  'nodos_a_fusionar': ['calcasieu parish, louisiana']},
 {'nodo_principal': 'canadian football',
  'nodos_a_fusionar': ['canadian football league']},
 {'nodo_principal': 'carbon-fibre composite',
  'nodos_a_fusionar': ['carbon-fiber', 'carbon-fibre']},
 {'nodo_principal': 'cedar park, texas', 'nodos_a_fusionar': ['cedar park']},
 {'nodo_principal': 'chahar taq',
  'nodos_a_fusionar': ['chahar taq bon', 'chahar taq-e bala']},
 {'nodo_principal': 'charles anselm sallier',
  'nodos_a_fusionar': ['charles sallier']},
 {'nodo_principal': 'chemung county, new york',
  'nodos_a_fusionar': ['chemung county']},
 {'nodo_principal': 'cheshmeh-ye hajji mohammad',
  'nodos_a_fusionar': ['cheshmeh-ye ali mohammad',
   'cheshmeh-ye hajji soleyman']},
 {'nodo_principal': "children's books",
  'nodos_a_fusionar': ["children's book"]},
 {'nodo_principal': 'collegiate gothic style',
  'nodos_a_fusionar': ['collegiate gothic']},
 {'nodo_principal': 'comedy-drama film',
  'nodos_a_fusionar': ['comedy-drama', 'comedy drama film']},
 {'nodo_principal': 'coming-of-age drama',
  'nodos_a_fusionar': ['coming-of-age film']},
 {'nodo_principal': 'compilation albums',
  'nodos_a_fusionar': ['compilation album']},
 {'nodo_principal': 'conservative national caucus',
  'nodos_a_fusionar': ['conservative national caucus chair',
   'conservative national caucus chair for her majesty ’s loyal opposition']},
 {'nodo_principal': 'cranbrook school, sydney',
  'nodos_a_fusionar': ['cranbrook school']},
 {'nodo_principal': 'crime drama', 'nodos_a_fusionar': ['crime drama film']},
 {'nodo_principal': 'dark mountain',
  'nodos_a_fusionar': ['dark mountain project']},
 {'nodo_principal': 'dinesh baboo', 'nodos_a_fusionar': ['dinesh babu']},
 {'nodo_principal': 'director general of police in punjab',
  'nodos_a_fusionar': ['director general of police']},
 {'nodo_principal': 'do you remember dolly bell?',
  'nodos_a_fusionar': ['do you remember dolly bell']},
 {'nodo_principal': 'drb-hicom', 'nodos_a_fusionar': ['drb-hicom berhad']},
 {'nodo_principal': 'dubai ruling family',
  'nodos_a_fusionar': ["dubai's ruling family"]},
 {'nodo_principal': 'eastern cape province',
  'nodos_a_fusionar': ['eastern cape']},
 {'nodo_principal': 'ecumenical patriarch of constantinople',
  'nodos_a_fusionar': ['ecumenical patriarch']},
 {'nodo_principal': 'edward iv of england',
  'nodos_a_fusionar': ['edward iv, king of england']},
 {'nodo_principal': 'efzar district',
  'nodos_a_fusionar': ['efzar rural district']},
 {'nodo_principal': 'eleni zaude gabre-madhin',
  'nodos_a_fusionar': ['eleni zaude gabre']},
 {'nodo_principal': 'elvis aaron presley',
  'nodos_a_fusionar': ['elvis presley']},
 {'nodo_principal': 'fatima bint mubarak al ketbi',
  'nodos_a_fusionar': ['fatima bint mubarak']},
 {'nodo_principal': 'fazle karim chowdhury',
  'nodos_a_fusionar': ['a b m fazle karim chowdhury',
   'a m b fazle karim chowdhury',
   'a b fazle karim chowdhury',
   'a m fazle karim chowdhury',
   'abm fazle karim chowdhury']},
 {'nodo_principal': 'felix frankfurter professor of law',
  'nodos_a_fusionar': ['felix frankfurter']},
 {'nodo_principal': 'films produced in turkmenistan',
  'nodos_a_fusionar': ['film produced in turkmenistan']},
 {'nodo_principal': 'television director',
  'nodos_a_fusionar': ['film and television director',
   'film/television director']},
 {'nodo_principal': 'film/television producer',
  'nodos_a_fusionar': ['television producer']},
 {'nodo_principal': 'films produced in japan',
  'nodos_a_fusionar': ['films produced', 'a list of films produced in japan']},
 {'nodo_principal': 'first romanesque style',
  'nodos_a_fusionar': ['first romanesque']},
 {'nodo_principal': 'frank vincent zappa',
  'nodos_a_fusionar': ['frank zappa']},
 {'nodo_principal': 'g devarajan', 'nodos_a_fusionar': ['devarajan']},
 {'nodo_principal': 'george lamb', 'nodos_a_fusionar': ['george lamb hannah']},
 {'nodo_principal': 'george h melford',
  'nodos_a_fusionar': ['george melford']},
 {'nodo_principal': 'george plantagenet, 1st duke of bedford',
  'nodos_a_fusionar': ['george plantagenet, 1st duke of']},
 {'nodo_principal': 'georgina rose chapman',
  'nodos_a_fusionar': ['georgina rose']},
 {'nodo_principal': 'gertrude of saxony and bavaria',
  'nodos_a_fusionar': ['gertrude of saxony']},
 {'nodo_principal': "girls' schools", 'nodos_a_fusionar': ["girls' school"]},
 {'nodo_principal': 'giyan district',
  'nodos_a_fusionar': ['giyan rural district']},
 {'nodo_principal': 'glen cove, long island, new york',
  'nodos_a_fusionar': ['glen cove, long island']},
 {'nodo_principal': 'grand canyon adventure',
  'nodos_a_fusionar': ['grand canyon']},
 {'nodo_principal': 'greene county',
  'nodos_a_fusionar': ['greene county, new york']},
 {'nodo_principal': 'first group stage', 'nodos_a_fusionar': ['group stage']},
 {'nodo_principal': 'gus green van sant jr',
  'nodos_a_fusionar': ['gus green van sant']},
 {'nodo_principal': 'hasan ibn ali', 'nodos_a_fusionar': ['hasan ibn hasan']},
 {'nodo_principal': 'hassan ii university',
  'nodos_a_fusionar': ['hassan ii university in casablanca']},
 {'nodo_principal': 'henry bryant',
  'nodos_a_fusionar': ['henry bryant bigelow']},
 {'nodo_principal': 'horror drama film', 'nodos_a_fusionar': ['horror drama']},
 {'nodo_principal': 'humboldt county',
  'nodos_a_fusionar': ['humboldt county, california']},
 {'nodo_principal': "i don't believe you (she acts like we never have met)",
  'nodos_a_fusionar': ["i don't believe you (she acts like we never have met"]},
 {'nodo_principal': "i'm a celebrity  get me out of here!",
  'nodos_a_fusionar': ["i'm a celebrity get me out of here!"]},
 {'nodo_principal': 'identity document',
  'nodos_a_fusionar': ['identity documents']},
 {'nodo_principal': 'iglesia de santa maría',
  'nodos_a_fusionar': ['iglesia de santa maría de los reyes',
   'iglesia de santa maría de palacio']},
 {'nodo_principal': 'indie rock', 'nodos_a_fusionar': ['indie-rock']},
 {'nodo_principal': 'international school',
  'nodos_a_fusionar': ['international school of koje']},
 {'nodo_principal': 'islamic revivalist movement in syria',
  'nodos_a_fusionar': ['islamic revivalist']},
 {'nodo_principal': 'it goes like this',
  'nodos_a_fusionar': ['it goes like it goes']},
 {'nodo_principal': 'jack ryan conway', 'nodos_a_fusionar': ['jack conway']},
 {'nodo_principal': 'jatt& juliet', 'nodos_a_fusionar': ['jatt & juliet']},
 {'nodo_principal': 'john montagu douglas scott, 7th duke of buccleuch',
  'nodos_a_fusionar': ['john montagu douglas scott, 7th']},
 {'nodo_principal': 'josephine roberto aka banig',
  'nodos_a_fusionar': ['josephine roberto']},
 {'nodo_principal': 'joaquim viana pimentel',
  'nodos_a_fusionar': ['joaquim pimentel ribeiro',
   'joaquim pimentel',
   'josé joaquim pimentel ribeiro',
   'joaquim viana',
   'josé joaquim pimentel']},
 {'nodo_principal': 'josefina tapias',
  'nodos_a_fusionar': ['joséfina tapias']},
 {'nodo_principal': 'kamazan-e sofla rural district',
  'nodos_a_fusionar': ['kamazan-e vosta rural district']},
 {'nodo_principal': 'karamana janardanan nair',
  'nodos_a_fusionar': ['karamana janardanan']},
 {'nodo_principal': 'kekuʻiapoiwa ii', 'nodos_a_fusionar': ['kekuʻiapoiwa']},
 {'nodo_principal': 'kfar yedidia',
  'nodos_a_fusionar': ['kfar yedidia, israel']},
 {'nodo_principal': 'george iii of the united kingdom',
  'nodos_a_fusionar': ['king george iii of the united kingdom']},
 {'nodo_principal': 'kinga of poland',
  'nodos_a_fusionar': ['kinga of poland (kunegunda)',
   'kinga of poland (cunegunda)']},
 {'nodo_principal': 'knox county',
  'nodos_a_fusionar': ['knox county, kentucky']},
 {'nodo_principal': 'kohanabad rural district',
  'nodos_a_fusionar': ['kohanabad district']},
 {'nodo_principal': 'kohgiluyeh and boyer-ahmad province',
  'nodos_a_fusionar': ['kohgiluyeh and boyer',
   'kohgiluyeh and boyer-ahmand province',
   'kohgiluyeh and boyer-ah province',
   'kohgiluyeh and boyer-ahmir province']},
 {'nodo_principal': 'krishnankoil venkadachalam',
  'nodos_a_fusionar': ['krishnankoil venkadachalam mahadevan']},
 {'nodo_principal': 'kuhenjan district',
  'nodos_a_fusionar': ['kuhenjan rural district']},
 {'nodo_principal': 'la torre de suso',
  'nodos_a_fusionar': ['la torre de los suplicios']},
 {'nodo_principal': 'lady almeria carpenter',
  'nodos_a_fusionar': ['almeria carpenter']},
 {'nodo_principal': 'lake charles',
  'nodos_a_fusionar': ['lake charles, louisiana']},
 {'nodo_principal': 'legislative assembly of ontario',
  'nodos_a_fusionar': ['legislative assembly']},
 {'nodo_principal': 'lesser slave lake',
  'nodos_a_fusionar': ['lesser slave lake provincial park',
   'lesser slave river']},
 {'nodo_principal': 'lewis county',
  'nodos_a_fusionar': ['lewis county, missouri']},
 {'nodo_principal': 'limerick senior inter-county team',
  'nodos_a_fusionar': ['cork senior inter-county team']},
 {'nodo_principal': 'linda lee cadwell',
  'nodos_a_fusionar': ['linda lee caldwell']},
 {'nodo_principal': 'list of films produced in turkmenistan',
  'nodos_a_fusionar': ['a list of films produced in turkmenistan']},
 {'nodo_principal': 'films produced in uruguay',
  'nodos_a_fusionar': ['film produced in uruguay',
   'list of films produced in uruguay',
   'a list of films produced in uruguay']},
 {'nodo_principal': 'little man, what now?',
  'nodos_a_fusionar': ['little man']},
 {'nodo_principal': 'los angeles',
  'nodos_a_fusionar': ['los angeles, california']},
 {'nodo_principal': 'manuel i komnenos',
  'nodos_a_fusionar': ['manuel komnenos']},
 {'nodo_principal': 'margown district',
  'nodos_a_fusionar': ['margown rural district']},
 {'nodo_principal': 'martha bulloch roosevelt',
  'nodos_a_fusionar': ['martha bulloch']},
 {'nodo_principal': 'g marthandan', 'nodos_a_fusionar': ['marthandan']},
 {'nodo_principal': 'mass cycle', 'nodos_a_fusionar': ['mass cycles']},
 {'nodo_principal': 'mazraeh-ye ali',
  'nodos_a_fusionar': ['mazraeh-ye ali shafi',
   'mazraeh-ye ali sirjani',
   'mazraeh-ye ali hasan-e sofla',
   'mazraeh-ye ali akbar hayati',
   'mazraeh-ye ali hasan',
   'mazraeh-ye ali faqihi',
   'mazraeh-ye ali akbar khan',
   'mazraeh-ye ali reza baharlu']},
 {'nodo_principal': 'mazraeh-ye razavi',
  'nodos_a_fusionar': ['mazraeh-ye rezavi']},
 {'nodo_principal': 'mazraeh-ye jonubi rural district',
  'nodos_a_fusionar': ['mazraeh-ye shomali rural district']},
 {'nodo_principal': 'me', 'nodos_a_fusionar': ['me or me']},
 {'nodo_principal': 'melissa ann moore',
  'nodos_a_fusionar': ['melissa moore']},
 {'nodo_principal': 'michael latham powell',
  'nodos_a_fusionar': ['michael powell']},
 {'nodo_principal': 'michel jacques boisrond',
  'nodos_a_fusionar': ['michel boisrond']},
 {'nodo_principal': 'miklós jancs ó', 'nodos_a_fusionar': ['miklós jancs']},
 {'nodo_principal': 'military intelligence organization',
  'nodos_a_fusionar': ['military intelligence']},
 {'nodo_principal': 'mirza ghulam ahmad of qadian',
  'nodos_a_fusionar': ['mirza ghulam ahmad']},
 {'nodo_principal': 'mohamed husseini mohamed',
  'nodos_a_fusionar': ['mohamed husseini']},
 {'nodo_principal': 'mohamed abdelaziz',
  'nodos_a_fusionar': ['mohamed mahmoud abdelaziz',
   'mohamed abdelaziz tchikou']},
 {'nodo_principal': 'morena clara (telenovela)',
  'nodos_a_fusionar': ['morena clara']},
 {'nodo_principal': 'motion picture',
  'nodos_a_fusionar': ['motion picture actor', 'motion picture director']},
 {'nodo_principal': 'mph group malaysia', 'nodos_a_fusionar': ['mph group']},
 {'nodo_principal': 'mr moto', 'nodos_a_fusionar': ["mr moto's gamble"]},
 {'nodo_principal': 'mr boggs steps out',
  'nodos_a_fusionar': ['mr muggs steps out',
   'muggs steps out',
   'boggs steps out']},
 {'nodo_principal': 'musical film',
  'nodos_a_fusionar': ['musical drama film']},
 {'nodo_principal': 'always in my heart',
  'nodos_a_fusionar': ['my heart', 'in my heart']},
 {'nodo_principal': 'naghan district',
  'nodos_a_fusionar': ['naghan rural district']},
 {'nodo_principal': 'nancy ann travis', 'nodos_a_fusionar': ['nancy travis']},
 {'nodo_principal': 'nandi award for best director',
  'nodos_a_fusionar': ['nandi award for best director – telugu']},
 {'nodo_principal': 'national gallery of australia',
  'nodos_a_fusionar': ['national gallery of australia (canberra)']},
 {'nodo_principal': 'new democratic party',
  'nodos_a_fusionar': ['democratic party']},
 {'nodo_principal': 'new kent county',
  'nodos_a_fusionar': ['new kent county, virginia']},
 {'nodo_principal': 'new york city', 'nodos_a_fusionar': ['new york']},
 {'nodo_principal': 'a night at the movies',
  'nodos_a_fusionar': ['night at the movies']},
 {'nodo_principal': 'nila madhab panda', 'nodos_a_fusionar': ['nila madhab']},
 {'nodo_principal': 'noura khalifa al suwaidi',
  'nodos_a_fusionar': ['noura khalifa']},
 {'nodo_principal': "o' grady", 'nodos_a_fusionar': ["o'grady"]},
 {'nodo_principal': 'odrysian kingdom',
  'nodos_a_fusionar': ['odrysian kingdom of thrace']},
 {'nodo_principal': 'one touch of venus',
  'nodos_a_fusionar': ['one touch of venus (film)']},
 {'nodo_principal': 'oscar c apfel', 'nodos_a_fusionar': ['oscar apfel']},
 {'nodo_principal': 'oxford university cricket club',
  'nodos_a_fusionar': ['oxford university']},
 {'nodo_principal': 'pahlavi dynasties',
  'nodos_a_fusionar': ['pahlavi dynasty']},
 {'nodo_principal': 'marc paul alain dutroux',
  'nodos_a_fusionar': ['paul alain dutroux']},
 {'nodo_principal': 'peer-reviewed', 'nodos_a_fusionar': ['peer-review']},
 {'nodo_principal': 'philip ives dunne', 'nodos_a_fusionar': ['philip dunne']},
 {'nodo_principal': "pier giorgio dall'acqua",
  'nodos_a_fusionar': ["giorgio dall'acqua"]},
 {'nodo_principal': 'pinal county',
  'nodos_a_fusionar': ['pinal county, arizona']},
 {'nodo_principal': 'pornographic film',
  'nodos_a_fusionar': ['pornographic film director']},
 {'nodo_principal': 'prince henry, duke of cumberland and strathearn',
  'nodos_a_fusionar': ['prince henry, duke of cumberland']},
 {'nodo_principal': 'princess augusta of saxe-gotha',
  'nodos_a_fusionar': ['princess augusta of saxe-gotha-altenburg']},
 {'nodo_principal': 'rafe kovich and alison barrington kovich',
  'nodos_a_fusionar': ['rafe kovich and alison barrington']},
 {'nodo_principal': 'rapid rail', 'nodos_a_fusionar': ['rapid rail sdn bhd']},
 {'nodo_principal': 'razavi khorasan province',
  'nodos_a_fusionar': ['razavi khorasan']},
 {'nodo_principal': 'rhett akins', 'nodos_a_fusionar': ['rhett akins jr']},
 {'nodo_principal': 'richard of shrewsbury, 1st duke of york',
  'nodos_a_fusionar': ['richard of shrewsbury, 1']},
 {'nodo_principal': 'richard woodville, 1st earl rivers',
  'nodos_a_fusionar': ['richard woodville, 1st']},
 {'nodo_principal': 'robert r parrish',
  'nodos_a_fusionar': ['robert parrish']},
 {'nodo_principal': 'robert the bruce, king of scots',
  'nodos_a_fusionar': ['robert the bruce']},
 {'nodo_principal': 'roman catholic',
  'nodos_a_fusionar': ['roman catholic church']},
 {'nodo_principal': 'roman catholic diocese of sioux falls',
  'nodos_a_fusionar': ['roman catholic diocese of springfield',
   'roman catholic diocese of springfield in illinois']},
 {'nodo_principal': 'romantic comedy',
  'nodos_a_fusionar': ['romantic comedy film']},
 {'nodo_principal': 'royal oak, michigan', 'nodos_a_fusionar': ['royal oak']},
 {'nodo_principal': 'royal veterinary academy of berlin',
  'nodos_a_fusionar': ['royal veterinary academy']},
 {'nodo_principal': 'rukn al-din mubarak khwaja',
  'nodos_a_fusionar': ['rukn al-din mubarak']},
 {'nodo_principal': 'rush dew holt sr', 'nodos_a_fusionar': ['rush dew holt']},
 {'nodo_principal': 'salehabad rural district',
  'nodos_a_fusionar': ['salehabad district']},
 {'nodo_principal': 'english name', 'nodos_a_fusionar': ['same english name']},
 {'nodo_principal': 'san francisco, california',
  'nodos_a_fusionar': ['san francisco']},
 {'nodo_principal': 'santa clara',
  'nodos_a_fusionar': ['santa clara county, california',
   'santa clara university',
   'santa clara, california',
   'santa clara county']},
 {'nodo_principal': 'santa maría',
  'nodos_a_fusionar': ['santa maría de oseira']},
 {'nodo_principal': 'sarre anglo-saxon cemetery',
  'nodos_a_fusionar': ['sarre anglo-saxon']},
 {'nodo_principal': 'sasikumar', 'nodos_a_fusionar': ['j sasikumar']},
 {'nodo_principal': 'saturday night at the movies',
  'nodos_a_fusionar': ['saturday night fever']},
 {'nodo_principal': 'science fiction',
  'nodos_a_fusionar': ['science fiction film']},
 {'nodo_principal': 'scr corporation sdn bhd',
  'nodos_a_fusionar': ['scr corporation']},
 {'nodo_principal': 'sedeh district',
  'nodos_a_fusionar': ['sedeh rural district']},
 {'nodo_principal': 'sex comedy film', 'nodos_a_fusionar': ['sex comedy']},
 {'nodo_principal': 'shannon lee',
  'nodos_a_fusionar': ['shannon lee sanderford',
   'shannon lee dawdy',
   'shannon lee tweed',
   'shannon emery',
   'shannon lee day',
   'shannon emery lee',
   'shannon lee tweed simmons']},
 {'nodo_principal': 'sheikha latifa', 'nodos_a_fusionar': ['sheika latifa']},
 {'nodo_principal': 'sheikh ahmed bin rashid al maktoum',
  'nodos_a_fusionar': ['ahmed bin rashid al maktoum']},
 {'nodo_principal': 'mohammed bin rashid al maktoum',
  'nodos_a_fusionar': ['mohammed bin rashid al',
   'sheikh mohammed bin rashid al maktoum',
   'mohammed bin rashid al maktou']},
 {'nodo_principal': 'sherlock holmes',
  'nodos_a_fusionar': ['sherlock holmes films']},
 {'nodo_principal': 'shocking asia', 'nodos_a_fusionar': ['shocking asia ii']},
 {'nodo_principal': 'sierra leone',
  'nodos_a_fusionar': ['sierra leone president']},

In [ ]:
query_fusion = """
UNWIND $grupos AS grupo
// 1. Buscamos el nodo principal en la base de datos (reemplaza :Entidad por tu etiqueta real)
MATCH (principal:Entity {name: grupo.nodo_principal})

// 2. Buscamos todos los nodos secundarios que pertenecen a ese mismo grupo
MATCH (secundarios:Entity)
WHERE secundarios.name IN grupo.nodos_a_fusionar 

// 3. Agrupamos los nodos secundarios en una lista
WITH principal, collect(secundarios) AS nodos_secundarios

// 4. Invocamos la función de APOC para fusionarlos todos en el principal
CALL apoc.refactor.mergeNodes([principal] + nodos_secundarios, {
  properties: {
    name: "discard",
    `*`: "combine"
  },
  mergeRels: true
}) YIELD node
RETURN count(node) AS fusiones_realizadas
"""

In [309]:
records, summary, key = driver.execute_query(query_fusion, grupos = datos_para_neo4j)

In [310]:
records

In [75]:
df_final

NameError: name 'df_final_excluidos_nombres' is not defined

# FUNCION GENERAL FUSIONAR NODOS

## Funciones

In [9]:
def calcular_rank_B25s(entidades, n_candidatos):
   entidades_token = bm25s.tokenize(entidades, stopwords="en")
   retriever = bm25s.BM25()
   retriever.index(entidades_token)
   results, scores = retriever.retrieve(entidades_token, k=n_candidatos)
   cols_sim = []
   cols_score = []
   for i in range(1, n_candidatos+1):
      cols_sim.append(f"similar_{i}")
      cols_score.append(f"score_{i}")
      
   df_resultados = pd.DataFrame(data=results, columns=cols_sim)
   df_scores = pd.DataFrame(scores, columns=cols_score)
   df_resultados = df_resultados.map(lambda x: entidades[x])
   df_rank_25 = pd.concat([df_resultados, df_scores], axis=1)
   df_rank_25['Entidad'] = entidades
   return df_rank_25

In [10]:
def encontrar_candidatos_iguales_principal(df, n_candidatos):
    
    for i in range(1, n_candidatos+1):
        df[f"entidad_similar_{i}_iguales"] = False
        df.loc[df["Entidad"] == df[f"similar_{i}"], f"entidad_similar_{i}_iguales"] = True
    return df

In [11]:
def get_columnas(n_candidatos):
    cols_jaro = []
    cols_leven = []
    cols_jaccard = []
    cols_overlap = []
    cols_exc_num = []
    cols_exc_nom = []
    for i in range(1, n_candidatos+1):
        cols_jaro.append(f"dist_jaro_{i}")
        cols_leven.append(f"dist_leven_{i}")
        cols_jaccard.append(f"dist_jaccard_{i}")
        cols_overlap.append(f"dist_overlap_{i}")
        cols_exc_num.append(f"excluir_num_{i}")
        cols_exc_nom.append(f"excluir_nom_{i}")
    cols_distancias = cols_jaro + cols_leven + cols_jaccard + cols_overlap
    
    return cols_distancias, cols_exc_num, cols_exc_nom

In [13]:
def calcular_distancias(fila, n_candidatos):
    doc_ent = nlp(fila['Entidad'])
    ent_sw_removed = " ".join([token.text for token in doc_ent if not token.is_stop and not token.is_punct])
    
    distancias_jaro = []
    distancias_leven = []
    distancias_jaccard = []
    distancias_overlap = []
    for i in range(1, n_candidatos+1):
        doc_sim = nlp(fila[f'similar_{i}'])
        sim_sw_removed = " ".join([token.text for token in doc_sim if not token.is_stop and not token.is_punct])
        dist_jaro = textdistance.jaro_winkler(ent_sw_removed, sim_sw_removed)
        dist_leven = textdistance.levenshtein.normalized_similarity(ent_sw_removed, sim_sw_removed)
        dist_jaccard = textdistance.jaccard.normalized_similarity(ent_sw_removed, sim_sw_removed)
        dist_overlap = textdistance.overlap.normalized_similarity(ent_sw_removed, sim_sw_removed)
        
        distancias_jaro.append(dist_jaro)
        distancias_leven.append(dist_leven)
        distancias_jaccard.append(dist_jaccard)
        distancias_overlap.append(dist_overlap)
    
    return distancias_jaro + distancias_leven + distancias_jaccard + distancias_overlap

In [14]:
def excluir_por_numeros(fila, n_candidatos):
    
    regex_romanos = r"\b(v[ii]{0,3}|i[vx]|x[lcvi]{0,4}|i{1,3})\b"
    romanos_ent = set(re.findall(regex_romanos, fila["Entidad"]))
    
    regex_numeros = r"\d+"
    numeros_ent = set(re.findall(regex_numeros, fila["Entidad"]))
    
    excluir = [False, False, False]
    
    for i in range(1, n_candidatos+1):
        romanos_sim = set(re.findall(regex_romanos, fila[f"similar_{i}"]))
        # if romanos_ent and romanos_sim and romanos_ent != romanos_sim:
        if romanos_ent != romanos_sim:
            excluir[i-1] = True
                
        numeros_sim = set(re.findall(regex_numeros, fila[f"similar_{i}"]))
        if numeros_ent != numeros_sim:
            excluir[i-1] = True
    
    return excluir

In [15]:
def excluir_por_nombre(fila, n_candidatos):
    
    doc_ent = nlp(fila['Entidad'])
    ents_ent = {ent.text: ent.label_ for ent in doc_ent.ents}
    palabras_ent = {ent.text for ent in doc_ent.ents}
    labels_excluir = ["PERSON", "GPE", "ORG"]
    
    exclusion = [False, False, False]
    
    for i in range(1, n_candidatos+1):
        if len(fila['Entidad'].split()) == len(fila[f'similar_{i}'].split()):

            doc_sim = nlp(fila[f'similar_{i}'])
            ents_sim = {ent.text: ent.label_ for ent in doc_sim.ents}
            palabras_sim = {ent.text for ent in doc_sim.ents}
            
            diferencias = palabras_ent.symmetric_difference(palabras_sim)

            for palabra_dif in diferencias:
                label_e = ents_ent.get(palabra_dif)
                label_sim = ents_sim.get(palabra_dif)
                if label_e in labels_excluir or label_sim in labels_excluir:
                    exclusion[i-1] = True

    return exclusion

In [16]:
def filtrar_fusionables(df, n_similares):
    
    for i in range(1, n_similares+1):
        col_jaro = f"dist_jaro_{i}"
        col_leven = f"dist_leven_{i}"
        col_jaccard = f"dist_jaccard_{i}"
        col_overlap = f"dist_overlap_{i}"
        col_score = f"score_{i}"
        
        col_ex_num = f"excluir_num_{i}"
        col_ex_nom = f"excluir_nom_{i}"
        col_sim_igual = f"entidad_similar_{i}_iguales"
        
        col_exclusion = f"exclusion_{i}"
        col_fusion = f"fusion_{i}"
        
        df[col_exclusion] = False
        df.loc[(df[col_ex_num] == True) | (df[col_ex_nom] == True) | (df[col_sim_igual] == True), col_exclusion] = True
        
        filtro_1 = (
            (
                (
                    (df[col_jaro].between(0.8, 0.999)) & (df[col_leven].between(0.75, 0.999))
                    ) |
                (
                    (df[col_jaro].between(0.9, 0.999)) & (df[col_leven].between(0.71, 0.999))
                    )
                ) &
            (df[col_score] > 4.5) &
            (df[col_exclusion] == False) 
            )
        
        filtro_2 = (
            (df[col_jaro].between(0.9, 0.999)) &
            (df[col_leven].between(0.8, 0.999)) &
            (df[col_score] > 2) &
            (df[col_exclusion] == False) 
            )
        
        filtro_3 = (
            (df[col_overlap] == 1) &
            (df[col_jaro] >= 0.9) &
            (df[col_score] >= 4.5) &
            (df[col_exclusion] == False) 
            )
        
        df[col_fusion] = False
        df.loc[filtro_1, col_fusion] = True
        df.loc[filtro_2, col_fusion] = True
        df.loc[filtro_3, col_fusion] = True
        
    return df

In [ ]:
def unir_candidatos(df, n_candidatos):
    df_union = pd.DataFrame()
    for i in range(1, n_candidatos+1):
        cols_union = ['Entidad', f'similar_{i}',f'score_{i}',f'dist_jaro_{i}', f'dist_leven_{i}',f'dist_jaccard_{i}', f'dist_overlap_{i}',f'fusion_{i}']
        df_filt = df.loc[df[f'fusion_{i}'] == True, cols_union]
        rename_cols = {f'similar_{i}': "similar",f'score_{i}': "score",f'dist_jaro_{i}': "dist_jaro", f'dist_leven_{i}': "dist_leven",f'dist_jaccard_{i}': "dist_jaccard", f'dist_overlap_{i}': "dist_overlap",f'fusion_{i}': "fusion"}
        df_filt = df_filt.rename(columns = rename_cols)
        df_union = pd.concat([df_union, df_filt], ignore_index=True)
    df_union = df_union.drop_duplicates(["Entidad", "similar"]).sort_values("Entidad").reset_index(drop=True)
    return df_union

In [18]:
def grupos_fusion(df):
    entidades_1 = df['Entidad'].tolist()
    entidades_2 = df['similar'].tolist()
    grupos = []

    for ent_1, ent_2 in zip(entidades_1, entidades_2):
        encontrados = []
        for grupo in grupos:
            if ent_1 in grupo or ent_2 in grupo:
                encontrados.append(grupo)

        if not encontrados:
            grupos.append({ent_1, ent_2})
        else:
            nuevo_grupo = {ent_1, ent_2}
            for g in encontrados:
                nuevo_grupo.update(g)
                grupos.remove(g)
            grupos.append(nuevo_grupo)

    return [list(g) for g in grupos]

In [19]:
def obtener_grados_nodos(driver, df):
# def obtener_grados_nodos(self, df):
    
    entidades = df['Entidad'].tolist()
    similares = df['similar'].tolist()
    set_entidades = list(set(entidades + similares)) 
    
    query = """
        UNWIND $entidades as entidad
        MATCH (n:Entity {name: entidad})
        RETURN n.name AS name, COUNT{(n)--()} AS n_relaciones
    """
    records, summary, key = driver.execute_query(query, entidades = set_entidades)
    # records, summary, key = self.driver.execute_query(get_n_relaciones, entidades = set_entidades, database_ = self.database)
    grados = {rec['name']: rec['n_relaciones'] for rec in records}
    return grados

In [20]:
def seleccionar_nodo_principal(grupos, grados):
    nodos_fusion = {}
    for grupo in grupos:
        
        nodo_principal = max(grupo, key = len)
        for ent in grupo:
            if grados[ent] > grados[nodo_principal]:
                nodo_principal = ent
        nodos_fusion[nodo_principal] = [sec for sec in grupo if sec != nodo_principal]
        
    nodos_fusion_neo4j = [
        {
            "nodo_principal": grupo,
            "nodos_a_fusionar": nodos_fusion[grupo]
        }
        for grupo in nodos_fusion
    ]
    return nodos_fusion_neo4j

In [21]:
# def fusionar_nodos(self, nodos_fusion):
def fusionar_nodos(driver, nodos_fusion):
    query_fusion = """
        UNWIND $grupos AS grupo
        
        MATCH (principal:Entity {name: grupo.nodo_principal})

        MATCH (secundarios:Entity)
        WHERE secundarios.name IN grupo.nodos_a_fusionar 

        WITH principal, collect(secundarios) AS nodos_secundarios, grupo.nodos_a_fusionar AS names_fusionados

        CALL apoc.refactor.mergeNodes([principal] + nodos_secundarios, {
        properties: {
            name: "discard",
            `\\*`: "combine"
        },
        mergeRels: true
        }) YIELD node

        SET node.fusionados = names_fusionados
        RETURN count(node) AS fusiones_realizadas
    """
    records, summary, key = driver.execute_query(query_fusion, grupos = nodos_fusion)
    # records, summary, key = self.driver.execute_query(query_fusion, grupos = datos_para_neo4j, , database_ = self.database)
    return records[0]["fusiones_realizadas"]

## Ejecucion

In [22]:
nlp = spacy.load("en_core_web_sm")
database_Neo = "2wiki.prueba.rebel.5"
conn_Neo4j = ConexionNeo4j(database_Neo)
driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=("neo4j", "password"),
    database = database_Neo,
)

In [23]:
entidades = conn_Neo4j.extraer_all_entidades_neo4j()
n_candidatos = 3

df_deduplicacion = calcular_rank_B25s(entidades, n_candidatos)

df_deduplicacion = encontrar_candidatos_iguales_principal(df_deduplicacion, n_candidatos)

cols_distancias, cols_exc_num, cols_exc_nom = get_columnas(n_candidatos)

df_deduplicacion[cols_distancias] = df_deduplicacion.apply(calcular_distancias, args=(n_candidatos,), axis = 1, result_type='expand')

df_deduplicacion[cols_exc_num] = df_deduplicacion.apply(excluir_por_numeros, args=(n_candidatos,), axis = 1, result_type='expand')
df_deduplicacion[cols_exc_nom] = df_deduplicacion.apply(excluir_por_nombre, args=(n_candidatos,), axis = 1, result_type='expand')
df_deduplicacion = filtrar_fusionables(df_deduplicacion, n_candidatos)

df_deduplicacion_final = unir_candidatos(df_deduplicacion, n_candidatos)
grupos = grupos_fusion(df_deduplicacion_final)
grados = obtener_grados_nodos(driver, df_deduplicacion_final)
nodos_fusion = seleccionar_nodo_principal(grupos, grados)
nodos_fusionados = fusionar_nodos(driver, nodos_fusion)

In [30]:
df_desambiguacion_final

,Entidad,similar,score,dist_jaro,dist_leven,dist_jaccard,dist_overlap,fusion
1,abd al-muttalib shaybah ibn hashim,abd al-muttalib shaybah,5.715919,0.935294,0.676471,0.676471,1.0,True
3,australian rules football,australian rules footballer,3.132057,0.985185,0.925926,0.925926,1.0,True
5,australian rules footballer,australian rules football,3.132057,0.985185,0.925926,0.925926,1.0,True
0,director general of police in punjab,director general of police,4.682092,0.953333,0.766667,0.766667,1.0,True
4,film director,film and tv director,2.164951,0.916346,0.812500,0.812500,1.0,True
2,national gallery of australia (canberra),national gallery of australia,4.932418,0.948571,0.742857,0.742857,1.0,True

In [26]:
nodos_fusionados

5

## Fusion similares_1

In [25]:
cols_ = ['Entidad', 'similar_1','score_1',
       'dist_jaro_1', 'dist_leven_1',
       'dist_jaccard_1', 'dist_overlap_1',
       'excluir_num_1', 'excluir_nom_1','fusion_1']

sim_1_fus = df_final[df_final['fusion_1'] == True][cols_]
sim_1_fus

NameError: name 'df_final' is not defined

# Revision

## Fusion similares_3

In [241]:
cols_ = ['Entidad', 'similar_3','score_3',
       'dist_jaro_3', 'dist_leven_3',
       'dist_jaccard_3', 'dist_overlap_3',
       'excluir_num_3', 'excluir_nom_3','fusion_3']

sim_3_fus = df_final[df_final['fusion_3'] == True][cols_]
sim_3_fus

,Entidad,similar_3,score_3,dist_jaro_3,dist_leven_3,dist_jaccard_3,dist_overlap_3,excluir_num_3,excluir_nom_3,fusion_3
55,la torre de los suplicios,la torre de suso,5.409472,0.915500,0.600000,0.640000,1.00,False,False,True
64,mazraeh-ye ali,mazraeh-ye ali shafi,4.874711,0.940000,0.700000,0.700000,1.00,False,False,True
87,"st mary's high school, quetta",st mary high school,6.455689,0.946154,0.730769,0.730769,1.00,False,False,True
90,mohammed bin rashid al maktoum,mohammed bin rashid al,6.681687,0.946667,0.733333,0.733333,1.00,False,False,True
94,jack ryan conway,jack conway,5.652337,0.901136,0.687500,0.687500,1.00,False,False,True
...,...,...,...,...,...,...,...,...,...,...
5715,motion picture director,motion picture actor,4.684707,0.934165,0.826087,0.791667,0.95,False,False,True
5774,motion picture actor,motion picture director,4.684707,0.934165,0.826087,0.791667,0.95,False,False,True
5981,children's books,children's book,2.940352,0.985714,0.928571,0.928571,1.00,False,False,True
6054,sierra leonean,sierra leonean army,4.947297,0.947368,0.736842,0.736842,1.00,False,False,True
6176,the piano tuner has,the piano tuner,6.258420,1.000000,1.000000,1.000000,1.00,False,False,True

## Fusion similares_1

In [242]:
cols_ = ['Entidad', 'similar_1','score_1',
       'dist_jaro_1', 'dist_leven_1',
       'dist_jaccard_1', 'dist_overlap_1',
       'excluir_num_1', 'excluir_nom_1','fusion_1']

sim_1_fus = df_final[df_final['fusion_1'] == True][cols_]
sim_1_fus

,Entidad,similar_1,score_1,dist_jaro_1,dist_leven_1,dist_jaccard_1,dist_overlap_1,excluir_num_1,excluir_nom_1,fusion_1
141,sasikumar,j sasikumar,4.153368,0.939394,0.818182,0.818182,1.000000,False,False,True
179,the star of india,star of india,5.522741,1.000000,1.000000,1.000000,1.000000,False,False,True
346,the sword stained with royal blood,sword stained with royal blood,8.201560,1.000000,1.000000,1.000000,1.000000,False,False,True
364,the young philadelphians,young philadelphians,5.621514,1.000000,1.000000,1.000000,1.000000,False,False,True
465,why did i get married,why did i get married?,8.270607,1.000000,1.000000,1.000000,1.000000,False,False,True
486,it goes like this,it goes like it goes,6.027068,0.928571,0.642857,0.642857,1.000000,False,False,True
647,a night at the movies,night at the movies,5.382150,1.000000,1.000000,1.000000,1.000000,False,False,True
659,fazle karim chowdhury,a b m fazle karim chowdhury,6.707862,0.851429,0.840000,0.840000,1.000000,False,False,True
675,cradle of humankind,the cradle of humankind,6.210154,1.000000,1.000000,1.000000,1.000000,False,False,True
732,g marthandan,marthandan,4.153368,0.944444,0.833333,0.833333,1.000000,False,False,True
736,manuel i komnenos,manuel komnenos,6.210154,1.000000,1.000000,1.000000,1.000000,False,False,True
814,white god,the white god,5.939967,1.000000,1.000000,1.000000,1.000000,False,False,True
816,the first part,first part,5.394909,1.000000,1.000000,1.000000,1.000000,False,False,True
835,toma n socolescu,toma t socolescu,6.069562,0.975000,0.937500,0.882353,0.937500,False,False,True
921,the second part,second part,5.964553,1.000000,1.000000,1.000000,1.000000,False,False,True
968,the legend of the condor heroes,legend of the condor heroes,7.039692,1.000000,1.000000,1.000000,1.000000,False,False,True
1046,augustus barratt,w augustus barratt,6.210154,0.879630,0.888889,0.888889,1.000000,False,False,True
1080,the norman rockwell code,norman rockwell code,7.545347,1.000000,1.000000,1.000000,1.000000,False,False,True
1289,william a berke,william berke,5.430972,1.000000,1.000000,1.000000,1.000000,False,False,True
1388,in my heart,my heart,5.129168,1.000000,1.000000,1.000000,1.000000,False,False,True
1404,so it goes,and so it goes,5.964553,1.000000,1.000000,1.000000,1.000000,False,False,True
1478,robert r parrish,robert parrish,5.569216,0.960714,0.875000,0.875000,1.000000,False,False,True
1555,pony express,the pony express,6.539603,1.000000,1.000000,1.000000,1.000000,False,False,True
1932,list of films produced in uruguay,a list of films produced in uruguay,7.663694,1.000000,1.000000,1.000000,1.000000,False,False,True
1953,united arab emirates (uae),united arab emirates (uae,8.102932,1.000000,1.000000,1.000000,1.000000,False,False,True
1966,fools' hall of fame,the fools' hall of fame,7.305106,1.000000,1.000000,1.000000,1.000000,False,False,True
1981,oscar c apfel,oscar apfel,6.399011,0.969231,0.846154,0.846154,1.000000,False,False,True
2049,indie-rock,indie rock,6.069562,1.000000,1.000000,1.000000,1.000000,False,False,True
2129,victor l schertzinger,victor schertzinger,6.399011,0.980952,0.904762,0.904762,1.000000,False,False,True
2140,george h melford,george melford,5.480923,0.975000,0.875000,0.875000,1.000000,False,False,True
2158,colvos store,the colvos store,6.539603,1.000000,1.000000,1.000000,1.000000,False,False,True
2165,good old days,the good old days,7.158574,1.000000,1.000000,1.000000,1.000000,False,False,True
2184,do you remember dolly bell?,do you remember dolly bell,8.935630,1.000000,1.000000,1.000000,1.000000,False,False,True
2191,a b fazle karim chowdhury,a b m fazle karim chowdhury,6.707862,0.909101,0.920000,0.920000,1.000000,False,False,True
2246,rafe kovich and alison barrington,rafe kovich and alison barrington kovich,9.082749,0.961111,0.805556,0.805556,1.000000,False,False,True
2342,jatt& juliet,jatt & juliet,6.153410,1.000000,1.000000,1.000000,1.000000,False,False,True
2394,a m fazle karim chowdhury,a b m fazle karim chowdhury,6.707862,0.871884,0.920000,0.920000,1.000000,False,False,True
2427,i don't believe you (she acts like we never ha...,i don't believe you (she acts like we never ha...,11.298933,1.000000,1.000000,1.000000,1.000000,False,False,True
2432,list of films produced in turkmenistan,a list of films produced in turkmenistan,7.663694,1.000000,1.000000,1.000000,1.000000,False,False,True
2481,bernard n nathanson,bernard nathanson,6.539603,0.931889,0.894737,0.894737,1.000000,False,False,True
2576,international school of columbus,the international school of columbus,5.709929,1.000000,1.000000,1.000000,1.000000,False,False,True
2604,mohamed husseini,mohamed husseini mohamed,6.079639,0.933333,0.666667,0.666667,1.000000,False,False,True
2714,university of wisconsin-madison,university of wisconsin – madison,6.741518,1.000000,1.000000,1.000000,1.000000,False,False,True
2767,o' grady,o'grady,3.974786,0.914286,0.857143,0.750000,0.857143,False,False,True
2768,theme music,the theme music,5.505509,1.000000,1.000000,1.000000,1.000000,False,False,True
2941,i'm a celebrity get me out of here!,i'm a celebrity get me out of here!,8.898523,0.963636,0.818182,0.818182,1.000000,False,False,True
2973,a thief has arrived,thief has arrived,7.770215,1.000000,1.000000,1.000000,1.000000,False,False,True
3054,g devarajan,devarajan,3.974786,0.939394,0.818182,0.818182,1.000000,False,False,True
3064,the model technical higher secondary school,model technical higher secondary school,8.059068,1.000000,1.000000,1.000000,1.000000,False,False,True
3142,another latin love song/ miss world,another latin love song/miss world,8.774432,0.992593,0.962963,0.962963,1.000000,False,False,True
3153,a m b fazle karim chowdhury,a b m fazle karim chowdhury,6.707862,0.986667,0.920000,1.000000,1.000000,False,False,True
3317,william marshall (died 1540),william marshall (died 1540?),8.018923,1.000000,1.000000,1.000000,1.000000,False,False,True
3790,film and television director,film/television director,5.348121,1.000000,1.000000,1.000000,1.000000,False,False,True
4433,comedy drama film,comedy-drama film,5.320801,1.000000,1.000000,1.000000,1.000000,False,False,True
4577,dubai ruling family,dubai's ruling family,7.512767,1.000000,1.000000,1.000000,1.000000,False,False,True
4820,miklós jancs ó,miklós jancs,6.539603,0.971429,0.857143,0.857143,1.000000,False,False,True

## Fusion similares_2

In [247]:
cols_ = ['Entidad', 'similar_2','score_2',
       'dist_jaro_2', 'dist_leven_2',
       'dist_jaccard_2', 'dist_overlap_2',
       'excluir_num_2', 'excluir_nom_2','fusion_2']

sim_2_fus = df_final[df_final['fusion_2'] == True][cols_]
sim_2_fus

,Entidad,similar_2,score_2,dist_jaro_2,dist_leven_2,dist_jaccard_2,dist_overlap_2,excluir_num_2,excluir_nom_2,fusion_2
0,night at the movies,a night at the movies,5.382150,1.000000,1.000000,1.000000,1.0,False,False,True
16,salehabad rural district,salehabad district,4.983867,0.927778,0.750000,0.750000,1.0,False,False,True
31,rafe kovich and alison barrington kovich,rafe kovich and alison barrington,11.370578,0.961111,0.805556,0.805556,1.0,False,False,True
36,edward iv of england,"edward iv, king of england",5.534581,0.919251,0.772727,0.772727,1.0,False,False,True
40,mission: impossible,mission: impossible iii,4.791569,0.963636,0.818182,0.818182,1.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...
6176,the piano tuner has,the piano tuner has arrived,6.511972,0.915789,0.578947,0.578947,1.0,False,False,True
6189,eleni zaude gabre,eleni zaude gabre-madhin,6.881523,0.941667,0.708333,0.708333,1.0,False,False,True
6204,stefano dell',stefano dell' arzere,4.849126,0.926316,0.631579,0.631579,1.0,False,False,True
6224,boggs steps out,mr boggs steps out,6.112169,0.867965,0.785714,0.785714,1.0,False,False,True
6228,electric clouds,under electric clouds,5.160583,1.000000,1.000000,1.000000,1.0,False,False,True

In [244]:
cols_2 = ['Entidad', 'similar_2','score_2','dist_jaro_2', 'dist_leven_2','dist_jaccard_2', 'dist_overlap_2', 'excluir_num_2', 'excluir_nom_2', 'fusion_2'  ]

In [248]:
df_final_2_NO_fusionar = df_final[(df_final['fusion_2'] == False) & (df_final['dist_jaro_2'] != 1) & (df_final['excluir_num_2'] == False)][cols_2]

In [249]:
df_final_2_NO_fusionar

,Entidad,similar_2,score_2,dist_jaro_2,dist_leven_2,dist_jaccard_2,dist_overlap_2,excluir_num_2,excluir_nom_2,fusion_2
2,jack shea,jack ferver,2.711984,0.842424,0.545455,0.428571,0.666667,False,True,False
3,harry johnson,emory johnson,2.870550,0.712821,0.769231,0.625000,0.769231,False,True,False
4,harsin,harsin county,3.269801,0.892308,0.461538,0.461538,1.000000,False,False,False
5,dance or die,dance,3.646231,0.911111,0.555556,0.555556,1.000000,False,False,False
6,lord of tears,lord salisbury,2.940352,0.849286,0.428571,0.500000,0.800000,False,False,False
...,...,...,...,...,...,...,...,...,...,...
6252,iranian,roman,0.000000,0.676190,0.428571,0.333333,0.600000,False,False,False
6254,romanian,roman,0.000000,0.925000,0.625000,0.625000,1.000000,False,False,False
6255,chahār,roman,0.000000,0.455556,0.000000,0.222222,0.400000,False,False,False
6256,greek,roman,0.000000,0.466667,0.000000,0.111111,0.200000,False,False,False
6257,roman,roman emperor,2.632154,0.876923,0.384615,0.384615,1.000000,False,False,False